Repository pingcap/tiup, pull requests merged in 2020-12, with the labels that each got.

#933 fix the exit order of the components of playground
  components/playground/instance/proc_attr_linux.go
  components/playground/playground.go
Labels: first-time-contributor, good-first-issue, size/S, status/LGT1, status/can-merge, type/enhancement

#948 Support host names in TLS certificates
  pkg/cluster/task/tls.go
Labels: first-time-contributor, size/S, status/LGT1, status/can-merge

#949 Fix PD --peer-urls flag to use listen_host variable
  pkg/cluster/embed/autogen_pkger.go
  templates/scripts/run_pd.sh.tpl
  templates/scripts/run_pd_scale.sh.tpl
Labels: first-time-contributor, need-more-test, need-update-documentation, size/XS, status/LGT1, status/can-merge

#953 Fix the dependencies field to match the specification
  pkg/repository/v1manifest/manifest.go
  pkg/repository/v1manifest/types.go
Labels: size/S, type/bug-fix

#951 Utilize TiKV --advertise-status-addr
  pkg/cluster/embed/autogen_pkger.go
  pkg/cluster/spec/tikv.go
  pkg/cluster/template/scripts/tikv.go
  templates/scripts/run_tikv.sh.tpl
  tests/tiup-cluster/script/cmd_subtest.sh
Labels: size/M, status/LGT1

#970 typo(*): TiOps -> TiUp
  components/cluster/command/import.go
  components/dm/command/scale_in.go
  components/dm/spec/cluster.go
  components/dm/spec/logic.go
  examples/dm/minimal.yaml
  examples/dm/topology.example.yaml
  examples/minimal.yaml
  examples/multi-dc.yaml
  examples/topology.example.yaml
  pkg/cliutil/cliutil.go
  pkg/cluster/ansible/test-data/group_vars/alertmanager_servers.yml
  pkg/cluster/ansible/test-data/group_vars/all.yml
  pkg/cluster/ansible/test-data/group_vars/drainer_servers.yml
  pkg/cluster/ansible/test-data/group_vars/grafana_servers.yml
  pkg/cluster/ansible/test-data/group_vars/lightning_server.yml
  pkg/cluster/ansible/test-data/group_vars/monitored_servers.yml
  pkg/cluster/ansible/test-data/group_vars/monitoring_servers.yml
  pkg/cluster/ansible/test-data/group_vars/pump_servers.yml
  pkg/cluster/ansible/test-data/meta.yaml
  pkg/cluster/embed/autogen_pkger.go
  pkg/cluster/executor/executor.go
  pkg/cluster/module/shell.go
  pkg/cluster/operation/destroy.go
  pkg/cluster/spec/profile.go
  pkg/cluster/spec/spec_manager.go
  pkg/cluster/spec/testdata/topology_err.yaml
  pkg/cluster/spec/util.go
  pkg/cluster/task/builder.go
  pkg/cluster/task/task.go
  pkg/crypto/keys.go
  pkg/environment/env.go
  pkg/localdata/constant.go
  pkg/localdata/profile.go
  pkg/repository/constant.go
  pkg/repository/mirror.go
  pkg/repository/repository.go
  pkg/repository/repository_test.go
  pkg/repository/v1_repository.go
  pkg/repository/v1manifest/manifest.go
  pkg/telemetry/testdata/full.yaml
  pkg/telemetry/testdata/single/nilvalue.yaml
  templates/config/alertmanager.yml
  templates/config/blackbox.yml
  tools/migrate/main.go
Labels: size/XXL, status/LGT1, status/can-merge

#973 Fix/playground noset localhost
  components/playground/instance/instance.go
  pkg/cluster/manager.go
Labels: size/S, status/LGT1, status/can-merge

#966 Refine the error message of monitor port conflict
  pkg/cluster/spec/validate.go
  pkg/cluster/spec/validate_test.go
Labels: size/M, status/LGT1, status/can-merge

#972 fix(cluster): store prometheus in etcd only once
  pkg/cluster/task/update_topology.go
Labels: category/usability, size/S, status/LGT1, status/can-merge, type/enhancement

#963 Add confirm in upgrade
  components/cluster/command/upgrade.go
  components/dm/command/upgrade.go
  pkg/cluster/manager.go
Labels: size/S, status/LGT1, status/can-merge

#968 Playground: support setting custom timeout for waiting instances up
  components/playground/instance/instance.go
  components/playground/main.go
  components/playground/playground.go
Labels: size/L, status/LGT1, status/can-merge, status/need-doc

#958 Fix/scalein pump monitor notreload
  components/cluster/command/prune.go
  components/dm/task/update_dm_meta.go
  pkg/cluster/manager.go
  pkg/cluster/operation/scale_in.go
  pkg/cluster/task/update_meta.go
  tests/tiup-cluster/script/scale_core.sh
  tests/tiup-dm/test_cmd.sh
Labels: size/XL, status/LGT1, status/can-merge

#964 Support THP in tiup cluster check
  components/cluster/command/check.go
  pkg/cluster/operation/check.go
  pkg/cluster/task/check.go
  tests/tiup-cluster/script/cmd_subtest.sh
Labels: size/M, status/LGT1, status/can-merge

#977 cluster: omit debug log from console output
  components/playground/playground.go
  go.mod
  go.sum
  pkg/cluster/manager.go
  pkg/logger/audit.go
  pkg/logger/log/log.go
Labels: category/usability, size/S, status/LGT1, status/can-merge, type/bug-fix

#967 Support rotate root manifests
  cmd/mirror.go
  pkg/localdata/constant.go
  pkg/repository/mirror.go
  pkg/repository/model/error.go
  pkg/repository/model/model.go
  pkg/repository/store/txn.go
  pkg/repository/v1_repository.go
  server/handler/rotate.go
  server/rotate/rotate_server.go
  server/router.go
Labels: category/security, size/XL, status/LGT1, type/new-feature

#978 utils: use local reader for RNG
  pkg/utils/rand/rand.go
Labels: category/security, size/S, status/LGT1, status/can-merge, type/enhancement

#969 Playground: fix missing config file for tiflash
  components/playground/instance/tiflash.go
Labels: size/XS

#979 Feature/split cluster into small files
  components/cluster/command/clean.go
  components/cluster/command/deploy.go
  components/cluster/command/destroy.go
  components/cluster/command/disable.go
  components/cluster/command/display.go
  components/cluster/command/edit_config.go
  components/cluster/command/enable.go
  components/cluster/command/exec.go
  components/cluster/command/list.go
  components/cluster/command/patch.go
  components/cluster/command/prune.go
  components/cluster/command/reload.go
  components/cluster/command/rename.go
  components/cluster/command/restart.go
  components/cluster/command/root.go
  components/cluster/command/scale_in.go
  components/cluster/command/scale_out.go
  components/cluster/command/start.go
  components/cluster/command/stop.go
  components/cluster/command/upgrade.go
  components/dm/command/deploy.go
  components/dm/command/destroy.go
  components/dm/command/display.go
  components/dm/command/edit_config.go
  components/dm/command/exec.go
  components/dm/command/import.go
  components/dm/command/list.go
  components/dm/command/patch.go
  components/dm/command/reload.go
  components/dm/command/restart.go
  components/dm/command/root.go
  components/dm/command/scale_in.go
  components/dm/command/scale_out.go
  components/dm/command/start.go
  components/dm/command/stop.go
  components/dm/command/upgrade.go
  pkg/cluster/manager.go
  pkg/cluster/manager/basic.go
  pkg/cluster/manager/builder.go
  pkg/cluster/manager/cacert.go
  pkg/cluster/manager/cleanup.go
  pkg/cluster/manager/deploy.go
  pkg/cluster/manager/destroy.go
  pkg/cluster/manager/display.go
  pkg/cluster/manager/edit_config.go
  pkg/cluster/manager/exec.go
  pkg/cluster/manager/list.go
  pkg/cluster/manager/manager.go
  pkg/cluster/manager/manager_test.go
  pkg/cluster/manager/patch.go
  pkg/cluster/manager/reload.go
  pkg/cluster/manager/rename.go
  pkg/cluster/manager/scale_in.go
  pkg/cluster/manager/scale_out.go
  pkg/cluster/manager/upgrade.go
  pkg/cluster/prepare.go
  pkg/cluster/task/action.go
  pkg/repository/mirror.go
Labels: size/XXL, status/LGT1, status/can-merge

#984 Fix tiflash start script
  pkg/cluster/embed/autogen_pkger.go
  templates/scripts/run_tiflash.sh.tpl
Labels: size/XS, status/LGT1

#985 Remove useless errors.AddStack
  components/cluster/command/check.go
  components/cluster/command/display.go
  components/cluster/command/import.go
  components/cluster/command/test.go
  components/dm/ansible/import.go
  components/dm/command/import.go
  components/dm/command/scale_in.go
  components/playground/command.go
  components/playground/grafana.go
  components/playground/main.go
  components/playground/monitor.go
  components/playground/playground.go
  pkg/cluster/ansible/service.go
  pkg/cluster/api/dmapi.go
  pkg/cluster/api/pdapi.go
  pkg/cluster/manager/basic.go
  pkg/cluster/manager/cacert.go
  pkg/cluster/manager/deploy.go
  pkg/cluster/manager/destroy.go
  pkg/cluster/manager/display.go
  pkg/cluster/manager/edit_config.go
  pkg/cluster/manager/exec.go
  pkg/cluster/manager/list.go
  pkg/cluster/manager/manager.go
  pkg/cluster/manager/patch.go
  pkg/cluster/manager/reload.go
  pkg/cluster/manager/rename.go
  pkg/cluster/manager/scale_in.go
  pkg/cluster/manager/scale_out.go
  pkg/cluster/manager/upgrade.go
  pkg/cluster/operation/action.go
  pkg/cluster/operation/destroy.go
  pkg/cluster/operation/scale_in.go
  pkg/cluster/operation/telemetry.go
  pkg/cluster/operation/upgrade.go
  pkg/cluster/spec/grafana.go
  pkg/cluster/spec/prometheus.go
  pkg/cluster/spec/server_config.go
  pkg/cluster/spec/spec_manager.go
  pkg/cluster/spec/tikv.go
  pkg/cluster/spec/util.go
  pkg/cluster/template/config/alertmanager.go
  pkg/environment/env.go
  pkg/logger/audit.go
  pkg/repository/clone_mirror.go
  pkg/repository/v1_repository.go
  pkg/repository/v1manifest/local_manifests.go
  pkg/repository/v1manifest/manifest.go
Labels: size/XL, status/LGT1, status/can-merge

#981 cluster: refine log_dir handling on `clean` (part 1)
  components/cluster/command/clean.go
  components/cluster/command/deploy.go
  components/cluster/command/root.go
  components/cluster/command/scale_out.go
  components/dm/command/root.go
  pkg/cluster/operation/destroy.go
  pkg/set/string_set.go
Labels: category/stability, category/usability, size/M, status/LGT1, status/can-merge, type/bug, type/enhancement

#987 Feature/remove not used file
  cmd/env.go
  components/cluster/command/root.go
  components/dm/command/root.go
  pkg/cluster/flags/debug.go
  pkg/cluster/template/config/dm/prometheus.go
  pkg/localdata/constant.go
Labels: size/L, status/LGT1, status/can-merge

#982 fix(cluster): quote surround wildcard
  .github/workflows/integrate-cluster-cmd.yaml
  .github/workflows/integrate-cluster-scale.yaml
  .github/workflows/integrate-dm.yaml
  .github/workflows/integrate-tiup.yaml
  pkg/cluster/spec/grafana.go
  pkg/cluster/spec/prometheus.go
Labels: size/M, status/LGT1, status/can-merge

#993 cluster/clean: prompt list of paths to be delete before processing (part 2)
  pkg/cluster/manager/cleanup.go
  pkg/cluster/operation/destroy.go
Labels: category/usability, size/L, status/LGT1, status/can-merge, type/bug-fix, type/enhancement

#989 Feature: don't reload prometheus if the scaled comp is itself
  components/cluster/command/patch.go
  components/dm/command/patch.go
  pkg/cluster/manager/builder.go
  pkg/cluster/manager/destroy.go
  pkg/cluster/manager/scale_in.go
  pkg/cluster/task/builder.go
  pkg/cluster/task/update_meta.go
  pkg/cluster/task/update_topology.go
  tests/tiup-cluster/script/scale_tools.sh
  tests/tiup-cluster/topo/.gitignore
  tests/tiup-cluster/topo/full_scale_in_prometheus.yaml
Labels: category/monitoring, category/stability, size/M, status/LGT1, status/can-merge, type/bug-fix

#997 Use more readable mirror init command
  cmd/mirror.go
Labels: category/usability, size/XS, status/LGT1, status/can-merge, type/enhancement

#996 Fix mirror sign command
  cmd/mirror.go
  pkg/repository/v1manifest/repo.go
Labels: category/security, size/L, status/LGT1, status/can-merge, type/enhancement

#994 manager/deploy: do not allow deploying of empty topology
  pkg/cluster/manager/deploy.go
Labels: size/S, status/LGT1, status/can-merge, type/bug-fix, type/enhancement

#998 Bump v1.3.0
  CHANGELOG.md
  pkg/version/version.go
Labels: category/document, size/M, status/LGT1, status/can-merge

#986 Feature/cache pd status
  components/dm/spec/topology_dm.go
  pkg/cluster/api/pdapi.go
  pkg/cluster/manager/display.go
  pkg/cluster/spec/pd.go
  pkg/cluster/spec/spec.go
  pkg/cluster/spec/util.go
  pkg/utils/http_client.go
  tests/tiup-cluster/script/cmd_subtest.sh
Labels: category/usability, size/L, status/LGT1, status/can-merge

#1005 Fix tail newline on thp check
  pkg/cluster/operation/check.go
Labels: size/XS, status/LGT1, status/can-merge, type/bug-fix

#1008 Fix tiup mirror merge usage
  cmd/mirror.go
Labels: size/XS, status/LGT1, status/can-merge

#1011 cluster/spec: workaround if store IDs are not monotonically assigned
  pkg/cluster/spec/tikv.go
Labels: category/stability, size/S, status/LGT1, status/can-merge, type/bug, type/bug-fix

#1010 cluster: refine some outputs
  components/cluster/command/deploy.go
  pkg/cluster/manager/deploy.go
  pkg/cluster/manager/edit_config.go
Labels: category/usability, size/S, status/LGT1, status/can-merge, type/enhancement

#1012 Tiny fix for the problem that the Drainer monitoring configuration of Prometheus is lost due to spelling.
  pkg/cluster/spec/prometheus.go
Labels: first-time-contributor, size/XS, status/LGT1, status/can-merge, status/need-info

#1001 respository: update root before snapshot
  pkg/repository/v1_repository.go
  pkg/repository/v1_repository_test.go
Labels: category/security, size/S, status/LGT1, status/can-merge, type/bug-fix

#1016 cluster: refine the process of getting latest store info from pd
  pkg/cluster/api/error.go
  pkg/cluster/api/error_test.go
  pkg/cluster/api/pdapi.go
  pkg/cluster/spec/tikv.go
Labels: category/stability, size/XL, status/LGT1, status/can-merge, type/bug-fix, type/enhancement

#1013 Remove env that should not be set by user
  cmd/env.go
Labels: size/XS, status/LGT1, status/can-merge

#1003 cluster: update dashboard metadata on reload
  pkg/cluster/manager/reload.go
Labels: category/monitoring, category/usability, size/S, status/LGT1, status/can-merge, type/bug-fix

#1009 cluster, dm: format semver input
  components/cluster/command/deploy.go
  components/cluster/command/upgrade.go
  components/dm/command/deploy.go
  pkg/utils/semver.go
  pkg/utils/semver_test.go
  tests/tiup-cluster/script/cmd_subtest.sh
  tests/tiup-cluster/test_cmd.sh
  tests/tiup-cluster/test_cmd_tls_native_ssh.sh
Labels: category/usability, size/M, status/LGT1, status/can-merge, type/enhancement

#1029 Add warn on clean log
  pkg/cluster/manager/cleanup.go
Labels: size/XS, status/LGT1, status/can-merge

#1020 Don't set pd-server.metric-storage because it's designed to set by user
  pkg/cluster/spec/pd.go
Labels: size/S, status/LGT1, status/can-merge

#1032 cluster: when rolling restart PD, confirm that each peers can serve
  pkg/cluster/spec/pd.go
Labels: category/stability, size/S, status/LGT1, status/can-merge, type/bug-fix

#1036 Bump v1.3.1
  CHANGELOG.md
  pkg/version/version.go
Labels: size/S, status/LGT1, status/can-merge
