Repository pingcap/tiup, pull requests merged in 2020-04, with the labels that each got.

#126 support hide component when tiup list subcommand
  cmd/install.go
  cmd/list.go
  cmd/run.go
  components/package/main.go
  pkg/repository/component.go
  tests/expected/tiup/tiup-install-not-exists.output
Labels: type/bug-fix, type/enhancement

#127 Prevent tikv config from being overwritten and Gracefully stop
  cmd/run.go
  components/playground/instance/tikv.go
  components/playground/main.go
  tests/expected/tiup/tiup-run-test-flag.output
  tests/expected/tiup/tiup-run-test-v1.1.1.output
  tests/expected/tiup/tiup-run-test.output
  tests/expected/tiup/tiup-run-test2.output
  tests/expected/tiup/tiup-run-test3.output
Labels: type/bug-fix

#158 Add a doc directory and outline
  README.md
  doc/README.md
  doc/design/README.md
  doc/dev/README.md
  doc/user/README.md
Labels: type/enhancement
