Repository pingcap/tiup, pull requests merged in 2020-05, with the labels that each got.

#193 Manifest and server organisation design doc
  doc/design/README.md
  doc/design/manifest.md
Labels: type/enhancement

#210 cmd: implement basic entries of repository management
  cmd/repo.go
  cmd/root.go
  pkg/repository/keys.go
  pkg/repository/manifest.go
  pkg/utils/ioutil.go
Labels: status/WIP, type/new-feature

#218 Add basic implementation of component
  cmd/repo.go
  pkg/repository/crypto/keys.go
  pkg/repository/crypto/rsa.go
  pkg/repository/crypto/rsa_test.go
  pkg/repository/v1_repository_test.go
  pkg/repository/v1manifest/manifest.go
  pkg/repository/v1manifest/manifest_test.go
  pkg/repository/v1manifest/repo.go
  pkg/repository/v1manifest/types.go
  tools/migrate/main.go
Labels: type/new-feature

#225 repository: fix tarball downloading
  pkg/repository/file_source.go
  pkg/repository/mirror.go
  pkg/repository/v1manifest/repo.go
  pkg/utils/ioutil.go
Labels: type/bug-fix

#228 tools/migrate: adjust manifest parsing
  pkg/repository/v1manifest/repo.go
  pkg/utils/ioutil.go
  tools/migrate/main.go
Labels: type/enhancement

#247 tools: manual migrate a v0 repo to v1 format
  cmd/repo.go
  go.mod
  go.sum
  pkg/repository/v1manifest/manifest.go
  pkg/repository/v1manifest/repo.go
  pkg/repository/v1manifest/types.go
  tools/migrate/main.go
Labels: type/new-feature

#256 manifest: save private key with 0600 permission
  cmd/repo.go
  pkg/repository/v1manifest/repo.go
Labels: type/enhancement

#261 *: add basic support of nightly versions
  cmd/repo.go
  doc/design/manifest.md
  pkg/repository/v1manifest/types.go
  tools/migrate/main.go
Labels: type/enhancement

#266 manifest: extend the expire time of snapshot and timestamp
  pkg/repository/v1manifest/manifest.go
Labels: type/enhancement

#270 tools/migrate: add function to rehash tarballs and update with existing keys
  pkg/repository/clone_mirror.go
  pkg/repository/hash.go
  pkg/repository/v1manifest/keys.go
  pkg/repository/v1manifest/repo.go
  tools/migrate/main.go
Labels: type/new-feature

#276 tools/migrate: fix version and expire time of updated manfiests
  pkg/repository/v1manifest/manifest.go
  tools/migrate/main.go
Labels: type/bug-fix

#286 *: update migrate tool and repo sub command
  cmd/mirror.go
  pkg/localdata/constant.go
  tools/migrate/main.go
Labels: type/new-feature
