Repository pingcap/tiup, pull requests merged in 2020-10, with the labels that each got.

#828 Adjust error spec
  components/err/error.go
  components/err/testdata/tidb.toml
Labels: category/documentation, status/LGT1, status/PTAL

#830 docs: update user/README.md
  doc/user/README.md
Labels: category/documentation, status/LGT1, status/can-merge

#837 Update dev doc
  doc/dev/README.md
Labels: status/LGT1, status/PTAL, status/can-merge, type/bug-fix

#836 Fix/datarace when concurrent save the same file
  Makefile
  pkg/cluster/task/builder.go
  pkg/file/file.go
  pkg/file/file_test.go
Labels: status/LGT1, status/PTAL, type/new-feature

#848 Skip atuo-start cluster before scale-out action
  pkg/cluster/manager.go
Labels: status/LGT1, status/PTAL, type/enhancement

#844 Fix copy file without mode
  components/cluster/command/import.go
  components/err/error.go
  pkg/cluster/manager.go
  pkg/localdata/profile.go
  pkg/utils/ioutil.go
  pkg/utils/ioutil_test.go
Labels: status/LGT1, status/PTAL, type/bug-fix

#824 Fix/pd scale in topo not updated
  components/cluster/command/scale_in.go
  pkg/cluster/operation/scale_in.go
  tests/tiup-cluster/run.sh
  tests/tiup-cluster/script/scale_core.sh
Labels: status/LGT1, type/bug-fix

#845 Fix the broken contribution guide link in README.md
  README.md
Labels: status/LGT2, status/can-merge

#843 Introduce a more graceful way to check labels
  pkg/cluster/api/pdapi.go
  pkg/cluster/manager.go
  pkg/cluster/spec/spec.go
  pkg/cluster/spec/validate.go
  pkg/cluster/spec/validate_test.go
Labels: status/LGT1, status/PTAL, type/bug-fix

#851 Implement the errors metadata file generator
  Makefile
  components/errdoc/errdoc-gen/README.md
  components/errdoc/errdoc-gen/main.go
  components/errdoc/main.go
  components/errdoc/spec/spec.go
  components/errdoc/testdata/tidb.toml
Labels: status/LGT1, type/new-feature

#856 Update the output of errdoc component
  components/errdoc/main.go
  components/errdoc/spec/spec.go
Labels: status/LGT1, status/can-merge, type/enhancement

#858 More safe way to cleanup tombstone nodes
  components/cluster/command/display.go
  components/cluster/command/prune.go
  components/cluster/command/root.go
  components/dm/command/display.go
  components/dm/command/prune.go
  components/dm/command/root.go
  go.sum
  pkg/cluster/manager.go
  pkg/cluster/operation/action.go
  pkg/cluster/operation/scale_in.go
  tests/tiup-cluster/script/util.sh
  tests/tiup-dm/script/util.sh
Labels: status/LGT2, status/PTAL, type/enhancement

#861 Bump v1.2.1
  CHANGELOG.md
  pkg/version/version.go
Labels: status/LGT1

#866 Fix search error documentation via error code
  components/errdoc/main.go
  components/errdoc/spec/spec.go
Labels: status/LGT1, type/bug-fix

#867 Allow merge the existing description/workaround in errors.toml
  components/errdoc/errdoc-gen/main.go
Labels: status/LGT1, type/enhancement

#869 Fix labels warning
  pkg/cluster/api/pdapi.go
  pkg/cluster/manager.go
  pkg/cluster/spec/spec.go
  pkg/cluster/spec/validate.go
  pkg/cluster/spec/validate_test.go
Labels: status/LGT1

#872 Bump v1.2.3
  CHANGELOG.md
  pkg/version/version.go
Labels: status/LGT1
