Repository pingcap/tiup, pull requests merged in 2020-06, with the labels that each got.

#387 *: update manifest version checking & build miscs
  Makefile
  doc/user/cluster.md
  pkg/repository/v1_repository.go
  pkg/version/version.go
Labels: type/bug-fix, type/enhancement

#388 cluster/destroy: fix wait for down & ignore the timeout error
  pkg/cluster/operation/destroy.go
Labels: type/bug-fix

#401 *: fix manifest update
  cmd/list.go
  pkg/repository/v1_repository.go
  pkg/repository/v1_repository_test.go
  pkg/repository/v1manifest/local_manifests.go
  pkg/repository/v1manifest/manifest.go
  server/store/qcloud.go
Labels: type/bug-fix

#412 workflow: add reprotest ci
  .github/workflows/reprotest.yaml
Labels: type/testing

#410 cluster/import: fix copying directory
  go.mod
  go.sum
  pkg/repository/v1_repository_test.go
  pkg/utils/ioutil.go
Labels: type/bug-fix

#392 Skip tiup component when tiup update/install
  pkg/environment/env.go
Labels: type/enhancement

#415 server: renew manifests on update
  cmd/mirror.go
  pkg/repository/remote/upload.go
  server/handler/component.go
  server/handler/error.go
  server/handler/tarball.go
  server/model/model.go
Labels: type/bug-fix

#409 Support send commands to a running playground
  components/playground/command.go
  components/playground/env.go
  components/playground/instance/instance.go
  components/playground/instance/pd.go
  components/playground/instance/tidb.go
  components/playground/instance/tiflash.go
  components/playground/instance/tikv.go
  components/playground/instance/tikv_config.go
  components/playground/main.go
  components/playground/playground.go
Labels: type/new-feature

#429 rename tiup-dm to tiup-dms
  Makefile
  components/dms/command/audit.go
  components/dms/command/check.go
  components/dms/command/deploy.go
  components/dms/command/destroy.go
  components/dms/command/display.go
  components/dms/command/edit_config.go
  components/dms/command/exec.go
  components/dms/command/list.go
  components/dms/command/patch.go
  components/dms/command/reload.go
  components/dms/command/restart.go
  components/dms/command/root.go
  components/dms/command/scale_in.go
  components/dms/command/scale_out.go
  components/dms/command/start.go
  components/dms/command/stop.go
  components/dms/command/telemetry.go
  components/dms/command/test.go
  components/dms/command/upgrade.go
  components/dms/main.go
  components/dms/main_test.go
  docker/up.sh
  tests/tiup-dms/test_dm_cmd.sh
Labels: type/enhancement

#430 Support scale-in for non stateful components
  components/playground/command.go
  components/playground/playground.go
Labels: type/new-feature

#431 Use file service discover for prometheus in playground
  components/playground/command.go
  components/playground/env.go
  components/playground/instance/instance.go
  components/playground/instance/tiflash.go
  components/playground/main.go
  components/playground/monitor.go
  components/playground/playground.go
Labels: type/new-feature

#436 add integration tests for tiup-playground
  .github/workflows/ci.yaml
  .github/workflows/integrate.yaml
  Makefile
  components/playground/instance/tiflash.go
  components/playground/instance/tiflash_proxy_config.go
  components/playground/main.go
  components/playground/main_test.go
  components/playground/playground.go
  tests/Makefile
  tests/cases.json
  tests/cases_cov.json
  tests/run.sh
  tests/tiup-cluster/run.sh
  tests/tiup-cluster/test_upgrade.sh
  tests/tiup-dms/run.sh
  tests/tiup-dms/test_dms_cmd.sh
  tests/tiup-playground/test_playground.sh
  tests/tiup/bin/root.json
  tests/tiup/test_tiup.sh
  tests/tiup_home/bin/root.json
  tests/tiup_mirrors/prepare.sh
Labels: type/testing

#426 cluster/api: refine pdapi
  pkg/cluster/api/dmapi.go
  pkg/cluster/api/pdapi.go
Labels: type/bug-fix, type/enhancement

#445 Report a warning when updating non-exist components
  pkg/repository/v1_repository.go
  pkg/repository/v1_repository_test.go
Labels: type/bug-fix

#446 utils: fix directory removing
  pkg/utils/ioutil.go
  tests/tiup/.gitignore
Labels: type/bug-fix

#457 Remove args in Command
  components/cluster/command/deploy.go
  components/cluster/command/destroy.go
  components/cluster/command/display.go
  components/cluster/command/edit_config.go
  components/cluster/command/exec.go
  components/cluster/command/patch.go
  components/cluster/command/reload.go
  components/cluster/command/restart.go
  components/cluster/command/root.go
  components/cluster/command/scale_in.go
  components/cluster/command/scale_out.go
  components/cluster/command/start.go
  components/cluster/command/stop.go
  components/cluster/command/upgrade.go
Labels: type/enhancement

#477 fix help bug and add version flag for tiup
  cmd/root.go
Labels: type/bug-fix, type/enhancement

#475 Fix the dead link in documentation
  doc/user/cluster.md
Labels: type/enhancement

#447 display: update state displaying for offline tikv node
  components/cluster/command/display.go
  pkg/cluster/meta/topology.go
Labels: type/enhancement

#450 executor/ssh: force using C locale for commands
  pkg/cluster/executor/ssh.go
Labels: type/bug-fix

#487 Support output verbose log for debugging
  pkg/environment/env.go
  pkg/repository/mirror.go
  pkg/repository/v1_repository.go
  pkg/verbose/verbose.go
Labels: status/can-merge, type/enhancement

#465 Remove history nightly version in manifests
  pkg/repository/remote/upload.go
Labels: status/can-merge

#448 cluster/check: update version of insight collector
  go.mod
  go.sum
  pkg/cluster/meta/bindversion.go
Labels: type/enhancement

#481 Handle scale in of kv/pd/flash in playground
  components/playground/instance/pd.go
  components/playground/instance/tiflash.go
  components/playground/instance/tikv.go
  components/playground/playground.go
Labels: status/can-merge, type/new-feature

#479 Support grafana and the build in dashboard when enable monitor
  components/playground/grafana.go
  components/playground/grafana_test.go
  components/playground/instance/instance.go
  components/playground/instance/pd.go
  components/playground/instance/tidb.go
  components/playground/instance/tiflash.go
  components/playground/instance/tikv.go
  components/playground/main.go
  components/playground/monitor.go
  components/playground/playground.go
Labels: type/enhancement

#489 move init mirror to preRun for `tiup mirror clone`
  cmd/mirror.go
Labels: status/can-merge

#496 Support pump&drainer in playground
  components/playground/command.go
  components/playground/instance/drainer.go
  components/playground/instance/instance.go
  components/playground/instance/pd.go
  components/playground/instance/pump.go
  components/playground/instance/tidb.go
  components/playground/instance/tiflash.go
  components/playground/instance/tikv.go
  components/playground/main.go
  components/playground/playground.go
Labels: status/can-merge, type/new-feature

#482 Fix the bug that generate wrong snapshot meta when tiup mirror clone
  pkg/repository/clone_mirror.go
Labels: status/can-merge, type/bug-fix

#505 fix tiup server transaction bug
  server/store/qcloud.go
Labels: type/bug-fix

#497 Implement --yank --standalone and --hide in tiup mirror publish|modify
  cmd/list.go
  cmd/mirror.go
  go.mod
  pkg/repository/remote/common.go
  pkg/repository/remote/modify.go
  pkg/repository/remote/upload.go
  server/handler/component.go
  server/main.go
  server/model/error.go
  server/model/model.go
  server/model/types.go
  server/server.go
  server/static.go
Labels: status/can-merge, type/new-feature

#510 executor/ssh: fix PATH for non-shell executors
  pkg/cluster/executor/ssh.go
Labels: type/bug-fix

#501 Fix timeout when target directory exists and there is lots of content
  pkg/cluster/clusterutil/clusterutil.go
  pkg/cluster/clusterutil/clusterutil_test.go
  pkg/cluster/task/mkdir.go
Labels: type/bug-fix

#502 cluster: optimize dir conflicts check & the destroying process
  components/cluster/command/check.go
  components/cluster/command/deploy.go
  components/cluster/command/destroy.go
  components/cluster/command/display.go
  components/cluster/command/edit_config.go
  components/cluster/command/exec.go
  components/cluster/command/list.go
  components/cluster/command/patch.go
  components/cluster/command/reload.go
  components/cluster/command/restart.go
  components/cluster/command/root.go
  components/cluster/command/scale_in.go
  components/cluster/command/scale_out.go
  components/cluster/command/start.go
  components/cluster/command/stop.go
  components/cluster/command/test.go
  components/cluster/command/upgrade.go
  components/dms/command/destroy.go
  components/dms/command/display.go
  components/dms/command/edit_config.go
  components/dms/command/exec.go
  components/dms/command/list.go
  components/dms/command/patch.go
  components/dms/command/reload.go
  components/dms/command/restart.go
  components/dms/command/scale_in.go
  components/dms/command/start.go
  components/dms/command/stop.go
  components/dms/command/test.go
  components/dms/command/upgrade.go
  pkg/cluster/ansible/import.go
  pkg/cluster/meta/cluster.go
  pkg/cluster/meta/logic.go
  pkg/cluster/meta/meta.go
  pkg/cluster/meta/meta_test.go
  pkg/cluster/meta/server_config_test.go
  pkg/cluster/meta/topology.go
  pkg/cluster/meta/topology_dm.go
  pkg/cluster/meta/topology_dm_test.go
  pkg/cluster/meta/topology_test.go
  pkg/cluster/operation/action.go
  pkg/cluster/operation/destroy.go
  pkg/cluster/operation/scale_in.go
  pkg/cluster/task/update_meta.go
  pkg/cluster/template/scripts/tidb.go
  pkg/cluster/template/scripts/tikv.go
  pkg/set/string_set.go
Labels: type/bug-fix, type/enhancement

#490 Rewrite dms specification
  components/dms/command/audit.go
  components/dms/command/check.go
  components/dms/command/deploy.go
  components/dms/command/destroy.go
  components/dms/command/display.go
  components/dms/command/edit_config.go
  components/dms/command/exec.go
  components/dms/command/list.go
  components/dms/command/patch.go
  components/dms/command/reload.go
  components/dms/command/restart.go
  components/dms/command/root.go
  components/dms/command/scale_in.go
  components/dms/command/scale_out.go
  components/dms/command/start.go
  components/dms/command/stop.go
  components/dms/command/telemetry.go
  components/dms/command/test.go
  components/dms/command/upgrade.go
  go.mod
  pkg/cliutil/prepare/prepare.go
  pkg/cluster/meta/logic.go
  pkg/cluster/meta/topology.go
  pkg/cluster/meta/topology_dm.go
  pkg/cluster/meta/topology_dm_test.go
  pkg/cluster/operation/destroy.go
  pkg/cluster/operation/scale_in.go
  pkg/cluster/operation/upgrade.go
  pkg/cluster/task/builder.go
  pkg/cluster/task/update_dm_meta.go
  pkg/dms/meta/cluster.go
  pkg/dms/meta/logic.go
  pkg/dms/meta/paths.go
  pkg/dms/meta/server_config.go
  pkg/dms/meta/topology.go
  pkg/dms/meta/topology_test.go
Labels: type/enhancement

#504 Retain data of instances/nodes when destroying cluster
  components/cluster/command/destroy.go
  pkg/cluster/operation/action.go
  pkg/cluster/operation/destroy.go
  pkg/cluster/operation/operation.go
  pkg/cluster/operation/scale_in.go
Labels: type/new-feature

#503 Support tiup mirror set command
  cmd/mirror.go
  install.sh
  pkg/cluster/template/install/local_install.sh.go
  pkg/environment/env.go
  pkg/localdata/config.go
  pkg/localdata/profile.go
  pkg/localdata/profile_test.go
  server/handler/component.go
Labels: type/new-feature

#515 Redirect std output to log file
  components/playground/command.go
  components/playground/instance/drainer.go
  components/playground/instance/instance.go
  components/playground/instance/pd.go
  components/playground/instance/process.go
  components/playground/instance/pump.go
  components/playground/instance/tidb.go
  components/playground/instance/tiflash.go
  components/playground/instance/tikv.go
  components/playground/main.go
  components/playground/playground.go
  components/playground/utils/utils.go
Labels: type/new-feature

#526 Support platform "any/any"
  cmd/mirror.go
  pkg/repository/v1_repository.go
  pkg/repository/v1manifest/manifest.go
  pkg/repository/v1manifest/manifest_test.go
Labels: type/enhancement

#530 Fix cdc cli
  components/ctl/main.go
Labels: type/bug-fix

#527 Enable playground TiFlash component on Mac
  components/playground/main.go
  components/playground/playground.go
  pkg/cluster/operation/operation.go
  pkg/utils/mock/mock.go
Labels: type/enhancement

#535 Fix custom config of grafana
  components/playground/grafana.go
  components/playground/monitor.go
Labels: status/can-merge

#547 Rename the component DMS to DM
  Makefile
  components/dm/command/audit.go
  components/dm/command/check.go
  components/dm/command/deploy.go
  components/dm/command/destroy.go
  components/dm/command/display.go
  components/dm/command/edit_config.go
  components/dm/command/exec.go
  components/dm/command/list.go
  components/dm/command/patch.go
  components/dm/command/reload.go
  components/dm/command/restart.go
  components/dm/command/root.go
  components/dm/command/scale_in.go
  components/dm/command/scale_out.go
  components/dm/command/start.go
  components/dm/command/stop.go
  components/dm/command/telemetry.go
  components/dm/command/test.go
  components/dm/command/upgrade.go
  components/dm/main.go
  components/dm/main_test.go
  tests/Makefile
  tests/tiup-dms/run.sh
Labels: type/enhancement

#548 Disable space holder of tikv in playground
  components/playground/instance/tikv_config.go
Labels: type/enhancement

#550 cluster: show message for impossible fix
  components/cluster/command/check.go
Labels: status/can-merge, type/enhancement

#546 always try to update state when force scale in instance
  pkg/cluster/api/binlog.go
  pkg/cluster/operation/action.go
  pkg/cluster/operation/scale_in.go
Labels: type/enhancement

#543 playground: fix panic if failed to start tiflash
  components/playground/instance/instance.go
  components/playground/playground.go
Labels: type/bug-fix
