Repository pingcap/tiup, pull requests merged in 2020-11, with the labels that each got.

#873 Correct 'Contribution Guide' URL
  .github/pull_request_template.md
  CONTRIBUTING.md
Labels: first-time-contributor, status/LGT1, status/can-merge

#879 cluster/audit: audit log in seconds maybe leads to file overwriten
  pkg/cluster/audit/audit.go
  pkg/cluster/audit/audit_test.go
  tests/tiup-dm/run.sh
Labels: status/LGT1

#871 Fix dataDir not deleted if containing comma
  components/cluster/command/prune.go
  pkg/cluster/operation/action.go
  pkg/cluster/spec/validate.go
  pkg/cluster/spec/validate_test.go
  tests/tiup-cluster/script/scale_tools.sh
  tests/tiup-cluster/topo/full.yaml.tpl
  tests/tiup-cluster/topo/full_scale_in_tiflash.yaml.tpl
Labels: status/LGT1, status/can-merge

#882 fix(cluster/audit): compatible with old second based ts
  pkg/cluster/audit/audit.go
  pkg/cluster/audit/audit_test.go
Labels: status/LGT1

#857 Fix: destroy monitor if no more components in host
  components/dm/command/scale_in.go
  pkg/cluster/operation/action.go
  pkg/cluster/operation/destroy.go
  pkg/cluster/operation/scale_in.go
  tests/Makefile
  tests/tiup-cluster/script/cmd_subtest.sh
  tests/tiup-cluster/script/pull_log.sh
  tests/tiup-cluster/script/scale_core.sh
  tests/tiup-cluster/topo/.gitignore
  tests/tiup-cluster/topo/full.yaml.tpl
  tests/tiup-cluster/topo/full_tls.yaml.tpl
Labels: status/LGT1

#864 Update topology.example.yaml
  examples/topology.example.yaml
Labels: first-time-contributor, status/LGT1, status/can-merge

#878 clone: retry on download while network error
  pkg/repository/mirror.go
Labels: status/LGT1, status/PTAL, status/can-merge

#884 Fix tiup dm patch can't detect correct version
  pkg/cluster/manager.go
Labels: status/LGT1, status/PTAL, status/can-merge

#887 update pingcap/go-tpc version
  go.mod
  go.sum
Labels: status/LGT1

#901 Fix ti-spark scale-out
  cmd/mirror.go
  pkg/cluster/manager.go
  pkg/cluster/spec/bindversion.go
  pkg/repository/v1_repository.go
Labels: status/LGT1

#905 cluster: enable service after scale out
  components/cluster/command/scale_out.go
  tests/tiup-cluster/script/scale_core.sh
Labels: status/LGT1

#890 dry: merge dm's {alertmanager,grafana,prometheus} into cluster
  components/dm/ansible/import.go
  components/dm/ansible/import_test.go
  components/dm/command/scale_in.go
  components/dm/spec/alertmanager.go
  components/dm/spec/bindversion.go
  components/dm/spec/cluster.go
  components/dm/spec/grafana.go
  components/dm/spec/grafana_test.go
  components/dm/spec/logic.go
  components/dm/spec/prometheus.go
  components/dm/spec/testdata/dashboards/tidb.json
  components/dm/spec/topology_dm.go
  components/dm/spec/topology_dm_test.go
  components/dm/task/update_dm_meta.go
  pkg/cluster/ansible/import.go
  pkg/cluster/ansible/import_test.go
  pkg/cluster/ansible/inventory.go
  pkg/cluster/ansible/service.go
  pkg/cluster/embed/autogen_pkger.go
  pkg/cluster/manager.go
  pkg/cluster/operation/destroy.go
  pkg/cluster/operation/scale_in.go
  pkg/cluster/spec/alertmanager.go
  pkg/cluster/spec/bindversion.go
  pkg/cluster/spec/cdc.go
  pkg/cluster/spec/drainer.go
  pkg/cluster/spec/grafana.go
  pkg/cluster/spec/grafana_test.go
  pkg/cluster/spec/instance.go
  pkg/cluster/spec/pd.go
  pkg/cluster/spec/prometheus.go
  pkg/cluster/spec/pump.go
  pkg/cluster/spec/spec.go
  pkg/cluster/spec/spec_manager_test.go
  pkg/cluster/spec/tidb.go
  pkg/cluster/spec/tiflash.go
  pkg/cluster/spec/tikv.go
  pkg/cluster/spec/tispark.go
  pkg/cluster/spec/validate.go
  pkg/cluster/task/update_meta.go
  pkg/cluster/task/update_topology.go
  pkg/cluster/template/config/prometheus.go
  templates/config/dm/prometheus.yml.tpl
  templates/config/prometheus.yml.tpl
  templates/scripts/dm/run_grafana.sh.tpl
  templates/scripts/dm/run_prometheus.sh.tpl
  tests/tiup-dm/script/util.sh
  tests/tiup-dm/test_import.sh
Labels: status/LGT1

#902 Fix tiflash not start with newest nightly PD
  components/playground/instance/tiflash.go
Labels: status/LGT1, status/PTAL

#907 Modify TiFlash's query memory limit from 10GB to 0(unlimited).
  components/playground/instance/tiflash_config.go
  pkg/cluster/spec/tiflash.go
Labels: status/LGT2

#766 Import configuration when migrating a cluster from Ansible
  components/cluster/command/import.go
  go.mod
  go.sum
  pkg/cluster/ansible/import.go
  pkg/cluster/ansible/import_test.go
  pkg/cluster/spec/server_config.go
  pkg/cluster/spec/server_config_test.go
  pkg/cluster/spec/spec_test.go
  pkg/cluster/spec/tikv.go
  pkg/set/any_set.go
  pkg/set/any_set_test.go
  pkg/set/string_set_test.go
Labels: status/LGT1, type/new-feature

#904 feat(node_exporter): add --collector.buddyinfo
  pkg/cluster/embed/autogen_pkger.go
  templates/scripts/run_node_exporter.sh.tpl
Labels: status/LGT1

#908 Feature/add log dir
  cmd/env.go
  components/cluster/command/root.go
  components/dm/command/root.go
  pkg/localdata/constant.go
  pkg/logger/debug.go
  tests/tiup-cluster/script/scale_tools.sh
  tests/tiup-dm/test_cmd.sh
Labels: status/LGT1

#903 Fix imported pump & drainer start script
  components/playground/playground.go
  pkg/cluster/api/binlog.go
  pkg/cluster/embed/autogen_pkger.go
  pkg/cluster/manager.go
  pkg/cluster/operation/scale_in.go
  pkg/cluster/spec/drainer.go
  pkg/cluster/spec/pump.go
  templates/scripts/run_drainer.sh.tpl
  templates/scripts/run_pump.sh.tpl
Labels: status/LGT1, status/PTAL

#920 cluster: ignore no tispark master error when listing clusters
  pkg/cluster/manager.go
Labels: cherrypick/1.2, status/LGT1, type/bug-fix

#918 fix(install): install script export path
  install.sh
Labels: first-time-contributor, status/LGT1

#921 Bump v1.2.4
  CHANGELOG.md
  pkg/version/version.go
Labels: status/LGT1

#924 cluster: fix tispark master scaling handling
  pkg/cluster/manager.go
  pkg/cluster/operation/scale_in.go
  pkg/cluster/spec/spec_manager.go
Labels: cherrypick/1.2, status/LGT1, type/bug-fix

#860 Refactor mirror command
  cmd/env.go
  cmd/mirror.go
  go.mod
  go.sum
  pkg/cluster/audit/audit.go
  pkg/file/file.go
  pkg/localdata/constant.go
  pkg/repository/merge_mirror.go
  pkg/repository/merge_mirror_test.go
  pkg/repository/mirror.go
  pkg/repository/model/error.go
  pkg/repository/model/model.go
  pkg/repository/model/publish.go
  pkg/repository/remote/common.go
  pkg/repository/remote/modify.go
  pkg/repository/remote/upload.go
  pkg/repository/store/local.go
  pkg/repository/store/store.go
  pkg/repository/store/store_test.go
  pkg/repository/store/sync.go
  pkg/repository/store/txn.go
  pkg/repository/v1manifest/key_store.go
  pkg/repository/v1manifest/keys.go
  pkg/repository/v1manifest/local_manifests.go
  pkg/repository/v1manifest/manifest.go
  pkg/repository/v1manifest/repo.go
  pkg/repository/v1manifest/types.go
  pkg/utils/ioutil.go
  server/handler/component.go
  server/handler/error.go
  server/handler/tarball.go
  server/main.go
  server/model/model.go
  server/model/types.go
  server/router.go
  server/server.go
  server/session/session.go
  server/store/qcloud.go
  server/store/qcloud_test.go
  server/store/store_test.go
  tests/tiup/test_tiup.sh
  tools/migrate/main.go
Labels: need-update-documentation, status/LGT1, status/can-merge, type/new-feature

#926 playground: allow a pure TiKV cluster
  components/playground/playground.go
Labels: good-first-issue, status/LGT1, status/can-merge, type/enhancement

#917 Fix: github workflow upload logs dir error
  .github/workflows/integrate-cluster-cmd.yaml
  .github/workflows/integrate-cluster-scale.yaml
  .github/workflows/integrate-dm.yaml
  .github/workflows/integrate-playground.yaml
  tests/tiup-cluster/script/pull_log.sh
Labels: status/LGT1, status/can-merge

#923 Feature/print log dir if {start,stop,restart} failed
  pkg/cluster/operation/action.go
Labels: status/LGT1, status/can-merge

#925 Fix drainer error node id message
  pkg/cluster/api/binlog.go
Labels: status/LGT1, status/PTAL, status/can-merge

#916 Fix concurrent saving file
  pkg/cluster/audit/audit.go
  pkg/cluster/task/ssh_keygen.go
  pkg/file/file.go
  pkg/file/file_test.go
  pkg/repository/mirror.go
  pkg/utils/rand/rand.go
Labels: status/LGT1, status/PTAL, status/can-merge

#922 Fix: duplicated pd_servers.name in the topology before truly deploy
  pkg/cluster/spec/validate.go
  pkg/cluster/spec/validate_test.go
Labels: first-time-contributor, good-first-issue, status/LGT1, status/can-merge, type/enhancement

#929 repository: move v0manifest.Version to dedicate package
  cmd/list.go
  cmd/mirror.go
  components/playground/grafana.go
  components/playground/instance/drainer.go
  components/playground/instance/instance.go
  components/playground/instance/pd.go
  components/playground/instance/process.go
  components/playground/instance/pump.go
  components/playground/instance/ticdc.go
  components/playground/instance/tidb.go
  components/playground/instance/tiflash.go
  components/playground/instance/tiflash_proxy_config.go
  components/playground/instance/tikv.go
  components/playground/monitor.go
  components/playground/playground.go
  pkg/cluster/manager.go
  pkg/environment/env.go
  pkg/exec/run.go
  pkg/localdata/constant.go
  pkg/localdata/profile.go
  pkg/meta/err_test.go
  pkg/repository/clone_mirror.go
  pkg/repository/merge_mirror.go
  pkg/repository/mirror.go
  pkg/repository/repository.go
  pkg/repository/v0manifest/component.go
  pkg/repository/v0manifest/version.go
  pkg/repository/v0manifest/version_test.go
  pkg/repository/v1_repository.go
  pkg/repository/version/version.go
  pkg/repository/version/version_test.go
  server/package/package.go
  tools/migrate/main.go
Labels: status/LGT1, type/enhancement

#934 Fix/make goimports typo error
  Makefile
  cmd/mirror.go
  components/bench/ycsb.go
  components/cluster/command/deploy.go
  components/playground/instance/process.go
  pkg/cluster/module/shell.go
  pkg/cluster/module/systemd.go
  pkg/cluster/operation/operation.go
  pkg/cluster/spec/server_config.go
  pkg/cluster/spec/validate_test.go
  pkg/cluster/template/install/local_install.sh.go
  pkg/meta/err.go
  pkg/repository/v1manifest/repo.go
  pkg/utils/diff.go
  pkg/utils/diff_test.go
  server/handler/error.go
  server/handler/handler.go
Labels: cherrypick/1.2, status/LGT1, type/enhancement

#931 Support deploy TiFlash on multi-disks with "storage" configurations since v4.0.9
  examples/topology.example.yaml
  pkg/cluster/spec/parse_topology_test.go
  pkg/cluster/spec/spec.go
  pkg/cluster/spec/spec_test.go
  pkg/cluster/spec/tiflash.go
  pkg/cluster/spec/validate.go
  pkg/cluster/spec/validate_test.go
  pkg/utils/diff.go
  pkg/utils/diff_test.go
Labels: status/LGT1

#938 Fix bug for only one directory in TiFlash storage.* configuration
  pkg/cluster/spec/parse_topology_test.go
  pkg/cluster/spec/tiflash.go
Labels: status/LGT1

#935 Fix/GitHub action failure
  .github/workflows/integrate-cluster-cmd.yaml
  .github/workflows/integrate-cluster-scale.yaml
  .github/workflows/integrate-dm.yaml
  .github/workflows/integrate-playground.yaml
Labels: status/LGT1, status/can-merge

#945 Bump v1.2.5
  CHANGELOG.md
  pkg/version/version.go
Labels: status/LGT1

#930 Fix dm monitor config
  components/dm/spec/logic.go
  components/dm/spec/topology_dm.go
  pkg/cluster/operation/download.go
  pkg/cluster/operation/telemetry.go
  pkg/cluster/spec/alertmanager.go
  pkg/cluster/spec/grafana.go
  pkg/cluster/spec/instance.go
  pkg/cluster/spec/profile.go
  pkg/cluster/spec/prometheus.go
  pkg/cluster/spec/spec.go
  pkg/cluster/spec/spec_manager_test.go
  pkg/cluster/spec/util.go
  pkg/cluster/task/copy_component.go
  tests/tiup-dm/test_cmd.sh
  tests/tiup-dm/topo/full_scale_in_grafana.yaml.tpl
Labels: status/LGT1, status/can-merge

#910 Feature/remove public key after destroyed
  components/dm/command/scale_in.go
  pkg/cluster/executor/executor.go
  pkg/cluster/operation/action.go
  pkg/cluster/operation/destroy.go
  pkg/cluster/operation/operation.go
  pkg/cluster/operation/scale_in.go
  pkg/cluster/task/env_init.go
  pkg/cluster/task/task.go
  tests/tiup-cluster/script/cmd_subtest.sh
  tests/tiup-cluster/script/scale_core.sh
  tests/tiup-dm/test_cmd.sh
Labels: size/L, status/LGT1, status/can-merge

#937 fix importing grafana admin user / password from ansible
  components/dm/ansible/import.go
  components/dm/ansible/import_test.go
  components/dm/ansible/testdata/ansible/inventory.ini
  pkg/cluster/ansible/inventory.go
  pkg/cluster/ansible/test-data/inventory.ini
  pkg/cluster/ansible/test-data/meta.yaml
  pkg/cluster/embed/autogen_pkger.go
  pkg/cluster/spec/grafana.go
  pkg/cluster/template/config/grafana.go
  templates/config/grafana.ini.tpl
Labels: size/M, status/LGT1, status/can-merge, type/bug-fix
