Repository pingcap/tiup, pull requests merged in 2020-08, with the labels that each got.

#648 Add changelog and bump 1.0.9
  CHANGELOG.md
  pkg/version/version.go
Labels: status/LGT1, status/PTAL

#623 Refactor helper pacakges and fix spec validation
  components/cluster/command/check.go
  components/dm/command/display.go
  components/dm/command/root.go
  components/playground/playground.go
  components/playground/utils/http.go
  components/playground/utils/utils.go
  pkg/cliutil/prepare/prepare.go
  pkg/cluster/api/dmapi.go
  pkg/cluster/api/pdapi.go
  pkg/cluster/clusterutil/retry.go
  pkg/cluster/manager.go
  pkg/cluster/module/wait_for.go
  pkg/cluster/operation/destroy.go
  pkg/cluster/operation/scale_in.go
  pkg/cluster/prepare.go
  pkg/cluster/spec/pd.go
  pkg/cluster/spec/server_config.go
  pkg/cluster/spec/spec.go
  pkg/cluster/spec/spec_manager.go
  pkg/cluster/spec/spec_manager_test.go
  pkg/cluster/spec/spec_test.go
  pkg/cluster/spec/tikv.go
  pkg/cluster/spec/validate.go
  pkg/cluster/spec/validate_test.go
  pkg/utils/retry.go
  pkg/utils/utils.go
  server/handler/component.go
Labels: category/testing, category/usability, status/LGT1, type/bug-fix, type/enhancement

#650 Fix test expired
  pkg/repository/testdata/polluted/manifests/snapshot.json
  pkg/repository/v1_repository_test.go
  pkg/repository/v1manifest/testdata/polluted/manifests/snapshot.json
Labels: status/LGT2

#655 Update source file format
  tests/tiup-dm/script/task/run.sh
  tests/tiup-dm/script/task/source1.toml
  tests/tiup-dm/script/task/source1.yml
  tests/tiup-dm/script/task/source2.toml
  tests/tiup-dm/script/task/source2.yml
Labels: status/LGT1

#652 cluster/import: read enable_binlog from inventory
  pkg/cluster/ansible/import.go
Labels: status/LGT2, type/bug-fix

#662 Skip evict store when only 1 tikv
  pkg/cluster/spec/tikv.go
Labels: status/LGT1, status/can-merge

#659 Fix tiup update --self with offline package
  .github/workflows/install.yaml
  pkg/environment/env.go
Labels: status/LGT1, status/can-merge

#644 Add clean sub command
  .github/workflows/integrate.yaml
  components/cluster/command/clean.go
  components/cluster/command/destroy.go
  components/cluster/command/root.go
  components/cluster/command/test.go
  pkg/cluster/manager.go
  pkg/cluster/operation/destroy.go
  pkg/cluster/operation/operation.go
  tests/tiup-cluster/script/cmd_subtest.sh
  tests/tiup-dm/test_cmd.sh
Labels: status/LGT1, status/PTAL

#668 Update examples/topology.example.yaml
  examples/topology.example.yaml
Labels: status/LGT1, status/PTAL

#669 Add release guide
  .github/pull_request_template.md
  doc/dev/release-note-guide.md
Labels: status/LGT1

#670 tui: fix reverse confirmation prompt
  pkg/cliutil/tui.go
  pkg/cluster/manager.go
Labels: category/usability, status/LGT1, status/can-merge, type/bug-fix

#674 don't wait the listen port disappear when destroy and clean
  pkg/cluster/operation/destroy.go
  pkg/cluster/spec/instance.go
Labels: status/LGT1, type/enhancement

#679 update tiup dm example
  examples/dm/minimal.yaml
  examples/dm/topology.example.yaml
  examples/topology.dm.example.yaml
Labels: status/LGT1, status/PTAL

#671 Support rename cluster
  components/cluster/command/rename.go
  components/cluster/command/root.go
  pkg/cluster/manager.go
  tests/tiup-cluster/script/cmd_subtest.sh
Labels: status/LGT1, status/PTAL, status/can-merge, type/new-feature

#682 Do not change the run component's wd
  pkg/exec/run.go
Labels: status/LGT1

#683 More clear error msg when fail copy file
  docker/control/bashrc
  pkg/cluster/task/install_package.go
Labels: status/LGT1

#676 Add advertise-status-addr for tiflash proxy
  components/playground/instance/tiflash.go
  components/playground/instance/tiflash_proxy_config.go
  components/playground/playground.go
  pkg/cluster/spec/tiflash.go
Labels: status/LGT1, status/can-merge, type/enhancement

#678 Improve env init on deploying and scale-out cluster
  components/cluster/command/deploy.go
  components/cluster/command/scale_out.go
  examples/topology.example.yaml
  pkg/cluster/manager.go
  pkg/cluster/module/user.go
  pkg/cluster/spec/spec.go
  pkg/cluster/task/builder.go
  pkg/cluster/task/env_init.go
  pkg/cluster/task/mkdir.go
  tests/tiup-cluster/script/cmd_subtest.sh
  tests/tiup-cluster/topo/full.yaml
Labels: need-update-documentation, status/LGT1, status/PTAL, status/can-merge

#672 Add import command for dm
  components/dm/ansible/import.go
  components/dm/ansible/import_test.go
  components/dm/ansible/testdata/ansible/ansible.cfg
  components/dm/ansible/testdata/ansible/hosts.ini
  components/dm/ansible/testdata/ansible/inventory.ini
  components/dm/ansible/testdata/deploy_dir/172.19.0.101/conf/dm-master.toml
  components/dm/ansible/testdata/deploy_dir/172.19.0.101/conf/dm-worker.toml
  components/dm/ansible/testdata/deploy_dir/172.19.0.101/scripts/run_alertmanager.sh
  components/dm/ansible/testdata/deploy_dir/172.19.0.101/scripts/run_dm-master.sh
  components/dm/ansible/testdata/deploy_dir/172.19.0.101/scripts/run_dm-worker.sh
  components/dm/ansible/testdata/deploy_dir/172.19.0.101/scripts/run_grafana.sh
  components/dm/ansible/testdata/deploy_dir/172.19.0.101/scripts/run_prometheus.sh
  components/dm/ansible/testdata/deploy_dir/172.19.0.102/conf/dm-worker.toml
  components/dm/ansible/testdata/deploy_dir/172.19.0.102/scripts/run_dm-worker.sh
  components/dm/ansible/testdata/readme.txt
  components/dm/ansible/worker.go
  components/dm/command/import.go
  components/dm/command/root.go
  components/dm/spec/logic.go
  components/dm/spec/topology_dm.go
  go.sum
  pkg/cluster/ansible/inventory.go
  pkg/cluster/embed/autogen_pkger.go
  pkg/cluster/executor/local.go
  pkg/cluster/executor/local_test.go
  pkg/cluster/template/scripts/dm_master.go
  templates/scripts/run_dm-master.sh.tpl
  tests/tiup-dm/ansible_data/hosts.ini
  tests/tiup-dm/ansible_data/inventory.ini
  tests/tiup-dm/test_import.sh
  tests/tiup-dm/topo/full_dm.yaml
  tests/tiup-dm/topo/full_scale_in_dm-master.yaml
  tests/tiup-dm/topo/full_scale_in_dm-worker.yaml
Labels: status/LGT2, status/PTAL

#689 Make it clear when transfer failed using native ssh
  pkg/cluster/executor/ssh.go
Labels: status/LGT1, status/PTAL, type/new-feature

#692 Fix an untranslated part of playground.md
  doc/user/playground.md
Labels: status/LGT1

#694 fail the command if failed to write audit
  components/cluster/command/root.go
  components/dm/command/root.go
  pkg/logger/audit.go
Labels: status/LGT1

#698 Remove component specified in tryURLs
  examples/dm/topology.example.yaml
  pkg/cluster/api/pdapi.go
Labels: status/LGT1, status/PTAL

#696 Do not overwrite alertmanager.yml for dm when InitConfig
  components/dm/spec/alertmanager.go
  components/dm/spec/grafana.go
  components/dm/spec/prometheus.go
  pkg/cluster/manager.go
Labels: status/LGT1, status/PTAL

#705 fix the hard-coded parameter: storage.tsdb.retention
  pkg/cluster/embed/autogen_pkger.go
  pkg/cluster/spec/prometheus.go
  pkg/cluster/template/scripts/prometheus.go
  pkg/cluster/template/scripts/prometheus_test.go
  templates/scripts/run_prometheus.sh.tpl
Labels: status/LGT1, status/can-merge, type/new-feature

#704 cluster/import: read and set deploy_dir properly on import
  go.mod
  go.sum
  pkg/cluster/ansible/import.go
  pkg/cluster/ansible/import_test.go
  pkg/cluster/ansible/test-data/inventory.ini
  pkg/cluster/ansible/test-data/meta.yaml
Labels: status/LGT1, type/bug-fix

#710 *: update dependency of pd
  go.mod
  go.sum
  pkg/cluster/api/pdapi.go
  pkg/cluster/spec/tikv.go
Labels: status/LGT1, type/enhancement

#708 Fix typo in docker/control/bashrc
  docker/control/bashrc
Labels: status/LGT1, status/can-merge

#713 cluster: set owner to current user when decompressing tarballs
  components/dm/spec/grafana.go
  components/dm/spec/prometheus.go
  pkg/cluster/operation/telemetry.go
  pkg/cluster/task/install_package.go
Labels: category/stability, status/LGT1, type/enhancement

#709 cluster/check: fix checking of existing cluster
  components/cluster/command/check.go
  pkg/cluster/operation/check.go
Labels: category/testing, status/LGT1, status/can-merge, type/bug-fix

#716 Fix showing misleading usage for cluster and dm
  components/cluster/command/root.go
  components/dm/command/root.go
  components/dm/main.go
  pkg/cliutil/cliutil.go
Labels: status/LGT1, status/PTAL

#707 cluster: fix some issues of tidb cluster with tispark component
  components/cluster/command/check.go
  components/cluster/command/start.go
  components/dm/spec/alertmanager.go
  components/dm/spec/grafana.go
  components/dm/spec/logic.go
  components/dm/spec/prometheus.go
  pkg/cluster/embed/autogen_pkger.go
  pkg/cluster/manager.go
  pkg/cluster/operation/operation.go
  pkg/cluster/spec/alertmanager.go
  pkg/cluster/spec/cdc.go
  pkg/cluster/spec/drainer.go
  pkg/cluster/spec/grafana.go
  pkg/cluster/spec/instance.go
  pkg/cluster/spec/pd.go
  pkg/cluster/spec/prometheus.go
  pkg/cluster/spec/pump.go
  pkg/cluster/spec/spec.go
  pkg/cluster/spec/tidb.go
  pkg/cluster/spec/tiflash.go
  pkg/cluster/spec/tikv.go
  pkg/cluster/spec/tispark.go
  pkg/cluster/template/scripts/tispark.go
  templates/scripts/spark-env.sh.tpl
Labels: category/testing, status/LGT1, status/can-merge, type/bug-fix

#718 Distinct instanceDir and wd
  components/playground/grafana.go
  components/playground/instance/process.go
  components/playground/monitor.go
  pkg/exec/run.go
  pkg/localdata/profile.go
Labels: status/LGT1, status/PTAL, status/can-merge

#715 Improve playground and test
  .github/workflows/integrate.yaml
  .gitignore
  components/playground/grafana.go
  components/playground/instance/instance.go
  components/playground/instance/process.go
  components/playground/main.go
  components/playground/monitor.go
  components/playground/playground.go
  pkg/utils/exec.go
  tests/tiup-playground/test_playground.sh
Labels: status/LGT1, status/PTAL

#717 cluster: restart prometheus after scaling the cluster
  components/cluster/command/scale_in.go
  components/dm/command/scale_in.go
  pkg/cluster/manager.go
Labels: category/stability, status/LGT1, status/can-merge, type/bug-fix

#712 Support use local file or directory as config for monitor components
  components/dm/spec/alertmanager.go
  components/dm/spec/grafana.go
  components/dm/spec/grafana_test.go
  components/dm/spec/prometheus.go
  components/dm/spec/testdata/dashboards/tidb.json
  components/dm/spec/topology_dm.go
  pkg/cluster/embed/autogen_pkger.go
  pkg/cluster/executor/local.go
  pkg/cluster/spec/alertmanager.go
  pkg/cluster/spec/grafana.go
  pkg/cluster/spec/grafana_test.go
  pkg/cluster/spec/instance.go
  pkg/cluster/spec/prometheus.go
  pkg/cluster/spec/testdata/dashboards/tidb.json
  pkg/cluster/spec/validate.go
  pkg/cluster/spec/validate_test.go
  pkg/cluster/template/config/alertmanager.go
  templates/scripts/run_grafana.sh.tpl
  templates/scripts/run_prometheus.sh.tpl
  tests/tiup-cluster/local/alertmanager/alertmanager.yml
  tests/tiup-cluster/local/grafana/tidb.json
  tests/tiup-cluster/local/prometheus/tidb.rules.yml
  tests/tiup-cluster/run.sh
  tests/tiup-cluster/script/cmd_subtest.sh
  tests/tiup-cluster/script/scale_tools.sh
  tests/tiup-cluster/topo/full.yaml
  tests/tiup-cluster/topo/full_without_cdc.yaml
  tests/tiup-cluster/topo/upgrade.yaml
  tests/tiup-dm/local/alertmanager/alertmanager.yml
  tests/tiup-dm/local/grafana/dm.json
  tests/tiup-dm/local/grafana/dm_instances.json
  tests/tiup-dm/local/prometheus/dm_worker.rules.yml
  tests/tiup-dm/run.sh
  tests/tiup-dm/test_cmd.sh
  tests/tiup-dm/topo/full_dm.yaml
Labels: need-update-documentation, status/LGT1, status/PTAL, type/new-feature

#724 Keep deploy dir for worker while import from ansible
  components/dm/ansible/import.go
  components/dm/ansible/import_test.go
  components/dm/command/import.go
  tests/tiup-dm/test_import.sh
Labels: status/LGT1, status/PTAL

#695 Allow empty key file
  components/cluster/command/check.go
  components/cluster/command/deploy.go
  components/cluster/command/scale_out.go
  components/dm/command/deploy.go
  components/dm/command/scale_out.go
  pkg/cliutil/ssh.go
  pkg/utils/utils.go
Labels: need-update-documentation, status/LGT1, status/PTAL, status/can-merge, type/bug-fix

#725 Add experimental tag in help message
  components/cluster/command/clean.go
  components/cluster/command/deploy.go
  components/cluster/command/root.go
  components/cluster/command/scale_out.go
  components/dm/command/root.go
Labels: status/LGT1, status/can-merge

#727 Bump v1.1.0
  CHANGELOG.md
  pkg/version/version.go
Labels: status/LGT1
