Repository pingcap/tiup, pull requests merged in 2020-07, with the labels that each got.

#559 Change the default goal in makefile
  Makefile
Labels: status/PTAL

#554 try revert some some to make dm works
  Makefile
  components/dm/command/deploy.go
  components/dm/command/root.go
  components/dm/command/start.go
  components/dm/command/telemetry.go
  docker/up.sh
  pkg/cliutil/prepare/prepare.go
  pkg/cluster/embed/autogen_pkger.go
  pkg/cluster/operation/action.go
  pkg/cluster/spec/server_config.go
  pkg/cluster/spec/spec.go
  pkg/cluster/task/builder.go
  pkg/dm/spec/cluster.go
  pkg/dm/spec/logic.go
  pkg/dm/spec/topology_dm.go
  pkg/dm/spec/topology_dm_test.go
  pkg/dms/spec/paths.go
  pkg/dms/spec/server_config.go
  pkg/dms/spec/topology.go
  pkg/dms/spec/topology_test.go
  pkg/repository/v1manifest/manifest_test.go
  templates/scripts/run_dm-master.sh.tpl
  templates/scripts/run_dm-master_scale.sh.tpl
  templates/scripts/run_dm-portal.sh.tpl
  templates/scripts/run_dm-worker.sh.tpl
Labels: status/PTAL

#560 Should request remote while local manifest expired
  pkg/repository/testdata/polluted/bin/root.json
  pkg/repository/testdata/polluted/manifests/index.json
  pkg/repository/testdata/polluted/manifests/snapshot.json
  pkg/repository/testdata/polluted/manifests/tidb.json
  pkg/repository/testdata/polluted/manifests/timestamp.json
  pkg/repository/v1_repository.go
  pkg/repository/v1_repository_test.go
  pkg/repository/v1manifest/key_store.go
  pkg/repository/v1manifest/local_manifests.go
  pkg/repository/v1manifest/local_manifests_test.go
  pkg/repository/v1manifest/manifest.go
  pkg/repository/v1manifest/testdata/polluted/bin/root.json
  pkg/repository/v1manifest/testdata/polluted/manifests/index.json
  pkg/repository/v1manifest/testdata/polluted/manifests/snapshot.json
  pkg/repository/v1manifest/testdata/polluted/manifests/tidb.json
  pkg/repository/v1manifest/testdata/polluted/manifests/timestamp.json
Labels: type/bug-fix

#558 Bugfix: patch can't overwrite twice
  components/cluster/command/patch.go
  components/cluster/command/scale_out.go
  pkg/utils/ioutil.go
  tests/tiup-cluster/script/cmd_subtest.sh
Labels: type/bug-fix

#582 update github issue template
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/general-question.md
Labels: category/documentation

#585 cluster: properly pass --wait-timeout to systemd operations
  components/cluster/command/root.go
  pkg/cluster/module/systemd.go
  pkg/cluster/operation/action.go
  pkg/cluster/operation/scale_in.go
  pkg/cluster/operation/upgrade.go
Labels: category/stability, status/can-merge, type/bug-fix

#578 Introduce a more general way to config profile
  .github/workflows/install.yaml
  .github/workflows/integrate.yaml
  install.sh
  pkg/cluster/template/install/local_install.sh.go
Labels: status/LGT1, status/can-merge, type/enhancement

#589 Fix the bug that ctl working directory is different with TiUP
  components/ctl/main.go
Labels: status/LGT2, status/can-merge, type/bug-fix

#592 Change example to show how to deploy to different arch
  examples/minimal.yaml
  examples/topology.example.yaml
Labels: category/documentation, status/can-merge, type/enhancement

#591 Run github action after PR merged
  .github/workflows/ci.yaml
  .github/workflows/integrate.yaml
  .github/workflows/reprotest.yaml
Labels: category/testing, status/LGT2, status/can-merge, type/enhancement

#576 cluster/scale-out: check for imported field earlier
  components/cluster/command/reload.go
  components/cluster/command/root_test.go
  components/cluster/command/scale_out.go
  components/cluster/command/scale_out_test.go
  components/cluster/command/upgrade.go
  components/cluster/command/upgrade_test.go
Labels: status/can-merge, type/bug-fix, type/enhancement

#593 cluster: ignore not found error when deleting something via PD API
  pkg/cluster/api/pdapi.go
Labels: category/stability, status/LGT1, status/can-merge, type/enhancement

#588 mini refactor playground to run component directly
  cmd/root.go
  cmd/telemetry.go
  components/playground/grafana.go
  components/playground/instance/drainer.go
  components/playground/instance/instance.go
  components/playground/instance/pd.go
  components/playground/instance/process.go
  components/playground/instance/pump.go
  components/playground/instance/tidb.go
  components/playground/instance/tiflash.go
  components/playground/instance/tikv.go
  components/playground/main.go
  components/playground/monitor.go
  components/playground/playground.go
  pkg/exec/run.go
  pkg/repository/v1_repository.go
  pkg/telemetry/meta.go
Labels: status/LGT1, status/PTAL, type/enhancement

#600 Bump v1.0.8
  pkg/version/version.go
Labels: status/LGT1

#599 Sort by filename when generate embed files
  pkg/cluster/embed/autogen_pkger.go
  tools/pkger/main.go
Labels: status/LGT1, status/can-merge, type/enhancement

#602 Clone with yanked version
  cmd/list.go
  pkg/cluster/clusterutil/cluster.go
  pkg/cluster/embed/autogen_pkger.go
  pkg/repository/clone_mirror.go
  pkg/repository/v1_repository.go
  pkg/repository/v1manifest/manifest.go
  pkg/repository/v1manifest/manifest_test.go
  pkg/repository/v1manifest/types.go
Labels: status/LGT1, status/WIP, type/new-feature

#606 Support bash and zsh completion
  cmd/completion.go
  cmd/root.go
Labels: category/contribution, status/LGT1, type/enhancement

#531 cluster: integrate tispark
  Makefile
  components/cluster/command/check.go
  components/cluster/command/deploy.go
  components/cluster/command/destroy.go
  components/cluster/command/display.go
  components/cluster/command/reload.go
  components/cluster/command/scale_in.go
  components/cluster/command/scale_out.go
  components/cluster/command/upgrade.go
  components/dm/command/deploy.go
  components/dm/command/scale_out.go
  docker/node/Dockerfile
  examples/topology.example.yaml
  go.mod
  go.sum
  pkg/cliutil/prepare/prepare.go
  pkg/cluster/embed/autogen_pkger.go
  pkg/cluster/embed/embed_test.go
  pkg/cluster/executor/ssh.go
  pkg/cluster/operation/destroy.go
  pkg/cluster/spec/bindversion.go
  pkg/cluster/spec/instance.go
  pkg/cluster/spec/spec.go
  pkg/cluster/spec/spec_test.go
  pkg/cluster/spec/tispark.go
  pkg/cluster/spec/util.go
  pkg/cluster/task/builder.go
  pkg/cluster/task/copy_component.go
  pkg/cluster/task/update_meta.go
  pkg/cluster/template/config/config.go
  pkg/cluster/template/config/tispark.go
  pkg/cluster/template/scripts/scripts.go
  pkg/cluster/template/scripts/tispark.go
  pkg/cluster/template/systemd/tispark.go
  pkg/utils/ioutil.go
  pkg/utils/ioutils.go
  templates/config/spark-defaults.conf.tpl
  templates/config/spark-log4j.properties.tpl
  templates/scripts/spark-env.sh.tpl
  templates/scripts/start_tispark_slave.sh.tpl
  templates/systemd/tispark.service.tpl
  tests/Makefile
  tests/tiup-cluster/run.sh
  tests/tiup-cluster/script/cmd_subtest.sh
  tests/tiup-cluster/test_cmd.sh
  tests/tiup-cluster/test_upgrade.sh
  tests/tiup-cluster/topo/full.yaml
  tests/tiup-cluster/topo/full_scale_in_tispark.yaml
  tests/tiup-cluster/topo/full_without_cdc.yaml
  tests/tiup-cluster/topology.yaml
Labels: status/LGT2, status/PTAL, type/new-feature

#605 Support yank a single version on client side
  cmd/mirror.go
  pkg/repository/remote/modify.go
  pkg/repository/v1manifest/manifest.go
  pkg/repository/v1manifest/types_test.go
  tests/tiup/tiup.toml
Labels: status/LGT1

#614 Add help msg of EDITOR
  components/cluster/command/edit_config.go
Labels: status/LGT1, status/PTAL

#612 Fix data_dir of tiflash when import cluster
  pkg/cluster/ansible/dirs.go
  pkg/cluster/ansible/dirs_test.go
Labels: status/LGT2, status/PTAL

#609 cluster: validate topo changes after edit-config
  components/cluster/command/edit_config.go
  components/dm/command/edit_config.go
  go.mod
  go.sum
  pkg/cluster/edit/diff.go
  pkg/cluster/spec/alertmanager.go
  pkg/cluster/spec/cdc.go
  pkg/cluster/spec/drainer.go
  pkg/cluster/spec/grafana.go
  pkg/cluster/spec/pd.go
  pkg/cluster/spec/prometheus.go
  pkg/cluster/spec/pump.go
  pkg/cluster/spec/spec.go
  pkg/cluster/spec/tidb.go
  pkg/cluster/spec/tiflash.go
  pkg/cluster/spec/tikv.go
  pkg/cluster/spec/tispark.go
  pkg/dm/spec/topology_dm.go
  pkg/meta/resource_ctrl.go
  pkg/repository/v1manifest/types_test.go
  pkg/utils/diff.go
  pkg/utils/diff_test.go
  pkg/utils/edit.go
Labels: category/stability, category/testing, status/LGT1, status/PTAL, status/can-merge, type/new-feature

#618 tests: split CI jobs to smaller groups
  .github/workflows/integrate.yaml
  tests/tiup-cluster/script/cmd_subtest.sh
  tests/tiup-cluster/script/scale_core.sh
  tests/tiup-cluster/script/scale_tools.sh
  tests/tiup-cluster/test_cmd.sh
  tests/tiup-cluster/test_cmd_no_cdc.sh
  tests/tiup-cluster/test_scale_core.sh
  tests/tiup-cluster/test_scale_tools.sh
  tests/tiup-cluster/test_upgrade.sh
Labels: category/testing, status/LGT1, status/can-merge

#621 cluster: optimize tispark supporting
  pkg/cluster/embed/autogen_pkger.go
  pkg/cluster/spec/spec.go
  pkg/cluster/spec/spec_test.go
  pkg/cluster/spec/tispark.go
  pkg/cluster/template/scripts/tispark.go
  pkg/cluster/template/systemd/tispark.go
  templates/scripts/spark-env.sh.tpl
  templates/systemd/tispark.service.tpl
Labels: category/usability, status/LGT1, type/enhancement

#622 If a new version is found when executing a component, remind the user
  components/playground/playground.go
  pkg/exec/run.go
Labels: status/LGT1, type/enhancement

#620 Evaluate absolute directory when user run playground
  components/playground/main.go
  components/playground/playground.go
  components/playground/playground_test.go
  go.mod
Labels: status/LGT1, type/bug-fix

#624 cluster: allow continue editing when new topology has errors
  components/cluster/command/edit_config.go
  pkg/cliutil/tui.go
Labels: category/usability, status/LGT1, status/can-merge, type/enhancement

#625 Support refresh configuration only when reload
  components/cluster/command/reload.go
  tests/tiup-cluster/script/scale_core.sh
Labels: status/LGT1, type/new-feature

#627 Apply config file on scaled pd server
  components/playground/playground.go
  pkg/cluster/embed/autogen_pkger.go
  pkg/cluster/spec/pd.go
  templates/scripts/run_pd_scale.sh.tpl
Labels: status/LGT2

#630 Refresh monitor configs on reload
  components/cluster/command/reload.go
Labels: status/LGT1, type/bug-fix

#631 Support posix style argument for --user"
  components/cluster/command/check.go
  components/cluster/command/deploy.go
  components/cluster/command/scale_out.go
Labels: category/usability, status/LGT1

#615 Support native ssh client
  .github/workflows/integrate.yaml
  components/cluster/command/check.go
  components/cluster/command/deploy.go
  components/cluster/command/display.go
  components/cluster/command/import.go
  components/cluster/command/reload.go
  components/cluster/command/root.go
  components/cluster/command/scale_out.go
  components/dm/command/deploy.go
  components/playground/instance/process.go
  components/playground/playground.go
  components/playground/utils/utils.go
  pkg/cluster/ansible/config.go
  pkg/cluster/ansible/dirs.go
  pkg/cluster/ansible/inventory.go
  pkg/cluster/executor/ssh.go
  pkg/cluster/operation/operation.go
  pkg/cluster/task/builder.go
  pkg/cluster/task/context.go
  pkg/cluster/task/ssh.go
  pkg/exec/run.go
  pkg/localdata/constant.go
  pkg/utils/exec.go
  pkg/utils/ioutil.go
  tests/tiup-cluster/script/cmd_subtest.sh
  tests/tiup-cluster/script/scale_core.sh
  tests/tiup-cluster/script/scale_tools.sh
  tests/tiup-cluster/test_cmd.sh
  tests/tiup-cluster/test_cmd_no_cdc.sh
  tests/tiup-cluster/test_cmd_with_native_ssh.sh
  tests/tiup-cluster/test_scale_core.sh
  tests/tiup-cluster/test_scale_core_with_native_ssh.sh
  tests/tiup-cluster/test_scale_tools.sh
  tests/tiup-cluster/test_scale_tools_with_native_ssh.sh
Labels: status/LGT1, type/new-feature

#638 Fix PD config incompatible when retrieving dashboard address
  go.mod
  go.sum
  pkg/cluster/api/pdapi.go
Labels: status/LGT1, type/bug-fix

#634 Overwrite the default --help persistent flag
  cmd/root.go
Labels: category/usability, status/LGT1

#640 Dont hint user to update component when user specify version
  pkg/exec/run.go
Labels: category/usability, status/LGT1

#636 Enhance native ssh test
  components/cluster/command/scale_in.go
  components/dm/command/scale_in.go
  docker/control/Dockerfile
  docker/up.sh
  pkg/cluster/executor/ssh.go
  pkg/cluster/manager.go
  pkg/cluster/task/builder.go
  tests/tiup-cluster/script/scale_core.sh
  tests/tiup-cluster/script/scale_tools.sh
  tests/tiup-cluster/script/util.sh
  tests/tiup-cluster/test_cmd_with_native_ssh.sh
  tests/tiup-cluster/test_scale_core_with_native_ssh.sh
  tests/tiup-cluster/test_scale_tools_with_native_ssh.sh
  tests/tiup-dms/test_dms_cmd.sh
Labels: status/LGT1, status/WIP

#643 Tweak the upgrade order of components
  pkg/cluster/spec/spec.go
Labels: status/LGT1, type/bug-fix

#635 Handle yanked version in update
  cmd/list.go
  cmd/mirror.go
  components/playground/playground.go
  pkg/exec/run.go
  pkg/repository/clone_mirror.go
  pkg/repository/v1_repository.go
  pkg/repository/v1_repository_test.go
Labels: status/LGT1, status/can-merge, type/bug-fix

#629 Add integration test for tiup-dm
  .github/workflows/integrate.yaml
  components/dm/spec/logic.go
  components/dm/spec/topology_dm.go
  docker/docker-compose.dm.yml
  pkg/cluster/embed/autogen_pkger.go
  pkg/cluster/task/update_dm_meta.go
  pkg/cluster/template/scripts/dm_portal.go
  templates/scripts/run_dm-master.sh.tpl
  templates/scripts/run_dm-master_scale.sh.tpl
  templates/scripts/run_dm-portal.sh.tpl
  templates/scripts/run_dm-worker.sh.tpl
  tests/tiup-cluster/run.sh
  tests/tiup-cluster/topo/full_scale_in_dm-master.yaml
  tests/tiup-cluster/topo/full_scale_in_dm-portal.yaml
  tests/tiup-cluster/topo/full_scale_in_dm-worker.yaml
  tests/tiup-dm/cover/.gitkeep
  tests/tiup-dm/root.json
  tests/tiup-dm/run.sh
  tests/tiup-dm/script/task/db1.prepare.sql
  tests/tiup-dm/script/task/db2.prepare.sql
  tests/tiup-dm/script/task/run.sh
  tests/tiup-dm/script/task/source1.toml
  tests/tiup-dm/script/task/source2.toml
  tests/tiup-dm/script/task/task.yaml
  tests/tiup-dm/script/util.sh
  tests/tiup-dm/test_cmd.sh
  tests/tiup-dm/test_upgrade.sh
  tests/tiup-dm/topo/full_dm.yaml
  tests/tiup-dm/topo/full_scale_in_dm-master.yaml
  tests/tiup-dm/topo/full_scale_in_dm-worker.yaml
  tests/tiup-dms/run.sh
Labels: status/LGT2, status/PTAL, status/can-merge

#645 Pre-check deploy version of dm
  Makefile
  components/dm/command/deploy.go
  components/dm/command/deploy_test.go
Labels: status/LGT1, status/PTAL

#646 Include dm integrate test for coverage
  .github/workflows/integrate.yaml
  components/dm/command/check.go
  components/dm/command/root.go
  components/dm/command/test.go
Labels: status/LGT1, status/PTAL
