Repository pingcap/tiup, pull requests merged in 2020-09, with the labels that each got.

#723 v1manifest: return error if signature incorrect
  cmd/list.go
Labels: category/contribution, status/LGT2, status/investigating, type/bug-fix

#732 Display checking state using bar
  components/playground/main.go
  components/playground/playground.go
  pkg/cliutil/progress/example_single_bar_test.go
Labels: status/LGT1, status/PTAL

#733 Set Pdeathsig to kill subprocess if playground dead
  components/playground/grafana.go
  components/playground/instance/proc_attr_default.go
  components/playground/instance/proc_attr_linux.go
  components/playground/instance/process.go
  components/playground/main.go
  components/playground/monitor.go
  pkg/exec/run.go
Labels: status/LGT1, status/PTAL, status/can-merge

#654 Add enable and disable sub command
  components/cluster/command/deploy.go
  components/cluster/command/disable.go
  components/cluster/command/enable.go
  components/cluster/command/root.go
  pkg/cluster/manager.go
  pkg/cluster/module/systemd.go
  pkg/cluster/operation/action.go
  tests/tiup-cluster/script/cmd_subtest.sh
Labels: need-update-documentation, status/LGT1, status/PTAL, status/can-merge, type/new-feature

#738 Bugfix: cleanup wrong conf files
  components/dm/spec/grafana.go
  pkg/cluster/executor/ssh.go
  pkg/cluster/spec/alertmanager.go
  pkg/cluster/spec/grafana.go
  pkg/cluster/spec/prometheus.go
Labels: status/LGT1

#726 Support ycsb bench
  components/bench/main.go
  components/bench/ycsb.go
  go.mod
  go.sum
Labels: status/LGT1, status/PTAL, type/new-feature

#746 typo(docker): indent
  docker/README.md
  docker/docker-compose.yml
Labels: status/LGT1

#745 server/handler: MaxFileSize -> MaxMemory
  server/handler/tarball.go
Labels: status/LGT1, status/can-merge

#747 fix(docker): ompatible with macOS's echo
  docker/up.sh
Labels: status/LGT1

#740 Reload prometheus configuration dynamically
  components/cluster/command/check.go
  pkg/cluster/embed/autogen_pkger.go
  pkg/cluster/manager.go
  pkg/cluster/spec/spec.go
  pkg/cluster/task/builder.go
  pkg/cluster/task/systemd.go
  templates/systemd/system.service.tpl
Labels: status/LGT1, type/bug-fix

#748 Support using --self and --all flag at the same time when using tiup update command
  cmd/update.go
Labels: status/LGT1, status/can-merge, type/enhancement

#749 Dump dns & port file at data dir
  components/playground/main.go
  components/playground/playground.go
  tests/tiup-playground/test_playground.sh
Labels: status/LGT2, status/PTAL, status/can-merge, type/bug

#734 executor/ssh: introduce TIUP_SSH_PATH,TIUP_SCP_PATH
  pkg/cluster/executor/ssh.go
  pkg/localdata/constant.go
  pkg/utils/ioutil.go
  pkg/utils/ioutil_test.go
Labels: status/LGT1

#758 cliutil: set cmdLine if registered
  components/cluster/main.go
  pkg/cliutil/cliutil.go
Labels: status/LGT1

#756 update tispark example parameter spark.tispark.grpc.framesize value
  examples/topology.example.yaml
Labels: status/LGT1, status/can-merge

#757 ci: apply codecov path fix
  .github/workflows/integrate.yaml
  docker/control/Dockerfile
Labels: category/testing, status/LGT1

#699 Support local executor
  components/cluster/command/check.go
  components/cluster/command/deploy.go
  components/cluster/command/display.go
  components/cluster/command/import.go
  components/cluster/command/root.go
  components/cluster/command/scale_in.go
  components/cluster/command/scale_out.go
  components/dm/ansible/import.go
  components/dm/ansible/import_test.go
  components/dm/command/deploy.go
  components/dm/command/import.go
  components/dm/command/root.go
  components/dm/command/scale_in.go
  components/dm/command/scale_out.go
  components/dm/spec/grafana_test.go
  pkg/cluster/ansible/config.go
  pkg/cluster/ansible/dirs.go
  pkg/cluster/ansible/inventory.go
  pkg/cluster/executor/executor.go
  pkg/cluster/executor/local.go
  pkg/cluster/executor/local_test.go
  pkg/cluster/executor/ssh.go
  pkg/cluster/manager.go
  pkg/cluster/operation/operation.go
  pkg/cluster/spec/grafana_test.go
  pkg/cluster/spec/spec.go
  pkg/cluster/task/builder.go
  pkg/cluster/task/context.go
  pkg/cluster/task/ssh.go
  tests/tiup-cluster/script/cmd_subtest.sh
Labels: status/LGT1, status/PTAL

#768 Fix the issue that tiflash's data is not clean up when tombstone
  pkg/cluster/operation/action.go
  pkg/cluster/spec/tiflash.go
Labels: status/LGT1, status/PTAL, type/bug-fix

#775 ci: split github workflows
  .github/workflows/integrate-cluster-cmd.yaml
  .github/workflows/integrate-cluster-scale.yaml
  .github/workflows/integrate-dm.yaml
  .github/workflows/integrate-playground.yaml
  .github/workflows/integrate-tiup.yaml
  .github/workflows/integrate.yaml
  .github/workflows/reprotest.yaml
  Makefile
  docker/docker-compose.yml
  docker/node/Dockerfile
Labels: category/testing, status/WIP, type/enhancement

#762 Fix wrong tikv store leader count
  .github/workflows/integrate-cluster-cmd.yaml
  go.mod
  go.sum
  pkg/cluster/api/pdapi.go
  pkg/cluster/spec/tikv.go
Labels: status/LGT2, status/PTAL, type/bug-fix

#773 Refine log if failed to scp
  pkg/cluster/executor/ssh.go
Labels: status/LGT1, status/PTAL

#770 template: support new cdc arguments `gc-ttl` and `tz`
  pkg/cluster/embed/autogen_pkger.go
  pkg/cluster/spec/cdc.go
  pkg/cluster/template/scripts/cdc.go
  templates/scripts/run_cdc.sh.tpl
Labels: status/LGT1, status/PTAL, status/can-merge

#769 template: remove duplicated config in run_tidb.sh.tpl
  pkg/cluster/embed/autogen_pkger.go
  templates/scripts/run_tidb.sh.tpl
Labels: status/LGT1, status/can-merge

#777 playground: support ticdc for playground
  components/playground/command.go
  components/playground/instance/ticdc.go
  components/playground/main.go
  components/playground/playground.go
Labels: status/LGT1, status/PTAL, type/new-feature

#779 Fix dependences version binding when cloning mirror
  cmd/mirror.go
  pkg/cluster/manager.go
  pkg/cluster/prepare.go
  pkg/cluster/spec/bindversion.go
  pkg/cluster/task/builder.go
  pkg/cluster/task/copy_component.go
  pkg/cluster/task/download.go
  pkg/repository/clone_mirror.go
  pkg/repository/v1manifest/key_store.go
  pkg/repository/v1manifest/local_manifests.go
Labels: status/LGT1, type/bug-fix

#794 Fix/tests wrong path
  .github/workflows/install.yaml
  .github/workflows/integrate-cluster-cmd.yaml
  .github/workflows/integrate-cluster-scale.yaml
  .github/workflows/integrate-dm.yaml
  .github/workflows/integrate-playground.yaml
  .github/workflows/integrate-tiup.yaml
  .github/workflows/reprotest.yaml
  docker/control/bashrc
  tests/tiup-cluster/run.sh
Labels: status/LGT1

#795 Fix panic if the query key not exist
  pkg/cluster/api/binlog.go
Labels: status/LGT1, status/PTAL

#788 Support tiup env command
  cmd/env.go
  cmd/root.go
  pkg/localdata/constant.go
  tests/tiup/test_tiup.sh
Labels: status/LGT1, status/PTAL, status/can-merge, type/new-feature

#802 cluster/command: missing short help of clean/destory
  components/cluster/command/clean.go
  components/cluster/command/destroy.go
Labels: status/LGT1

#801 Fix/display selinux result
  pkg/cluster/operation/check.go
  tests/tiup-cluster/script/cmd_subtest.sh
Labels: status/LGT2, status/PTAL, status/can-merge, type/enhancement

#793 Skip download nightly package when it exists
  pkg/cluster/operation/download.go
Labels: status/LGT1, status/can-merge

#804 dm: forget to set sshType,sshTimeout
  components/dm/ansible/import.go
  components/dm/command/deploy.go
  components/dm/command/root.go
Labels: status/LGT1, status/can-merge, type/bug-fix

#755 Feature/download in stream mode
  .gitignore
  Makefile
  cmd/cmd_test.go
  docker/control/Dockerfile
  pkg/cluster/clusterutil/cluster.go
  pkg/environment/env.go
  pkg/localdata/constant.go
  pkg/repository/mirror.go
  pkg/repository/v1_repository.go
  pkg/repository/v1manifest/local_manifests.go
Labels: status/LGT1, type/enhancement

#803 playground: dry, rm duplicated code
  components/playground/command.go
  components/playground/playground.go
  tests/tiup-playground/test_playground.sh
Labels: status/LGT1, status/can-merge, type/enhancement

#806 cluster: fix custom port handling for drainer on importing
  pkg/cluster/ansible/inventory.go
  pkg/cluster/ansible/service.go
  pkg/cluster/ansible/service_test.go
  pkg/cluster/ansible/test-data/inventory.ini
  pkg/cluster/ansible/test-data/meta.yaml
Labels: status/LGT1, type/bug-fix

#818 *: set timeout's type from int64 to uint64
  components/cluster/command/patch.go
  components/cluster/command/reload.go
  components/cluster/command/root.go
  components/cluster/command/scale_in.go
  components/cluster/command/upgrade.go
  components/dm/ansible/import.go
  components/dm/command/display.go
  components/dm/command/patch.go
  components/dm/command/reload.go
  components/dm/command/root.go
  components/dm/command/scale_in.go
  components/dm/command/upgrade.go
  pkg/cluster/ansible/config.go
  pkg/cluster/ansible/inventory.go
  pkg/cluster/ansible/service.go
  pkg/cluster/manager.go
  pkg/cluster/operation/action.go
  pkg/cluster/operation/destroy.go
  pkg/cluster/operation/operation.go
  pkg/cluster/operation/scale_in.go
  pkg/cluster/spec/instance.go
  pkg/cluster/task/builder.go
  pkg/cluster/task/context.go
  pkg/cluster/task/ssh.go
Labels: status/LGT1, type/enhancement

#817 Support config core dump limit
  pkg/cluster/embed/autogen_pkger.go
  pkg/cluster/spec/instance.go
  pkg/cluster/template/systemd/system.go
  pkg/meta/resource_ctrl.go
  templates/systemd/system.service.tpl
Labels: status/LGT1, status/can-merge

#812 Force relaod, scale-in and destroy
  components/cluster/command/check.go
  components/cluster/command/deploy.go
  components/cluster/command/destroy.go
  components/cluster/command/reload.go
  components/cluster/command/scale_out.go
  pkg/cluster/ansible/config.go
  pkg/cluster/manager.go
  pkg/cluster/operation/action.go
  pkg/cluster/operation/destroy.go
  pkg/cluster/operation/upgrade.go
  pkg/cluster/task/builder.go
  pkg/cluster/task/step.go
  pkg/cluster/task/task.go
Labels: status/LGT1, status/PTAL, type/enhancement

#800 Support tikv label check
  components/cluster/command/deploy.go
  components/cluster/command/scale_out.go
  examples/topology.example.yaml
  pkg/cluster/api/pdapi.go
  pkg/cluster/manager.go
  pkg/cluster/spec/server_config.go
  pkg/cluster/spec/server_config_test.go
  pkg/cluster/spec/spec.go
  pkg/cluster/spec/spec_test.go
  pkg/cluster/spec/tikv.go
  pkg/cluster/spec/validate.go
  pkg/cluster/spec/validate_test.go
Labels: status/LGT1, status/can-merge, type/new-feature

#810 Fix dm start script
  pkg/cluster/embed/autogen_pkger.go
  templates/scripts/run_dm-worker.sh.tpl
Labels: status/LGT1, status/PTAL, status/can-merge, type/bug

#816 Fix self update
  .github/workflows/install.yaml
  cmd/update.go
  pkg/repository/mirror.go
  pkg/repository/v1_repository.go
Labels: status/LGT1, status/can-merge, type/bug-fix

#815 dm: redirect stdout to log files
  pkg/cluster/embed/autogen_pkger.go
  templates/scripts/run_dm-master.sh.tpl
  templates/scripts/run_dm-master_scale.sh.tpl
  templates/scripts/run_dm-worker.sh.tpl
Labels: status/LGT1, status/can-merge

#821 fix tidb count in error message
  components/playground/playground.go
Labels: status/LGT1

#811 Remove some useless flag
  components/dm/command/deploy.go
  components/dm/command/display.go
  components/dm/command/patch.go
  components/dm/command/reload.go
  components/dm/command/scale_in.go
  components/dm/command/upgrade.go
  tests/tiup-dm/test_upgrade.sh
Labels: status/LGT2, status/can-merge

#820 Add more test case for target's spec.TargetDir
  pkg/repository/v1_repository.go
  pkg/repository/v1_repository_test.go
  pkg/repository/v1manifest/local_manifests.go
  tests/tiup/test_tiup.sh
Labels: status/LGT1, status/can-merge, type/enhancement

#822 Use absolute path of DataDir/DeployDir/LogDir
  components/cluster/command/check.go
  components/dm/spec/logic.go
  components/dm/spec/topology_dm.go
  components/dm/spec/topology_dm_test.go
  go.mod
  go.sum
  pkg/cluster/clusterutil/clusterutil.go
  pkg/cluster/clusterutil/parse_topology.go
  pkg/cluster/clusterutil/parse_topology_test.go
  pkg/cluster/manager.go
  pkg/cluster/operation/check.go
  pkg/cluster/operation/destroy.go
  pkg/cluster/spec/parse_topology.go
  pkg/cluster/spec/parse_topology_test.go
  pkg/cluster/spec/spec.go
  pkg/cluster/spec/testdata/topology_err.yaml
  pkg/cluster/spec/util.go
  pkg/cluster/spec/util_test.go
  pkg/cluster/spec/validate.go
  pkg/cluster/task/check.go
Labels: status/LGT1, status/PTAL, type/new-feature

#825 Fix index dir mode
  components/err/error.go
Labels: status/LGT1, type/bug-fix

#826 Bump v1.2.0
  CHANGELOG.md
  pkg/version/version.go
Labels: status/LGT1
