Repository pingcap/tiup, pull requests merged in 2021-05, with the labels that each got.

#1331 tiup: optimize some mirror subcommands
  cmd/mirror.go
  tests/tiup-playground/test_playground.sh
Labels: category/usability, component/tiup, size/M, status/LGT1, status/can-merge

#1342 repository: set user agent for mirror requests
  pkg/repository/mirror.go
Labels: size/XS, status/LGT1, status/can-merge

#1336 cluster: fix and optimize os version check
  pkg/cluster/operation/check.go
Labels: size/S, status/LGT1, status/can-merge

#1348 install.sh: check depends before downloading package
  install.sh
  pkg/cluster/template/install/local_install.sh.go
Labels: category/usability, size/M, status/LGT1, status/can-merge

#1341 telemetry: add basic telemetry for `tiup`
  cmd/clean.go
  cmd/completion.go
  cmd/env.go
  cmd/install.go
  cmd/list.go
  cmd/mirror.go
  cmd/root.go
  cmd/status.go
  cmd/telemetry.go
  cmd/uninstall.go
  cmd/update.go
  components/cluster/command/deploy.go
  components/cluster/command/root.go
  components/cluster/command/telemetry.go
  pkg/cluster/operation/telemetry.go
  pkg/flags/debug.go
  pkg/localdata/constant.go
  pkg/telemetry/report.go
  pkg/telemetry/report.pb.go
  pkg/telemetry/report.proto
  pkg/telemetry/report_test.go
Labels: component/tiup, size/XXL, status/LGT1, status/can-merge

#1349 Fix the issue that installation instructions result in old tiup version
  pkg/repository/model/model.go
Labels: size/S, status/LGT1, status/can-merge

#1353 telemetry: add simple report for playground
  cmd/root.go
  components/cluster/command/deploy.go
  components/cluster/command/root.go
  components/playground/command.go
  components/playground/instance/instance.go
  components/playground/main.go
  components/playground/playground.go
  pkg/cluster/operation/telemetry.go
  pkg/telemetry/report.go
  pkg/telemetry/report.pb.go
  pkg/telemetry/report.proto
  pkg/telemetry/scrub.go
Labels: component/playground, size/XXL, status/LGT1, status/can-merge

#1350 Comments all lines from files in ansible-imported-configs after import from ansible
  components/cluster/command/import.go
  pkg/cluster/ansible/import.go
Labels: ansible, size/M, status/LGT1, status/can-merge

#1346 cluster: fix wrong data_dir for imported drainer instances
  pkg/cluster/ansible/service.go
Labels: component/cluster, size/XS, status/LGT1, status/can-merge, type/bug-fix

#1358 cluster: add JSON output option for display
  components/cluster/command/display.go
  pkg/cluster/manager/display.go
  pkg/cluster/operation/operation.go
Labels: size/L, status/LGT1, status/can-merge

#1357 bump version 1.4.3
  CHANGELOG.md
  pkg/version/version.go
Labels: size/S, status/LGT1, status/can-merge

#1363 cluster: allow scale-in when there is no tispark master node
  pkg/cluster/manager/scale_in.go
Labels: size/XS, status/LGT1, status/can-merge, type/enhancement

#1359 cluster: ignore error when increasing schedule limit during upgrade
  pkg/cluster/operation/upgrade.go
Labels: component/cluster, size/XS, status/LGT1, status/can-merge

#1361 set prof_active to false
  embed/templates/scripts/run_tikv.sh.tpl
Labels: size/XS, status/LGT1, status/can-merge

#1367 cluster: make port check error message more clear to users.
  pkg/cluster/spec/validate.go
  pkg/cluster/spec/validate_test.go
Labels: category/usability, component/cluster, good first issue, size/XS, status/LGT1

#1365 playground: implement `mode` option for painter algorithm populating options
  components/playground/main.go
  components/playground/playground.go
Labels: category/usability, component/playground, size/XL, status/LGT1, status/can-merge

#1369 modify MALLOC_CONF for playground
  components/playground/instance/tikv.go
Labels: size/XS, status/LGT1, status/can-merge

#1376 Fix the issue that the global absolute log dir path not generate correctly
  pkg/cluster/spec/parse_topology_test.go
  pkg/cluster/spec/spec.go
Labels: size/M, status/LGT1, status/can-merge

#1378 Don't check labels when user enable placement-rule
  pkg/cluster/api/pdapi.go
  pkg/cluster/manager/display.go
  pkg/cluster/manager/scale_out.go
Labels: size/S, status/LGT1, status/can-merge

#1380 cluster: make two configs in cdc spec editable
  pkg/cluster/spec/cdc.go
Labels: size/XS, status/LGT1, status/can-merge

#1383 cluster: fix wrong SELINUX disabling config
  pkg/cluster/manager/check.go
Labels: size/XS, status/LGT1, status/can-merge, type/bug-fix

#1382 cluster/executor: implement native SCP download instead of cat
  components/cluster/command/transfer.go
  components/dm/ansible/import.go
  components/dm/ansible/import_test.go
  components/dm/spec/logic.go
  pkg/cluster/ansible/config.go
  pkg/cluster/ctxt/context.go
  pkg/cluster/executor/checkpoint.go
  pkg/cluster/executor/local.go
  pkg/cluster/executor/local_test.go
  pkg/cluster/executor/scp.go
  pkg/cluster/executor/ssh.go
  pkg/cluster/manager/transfer.go
  pkg/cluster/operation/telemetry.go
  pkg/cluster/spec/alertmanager.go
  pkg/cluster/spec/cdc.go
  pkg/cluster/spec/drainer.go
  pkg/cluster/spec/grafana.go
  pkg/cluster/spec/instance.go
  pkg/cluster/spec/pd.go
  pkg/cluster/spec/prometheus.go
  pkg/cluster/spec/pump.go
  pkg/cluster/spec/tidb.go
  pkg/cluster/spec/tiflash.go
  pkg/cluster/spec/tikv.go
  pkg/cluster/spec/tispark.go
  pkg/cluster/task/builder.go
  pkg/cluster/task/copy_file.go
  pkg/cluster/task/init_config_test.go
  pkg/cluster/task/install_package.go
  pkg/cluster/task/monitored_config.go
  pkg/cluster/task/tls.go
Labels: component/cluster, size/XL, status/LGT1, status/can-merge, type/enhancement

#1386 Fix the issue that the imported monitor directory may conflict with o…
  pkg/cluster/spec/validate.go
Labels: size/S, status/LGT1, status/can-merge

#1387 Renew expired manifests used in unit tests
  pkg/repository/testdata/polluted/bin/root.json
  pkg/repository/testdata/polluted/manifests/snapshot.json
  pkg/repository/v1_repository_test.go
  pkg/repository/v1manifest/testdata/polluted/bin/root.json
Labels: size/XS, status/LGT1, status/can-merge

#1384 bump version 1.4.4
  CHANGELOG.md
  pkg/version/version.go
Labels: size/S, status/LGT1, status/can-merge

#1388 README: remove TiDB Monthly
  README.md
Labels: size/XS, status/LGT1, status/can-merge
