Repository pingcap/tiup, pull requests merged in 2021-08, with the labels that each got.

#1506 playground: Set terminal title
  components/playground/main.go
Labels: size/XS, status/LGT1, status/can-merge

#1500 Fix telemetry timeout
  cmd/mirror.go
  cmd/root.go
  components/cluster/command/root.go
  components/playground/main.go
  pkg/cluster/api/dmapi.go
  pkg/cluster/api/pdapi.go
  pkg/cluster/spec/util.go
  pkg/cluster/template/install/local_install.sh.go
  pkg/repository/store/txn.go
  pkg/telemetry/telemetry.go
  pkg/telemetry/telemetry_test.go
  pkg/utils/http_client.go
Labels: size/L, status/LGT1, status/can-merge

#1510 ignore exporters when check data_dir overlap
  pkg/cluster/spec/validate.go
  pkg/cluster/spec/validate_test.go
Labels: size/M, status/LGT1, status/can-merge

#1509 bump version 1.5.4
  CHANGELOG.md
  pkg/version/version.go
Labels: size/S, status/LGT1, status/can-merge

#1513 cluster: skip updating topology when reload with --skip-restart
  pkg/cluster/manager/reload.go
Labels: type/bug-fix, status/can-merge, status/LGT1, size/S, component/cluster

#1492 cluster: add ability to ignore monitor agent for instances
  components/dm/command/scale_in.go
  components/dm/spec/logic.go
  components/dm/spec/topology_dm.go
  pkg/cluster/manager/builder.go
  pkg/cluster/manager/cleanup.go
  pkg/cluster/manager/deploy.go
  pkg/cluster/manager/reload.go
  pkg/cluster/manager/upgrade.go
  pkg/cluster/operation/action.go
  pkg/cluster/operation/destroy.go
  pkg/cluster/spec/alertmanager.go
  pkg/cluster/spec/cdc.go
  pkg/cluster/spec/drainer.go
  pkg/cluster/spec/grafana.go
  pkg/cluster/spec/pd.go
  pkg/cluster/spec/prometheus.go
  pkg/cluster/spec/pump.go
  pkg/cluster/spec/spec.go
  pkg/cluster/spec/tidb.go
  pkg/cluster/spec/tiflash.go
  pkg/cluster/spec/tikv.go
  pkg/cluster/spec/tispark.go
  pkg/cluster/spec/validate.go
  pkg/cluster/spec/validate_test.go
  tests/tiup-dm/test_cmd.sh
Labels: type/new-feature, status/can-merge, status/LGT1, size/XL, category/monitoring, component/cluster

#1502 Update embed examples
  components/cluster/command/template.go
  components/dm/command/template.go
  embed/embed.go
  embed/embed_test.go
  embed/examples/cluster/local.yaml
  embed/examples/cluster/minimal.yaml
  embed/examples/cluster/multi-dc.yaml
  embed/examples/cluster/topology.example.yaml
  embed/examples/dm/minimal.yaml
  embed/examples/dm/topology.example.yaml
  pkg/cluster/template/config/alertmanager.go
  pkg/cluster/template/config/blackbox.go
  pkg/cluster/template/config/config.go
  pkg/cluster/template/config/dashboard.go
  pkg/cluster/template/config/datasource.go
  pkg/cluster/template/config/grafana.go
  pkg/cluster/template/config/prometheus.go
  pkg/cluster/template/config/tispark.go
  pkg/cluster/template/scripts/alertmanager.go
  pkg/cluster/template/scripts/blackbox_exporter.go
  pkg/cluster/template/scripts/cdc.go
  pkg/cluster/template/scripts/dm_master.go
  pkg/cluster/template/scripts/dm_worker.go
  pkg/cluster/template/scripts/drainer.go
  pkg/cluster/template/scripts/grafana.go
  pkg/cluster/template/scripts/node_exporter.go
  pkg/cluster/template/scripts/pd.go
  pkg/cluster/template/scripts/prometheus.go
  pkg/cluster/template/scripts/pump.go
  pkg/cluster/template/scripts/scripts.go
  pkg/cluster/template/scripts/tidb.go
  pkg/cluster/template/scripts/tiflash.go
  pkg/cluster/template/scripts/tikv.go
  pkg/cluster/template/systemd/system.go
  pkg/cluster/template/systemd/tispark.go
Labels: status/can-merge, status/LGT1, size/L

#1512 playground: deprecate bootstrap option `--monitor` and add a new option `--without-monitor` to disable monitors.
  components/playground/main.go
Labels: status/can-merge, status/LGT1, size/S, component/playground

#1516 Use absolute path for sudo command #1515
  components/playground/main.go
  pkg/cluster/executor/local.go
  pkg/cluster/executor/ssh.go
  pkg/cluster/operation/check.go
Labels: status/can-merge, status/LGT1, size/S

#1517 *: use the rand source initialized by ourself
  pkg/cluster/audit/audit.go
  pkg/cluster/task/ssh_keygen.go
  pkg/crypto/ca.go
  pkg/crypto/rand/rand.go
  pkg/crypto/rsa.go
  pkg/repository/mirror.go
  pkg/telemetry/meta.go
Labels: status/can-merge, status/LGT1, size/S

#1519 *: update linter
  Makefile
  components/dm/ansible/import.go
Labels: status/can-merge, status/LGT1, size/XS

#1511 playground: fix bug which can't specify db port
  components/playground/instance/instance.go
  components/playground/instance/tidb.go
  components/playground/main.go
  components/playground/playground.go
  go.mod
  go.sum
Labels: status/can-merge, status/LGT1, size/M, good first issue, component/playground

#1520 show port of tidb when scale-out on playground
  components/playground/playground.go
Labels: status/can-merge, status/LGT1, size/L, component/playground

#1522 Adjust --comments position
  components/playground/playground.go
Labels: status/can-merge, status/LGT1, size/XS

#1524 bump version 1.5.5
  CHANGELOG.md
  pkg/version/version.go
Labels: size/S

#1529 tests: fix CI tests
  docker/control/Dockerfile
  docker/node/Dockerfile
  pkg/cluster/executor/local.go
  pkg/cluster/executor/ssh.go
Labels: size/S

#1523 Add some desc when execute `tiup-cluster restart`
  pkg/cluster/manager/basic.go
Labels: status/can-merge, status/LGT1, size/XS

#1532 update ComponentManifests simultaneously when tiup list
  pkg/repository/v1_repository.go
Labels: status/can-merge, status/LGT1, size/S

#1535 cluster: update os check
  pkg/cluster/operation/check.go
Labels: size/XS

#1540 fix dm test
  tests/tiup-dm/test_cmd.sh
Labels: status/can-merge, status/LGT1, size/XS

#1538 cluster: reverse the order of audit log list
  pkg/cluster/audit/audit.go
  pkg/cluster/audit/audit_test.go
Labels: status/can-merge, status/LGT1, size/XS
