Repository pingcap/tiup, pull requests merged in 2021-04, with the labels that each got.

#1272 enable but inact memory profiling
  components/playground/instance/process.go
  components/playground/instance/tikv.go
  embed/templates/scripts/run_tikv.sh.tpl
  pkg/exec/run.go
Labels: size/M, status/LGT1, status/can-merge

#1263 Feature/confirm reload patch rename
  components/cluster/command/patch.go
  components/cluster/command/reload.go
  components/cluster/command/rename.go
  components/cluster/command/restart.go
  components/cluster/command/stop.go
  components/dm/command/patch.go
  components/dm/command/reload.go
  components/dm/command/restart.go
  components/dm/command/stop.go
  pkg/cluster/manager/basic.go
  pkg/cluster/manager/patch.go
  pkg/cluster/manager/reload.go
  pkg/cluster/manager/rename.go
  tests/tiup-cluster/script/cmd_subtest.sh
  tests/tiup-cluster/script/scale_core.sh
Labels: size/L, status/LGT1, status/can-merge

#1262 cluster: start pd,dm-master in sequentially
  pkg/cluster/manager/builder.go
  pkg/cluster/operation/action.go
  pkg/cluster/operation/operation.go
Labels: size/S, status/LGT1, status/can-merge

#1274 Fix the compatibility with PD v3.x
  pkg/cluster/api/pdapi.go
Labels: size/M, status/LGT1, status/can-merge, type/bug-fix

#1259 Fix the issue that checkpoint can't parse large audit log
  pkg/checkpoint/checkpoint.go
Labels: size/XS, status/LGT1, status/can-merge

#1265 cluster: reload shoud pass through ignore-config-check
  pkg/cluster/manager/reload.go
Labels: size/XS, status/LGT1, status/can-merge

#1276 Update grafana.ini.tpl
  embed/templates/config/grafana.ini.tpl
Labels: size/XS, status/LGT1, status/can-merge

#1224 Add advertise addr for TiKV and PD
  embed/templates/scripts/run_pd.sh.tpl
  embed/templates/scripts/run_pd_scale.sh.tpl
  embed/templates/scripts/run_tidb.sh.tpl
  embed/templates/scripts/run_tikv.sh.tpl
  pkg/cluster/spec/pd.go
  pkg/cluster/spec/spec.go
  pkg/cluster/spec/tidb.go
  pkg/cluster/spec/tikv.go
  pkg/cluster/template/scripts/pd.go
  pkg/cluster/template/scripts/tidb.go
  pkg/cluster/template/scripts/tikv.go
Labels: size/L, status/LGT1, status/can-merge

#1291 Fix the issue that cluster can't start with TLS
  embed/templates/scripts/run_pd_scale.sh.tpl
  pkg/cluster/template/scripts/pd.go
Labels: size/XS, status/LGT1, status/can-merge

#1273 Fix the dir check logic on imported cluster
  components/dm/ansible/import.go
  components/dm/ansible/import_test.go
  pkg/cluster/manager/deploy.go
  pkg/cluster/spec/prometheus.go
  pkg/cluster/spec/validate.go
Labels: size/S, status/LGT1, status/can-merge

#1261 Fix the issue that binlog_enable not import from ansible
  pkg/cluster/ansible/import.go
  pkg/cluster/spec/server_config.go
  pkg/cluster/spec/tiflash.go
Labels: size/M, status/LGT1, status/can-merge

#1280 Revert "Fix tiflash not start with newest nightly PD (#902)"
  components/playground/instance/tiflash.go
  tests/tiup-playground/test_playground.sh
Labels: size/S, status/LGT1, status/can-merge

#1281 fix: workaround for nightly versions in checkConfig()
  pkg/cluster/spec/server_config.go
Labels: size/XS, status/LGT1, status/can-merge, type/bug-fix

#1294 Fix the issue the playground can't start when there is a nightly in and not in remote
  pkg/repository/v1_repository.go
Labels: size/XS, status/LGT1, status/can-merge, type/bug-fix

#1295 Bump v1.4.1
  CHANGELOG.md
  pkg/version/version.go
Labels: size/S, status/LGT1, status/can-merge

#1285 cluster: speed up start/enable monitor instances
  pkg/cluster/operation/action.go
  pkg/cluster/operation/destroy.go
  pkg/cluster/spec/pump.go
Labels: size/XL, status/LGT1, status/can-merge

#1289 ci: bump tidb versions in test scripts
  tests/tiup-cluster/run.sh
  tests/tiup-cluster/test_cmd.sh
  tests/tiup-cluster/test_cmd_tls_native_ssh.sh
  tests/tiup-cluster/test_scale_core.sh
  tests/tiup-cluster/test_scale_core_tls.sh
  tests/tiup-cluster/test_scale_tools.sh
  tests/tiup-cluster/test_scale_tools_tls.sh
  tests/tiup-cluster/test_upgrade.sh
  tests/tiup-cluster/test_upgrade_tls.sh
Labels: category/testing, size/M, status/LGT1, status/can-merge

#1298 Send 'Staring component...' output to stderr
  pkg/exec/run.go
Labels: category/usability, good first issue, size/XS, status/LGT1, status/can-merge, type/bug-fix

#1302 tiup: update `mirror` command
  cmd/mirror.go
  cmd/root.go
Labels: category/usability, size/M, status/LGT1, status/can-merge, type/bug-fix, type/enhancement

#1296 doc: Updated doc/dev/README.md with relative links
  doc/dev/README.md
Labels: category/document, good first issue, size/S, status/LGT1, status/can-merge

#1277 Added and tweaked the method of reporting makefile targets
  Makefile
  tests/Makefile
Labels: size/M, status/LGT1, status/can-merge

#1306 Fixed a variety of typos
  cmd/mirror.go
  pkg/environment/env.go
  pkg/repository/mirror.go
Labels: size/S, status/LGT1, status/can-merge

#1312 repository/progress: Format progress
  pkg/repository/clone_mirror.go
  pkg/repository/progress.go
Labels: size/XS, status/LGT1, status/can-merge

#1313 mirror clone: Improve handling of latest versions
  pkg/repository/clone_mirror.go
  pkg/utils/semver.go
Labels: size/S, status/LGT1, status/can-merge

#1317 mirror: add `tiup mirror show` command to print current mirror address
  cmd/mirror.go
Labels: size/S, status/LGT1, status/can-merge

#1316 Update feature-request.md
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: size/XS, status/LGT1, status/can-merge

#1318 playground: update version selection examples
  components/playground/playground.go
Labels: size/XS, status/LGT1, status/can-merge

#1303 repository: optimize error handing if root.json fails to load
  cmd/root.go
  pkg/repository/v1manifest/local_manifests.go
  pkg/repository/v1manifest/types.go
  pkg/repository/v1manifest/types_test.go
Labels: size/M, status/LGT1, status/can-merge

#1309 manager: check for global configs and prompt user for confirmation on…
  pkg/cluster/manager/scale_out.go
  pkg/cluster/spec/parse_topology.go
Labels: size/M, status/LGT1, status/can-merge, type/new-feature

#1321 Fix the issue that clone will add yanked component
  cmd/mirror.go
Labels: size/XS, status/LGT1, status/can-merge

#1322 Fix issue that advertise address not work with PD non-default ports
  pkg/cluster/manager/scale_out.go
  pkg/cluster/template/scripts/pd.go
Labels: size/S, status/LGT1, status/can-merge

#1323 playground: add --comments option to the mysql client connection tips
  components/playground/playground.go
Labels: component/playground, size/XS, status/LGT1, status/can-merge

#1325 playground: support semver constraint
  cmd/mirror.go
  components/playground/playground.go
  pkg/repository/v1_repository.go
  pkg/utils/regexp.go
  pkg/utils/regexp_test.go
  pkg/utils/semver.go
  pkg/utils/semver_test.go
  pkg/utils/utils.go
Labels: component/playground, size/XL, status/LGT1, status/can-merge

#1328 bump version 1.4.2
  CHANGELOG.md
  pkg/version/version.go
Labels: size/S, status/LGT1, status/can-merge

#1327 telemetry: fix tememetry data and update reported fields
  components/cluster/command/check.go
  components/cluster/command/clean.go
  components/cluster/command/deploy.go
  components/cluster/command/destroy.go
  components/cluster/command/disable.go
  components/cluster/command/display.go
  components/cluster/command/edit_config.go
  components/cluster/command/enable.go
  components/cluster/command/exec.go
  components/cluster/command/patch.go
  components/cluster/command/prune.go
  components/cluster/command/reload.go
  components/cluster/command/rename.go
  components/cluster/command/restart.go
  components/cluster/command/root.go
  components/cluster/command/scale_in.go
  components/cluster/command/scale_out.go
  components/cluster/command/start.go
  components/cluster/command/stop.go
  components/cluster/command/transfer.go
  components/cluster/command/upgrade.go
  pkg/cluster/flags/debug.go
  pkg/cluster/report/report.go
  pkg/cluster/spec/validate.go
  pkg/exec/run.go
  pkg/localdata/constant.go
  pkg/telemetry/generate.sh
  pkg/telemetry/meta.go
  pkg/telemetry/report.pb.go
  pkg/telemetry/report.proto
  pkg/telemetry/scrub.go
  pkg/telemetry/scrub_test.go
  pkg/telemetry/telemetry.go
  pkg/telemetry/telemetry_test.go
  pkg/telemetry/testdata/full.yaml
  pkg/telemetry/testdata/full.yaml.out
  pkg/telemetry/testdata/simple.yaml.out
  pkg/utils/http_client.go
  pkg/utils/rand/rand.go
  pkg/utils/regexp_test.go
Labels: component/cluster, component/tiup, size/XXL, status/LGT1, status/can-merge, type/enhancement

#1333 playgroud: support kv-only mode to start TiKV cluster only
  components/playground/main.go
  components/playground/playground.go
Labels: size/S, status/LGT1, status/can-merge
