Repository pingcap/tiup, pull requests merged in 2021-02, with the labels that each got.

#1096 Support upgrade/patch offline tidb/dm cluster
  components/cluster/command/patch.go
  components/cluster/command/upgrade.go
  components/dm/command/patch.go
  components/dm/command/upgrade.go
  pkg/cluster/manager/patch.go
  pkg/cluster/manager/upgrade.go
  tests/tiup-cluster/script/cmd_subtest.sh
Labels: size/M, status/LGT1, status/can-merge, status/need-doc

#1117 cluster: update binded version of insight collector
  pkg/cluster/spec/bindversion.go
Labels: size/XS, status/LGT1, status/can-merge

#1107 cluster: check permission for deploy/data dir for exist clusters
  components/cluster/command/check.go
  pkg/cluster/operation/check.go
  pkg/cluster/task/builder.go
  pkg/cluster/task/check.go
Labels: size/XL, status/LGT1, status/can-merge, type/enhancement, type/new-feature

#1123 Add darwin-arm64 not support hint for install.sh
  install.sh
  pkg/cluster/template/install/local_install.sh.go
Labels: first-time-contributor, size/S, status/LGT1, status/can-merge

#1116 Add --keys flag for server
  pkg/repository/mirror.go
  server/handler/component.go
  server/main.go
  server/server.go
Labels: size/S, status/LGT1, status/can-merge

#1121 Fix the issue that merge not work with official offline package
  pkg/repository/merge_mirror.go
Labels: size/XS, status/LGT1, status/can-merge

#1098 Add custom field in global options
  pkg/cluster/spec/spec.go
  pkg/cluster/spec/spec_test.go
Labels: size/M, status/LGT1, status/can-merge, status/need-doc

#1126 cluster: check region info for existing cluster
  components/cluster/command/check.go
  pkg/cluster/api/pdapi.go
Labels: category/stability, category/usability, size/M, status/LGT1, status/can-merge, type/new-feature

#1133 Change the playground info for connecting to TiDB
  components/playground/playground.go
Labels: size/XS, status/LGT1, status/can-merge

#1132 add default description
  pkg/cliutil/tui.go
Labels: first-time-contributor, size/XS, status/LGT1, status/can-merge

#1118 Feature/check network
  go.mod
  go.sum
  pkg/cluster/operation/check.go
Labels: size/L, status/LGT1, status/can-merge, status/need-doc

#1134 add PromptForConfirmYes default description"
  pkg/cliutil/tui.go
Labels: category/usability, size/XS, status/LGT1, status/can-merge, type/enhancement

#1130 *: update depends & CI jobs
  .github/workflows/integrate-cluster-cmd.yaml
  .github/workflows/integrate-cluster-scale.yaml
  .github/workflows/integrate-dm.yaml
  .github/workflows/integrate-playground.yaml
  .github/workflows/integrate-tiup.yaml
  .github/workflows/reprotest.yaml
  go.mod
  go.sum
  pkg/cliutil/tui.go
  pkg/cluster/api/dmapi.go
  pkg/repository/progress.go
  tests/tiup-playground/test_playground.sh
Labels: category/testing, size/XXL, type/enhancement

#1137 Fix the issue that download retry may timeout without retry
  pkg/repository/mirror.go
Labels: size/XS, status/LGT1, status/can-merge

#1070 Feature/sp prometheus remote rw
  pkg/cluster/embed/autogen_pkger.go
  pkg/cluster/spec/prometheus.go
  pkg/cluster/spec/server_config.go
  pkg/cluster/spec/server_config_test.go
  pkg/cluster/template/config/prometheus.go
  templates/config/prometheus.yml.tpl
Labels: category/monitoring, first-time-contributor, size/M, status/LGT1, status/can-merge

#1139 Refine cluster list and display commands
  pkg/cluster/manager/display.go
  pkg/cluster/manager/list.go
Labels: size/L, status/LGT1, status/can-merge

#1144 cluster: updateTopology maybe hang forever
  pkg/cluster/task/update_topology.go
  tests/tiup-cluster/script/cmd_subtest.sh
Labels: size/S, status/LGT1, status/can-merge

#1142 playground: set grafana topology in pd
  components/playground/instance/drainer.go
  components/playground/instance/instance.go
  components/playground/instance/pd.go
  components/playground/instance/pump.go
  components/playground/instance/ticdc.go
  components/playground/instance/tidb.go
  components/playground/instance/tiflash.go
  components/playground/instance/tikv.go
  components/playground/playground.go
Labels: size/M, status/LGT1, status/can-merge

#1145 tiup: install --force to reinstall
  cmd/install.go
Labels: size/XS, status/LGT1, status/can-merge

#1124 fix(cluster/operation): extract the correct java's version field
  pkg/cluster/operation/check.go
Labels: size/S, status/LGT1, status/can-merge, status/need-info

#1129 Bind newest stable non-core components
  components/dm/spec/bindversion.go
  pkg/cluster/embed/autogen_pkger.go
  pkg/cluster/spec/bindversion.go
  pkg/cluster/spec/prometheus.go
  templates/config/prometheus.yml.tpl
Labels: size/M, status/LGT1, status/can-merge

#1128 Fix the issue that the default selected version may be a preprelease version
  cmd/list.go
  cmd/uninstall.go
  go.mod
  pkg/environment/env.go
  pkg/exec/run.go
  pkg/localdata/profile.go
  pkg/repository/clone_mirror.go
  pkg/repository/merge_mirror.go
  pkg/repository/v1_repository.go
  pkg/repository/v1_repository_test.go
Labels: size/XL, status/LGT1, status/can-merge

#1152 playground: use the advertised host instead of 0.0.0.0
  components/playground/playground.go
Labels: size/XS, status/LGT1, status/can-merge

#1149 Support external alertmanager target
  pkg/cluster/ansible/test-data/meta.yaml
  pkg/cluster/spec/prometheus.go
Labels: category/usability, size/M, status/LGT1, status/can-merge, type/new-feature

#1125 cluster: mark patched nodes in display
  components/cluster/command/test.go
  components/dm/ansible/import.go
  components/dm/ansible/import_test.go
  components/dm/spec/logic.go
  components/dm/spec/topology_dm.go
  components/dm/spec/topology_dm_test.go
  components/dm/task/update_dm_meta.go
  pkg/cluster/ansible/import.go
  pkg/cluster/ansible/inventory.go
  pkg/cluster/ansible/service.go
  pkg/cluster/manager/display.go
  pkg/cluster/manager/manager.go
  pkg/cluster/manager/patch.go
  pkg/cluster/manager/scale_out.go
  pkg/cluster/manager/transfer.go
  pkg/cluster/manager/transfer_test.go
  pkg/cluster/manager/upgrade.go
  pkg/cluster/operation/destroy.go
  pkg/cluster/spec/alertmanager.go
  pkg/cluster/spec/cdc.go
  pkg/cluster/spec/drainer.go
  pkg/cluster/spec/grafana.go
  pkg/cluster/spec/grafana_test.go
  pkg/cluster/spec/instance.go
  pkg/cluster/spec/parse_topology.go
  pkg/cluster/spec/parse_topology_test.go
  pkg/cluster/spec/pd.go
  pkg/cluster/spec/prometheus.go
  pkg/cluster/spec/prometheus_test.go
  pkg/cluster/spec/pump.go
  pkg/cluster/spec/spec.go
  pkg/cluster/spec/spec_test.go
  pkg/cluster/spec/tidb.go
  pkg/cluster/spec/tiflash.go
  pkg/cluster/spec/tikv.go
  pkg/cluster/spec/tispark.go
  pkg/cluster/spec/validate.go
  pkg/cluster/task/update_meta.go
  tests/tiup-cluster/script/cmd_subtest.sh
Labels: category/usability, size/XXL, status/LGT1, status/can-merge, type/new-feature

#1155 Update the correspondence between component default port and dir
  examples/topology.example.yaml
Labels: first-time-contributor, size/S, status/LGT1, status/can-merge

#1156 Support template command
  components/cluster/command/root.go
  components/cluster/command/template.go
  components/dm/command/root.go
  components/dm/command/template.go
  embed/templates/examples/dm/minimal.yaml
  embed/templates/examples/dm/topology.example.yaml
  embed/templates/examples/minimal.yaml
  embed/templates/examples/multi-dc.yaml
  embed/templates/examples/topology.example.yaml
  examples
Labels: size/L, status/LGT1, status/can-merge, status/need-doc

#1157 Support replay command to enhance checkpoint
  components/cluster/command/replay.go
  components/cluster/command/root.go
  components/dm/command/replay.go
  components/dm/command/root.go
  pkg/checkpoint/checkpoint.go
  pkg/checkpoint/checkpoint_test.go
  pkg/cluster/audit/audit.go
  pkg/cluster/operation/operation.go
  pkg/logger/audit.go
  tests/tiup-cluster/script/cmd_subtest.sh
Labels: size/L, status/LGT1

#1158 ci: use github actions to publish new tiup releases
  .github/workflows/install.yaml
  .github/workflows/integrate-cluster-cmd.yaml
  .github/workflows/integrate-cluster-scale.yaml
  .github/workflows/integrate-dm.yaml
  .github/workflows/integrate-playground.yaml
  .github/workflows/integrate-tiup.yaml
  .github/workflows/release-tiup.yaml
  .github/workflows/reprotest.yaml
  Makefile
  cmd/mirror.go
  cmd/root.go
  components/playground/main.go
  install.sh
  pkg/repository/mirror.go
  pkg/version/version.go
  server/main.go
Labels: size/XL, status/LGT1, status/can-merge
