Repository pingcap/tiup, pull requests merged in 2021-11, with the labels that each got.

#1596 support rendering template when set "--local" option
  components/cluster/command/template.go
  components/cluster/command/template_test.go
  components/dm/command/template.go
  components/dm/command/template_test.go
  embed/examples/cluster/local.tpl
  embed/examples/cluster/local.yaml
  embed/examples/dm/local.tpl
Labels: type/new-feature, status/can-merge, category/usability, status/LGT1, size/XXL, good first issue, component/cluster

#1606 remove tag warnning
  cmd/root.go
Labels: status/can-merge, status/LGT1, size/XS

#1608 add --external-url for alertmanager
  embed/templates/scripts/run_alertmanager.sh.tpl
Labels: status/can-merge, status/LGT1, size/XS, good first issue

#1612 cluster: fix mistake error about TLS
  pkg/cluster/manager/deploy.go
  pkg/cluster/manager/scale_out.go
Labels: status/can-merge, status/LGT1, size/XS

#1610 cluster: fix wrong keys detecting host arch
  pkg/cluster/manager/manager.go
Labels: status/can-merge, status/LGT1, size/XS

#1601 cluster: add ng-monitoring support
  embed/templates/config/ngmonitoring.toml.tpl
  embed/templates/scripts/run_prometheus.sh.tpl
  pkg/cluster/spec/monitoring.go
  pkg/cluster/spec/monitoring_test.go
  pkg/cluster/spec/validate.go
  pkg/cluster/spec/validate_test.go
  pkg/cluster/template/config/ngmonitoring.go
  pkg/cluster/template/scripts/monitoring.go
  pkg/cluster/template/scripts/monitoring_test.go
Labels: status/can-merge, status/LGT1, size/L

#1618 cluster: update error message of tiflash not ready
  pkg/cluster/spec/tiflash.go
Labels: status/can-merge, status/LGT1, size/XS

#1617 cluster: implement pure JSON output mode (experimental)
  components/cluster/command/deploy.go
  components/cluster/command/display.go
  components/cluster/command/root.go
  components/cluster/command/scale_out.go
  components/dm/command/deploy.go
  components/dm/command/root.go
  components/dm/command/scale_out.go
  pkg/cluster/ansible/config.go
  pkg/cluster/audit/audit.go
  pkg/cluster/manager/builder.go
  pkg/cluster/manager/check.go
  pkg/cluster/manager/deploy.go
  pkg/cluster/manager/destroy.go
  pkg/cluster/manager/display.go
  pkg/cluster/manager/exec.go
  pkg/cluster/manager/list.go
  pkg/cluster/manager/manager.go
  pkg/cluster/manager/patch.go
  pkg/cluster/manager/reload.go
  pkg/cluster/manager/scale_in.go
  pkg/cluster/manager/scale_out.go
  pkg/cluster/manager/transfer.go
  pkg/cluster/manager/upgrade.go
  pkg/cluster/operation/operation.go
  pkg/cluster/task/builder.go
  pkg/cluster/task/step.go
  pkg/logger/log/log.go
  pkg/tui/progress/display_props.go
Labels: type/new-feature, status/can-merge, status/LGT1, size/XXL, component/cluster, component/dm

#1619 bump version 1.7.0
  CHANGELOG.md
  pkg/version/version.go
Labels: status/can-merge, status/LGT1, size/S

#1624 cluster: fix progressBar return nil
  pkg/cluster/task/step.go
Labels: status/can-merge, status/LGT1, size/XS

#1623 cluster: add compress option to scp
  components/cluster/command/transfer.go
  components/dm/ansible/import.go
  components/dm/ansible/import_test.go
  components/dm/spec/logic.go
  pkg/cluster/ansible/config.go
  pkg/cluster/ctxt/context.go
  pkg/cluster/executor/checkpoint.go
  pkg/cluster/executor/local.go
  pkg/cluster/executor/local_test.go
  pkg/cluster/executor/scp.go
  pkg/cluster/executor/ssh.go
  pkg/cluster/manager/transfer.go
  pkg/cluster/operation/telemetry.go
  pkg/cluster/spec/alertmanager.go
  pkg/cluster/spec/cdc.go
  pkg/cluster/spec/drainer.go
  pkg/cluster/spec/grafana.go
  pkg/cluster/spec/instance.go
  pkg/cluster/spec/monitoring.go
  pkg/cluster/spec/pd.go
  pkg/cluster/spec/pump.go
  pkg/cluster/spec/tidb.go
  pkg/cluster/spec/tiflash.go
  pkg/cluster/spec/tikv.go
  pkg/cluster/spec/tispark.go
  pkg/cluster/task/builder.go
  pkg/cluster/task/copy_file.go
  pkg/cluster/task/init_config_test.go
  pkg/cluster/task/install_package.go
  pkg/cluster/task/monitored_config.go
  pkg/cluster/task/tls.go
Labels: status/can-merge, status/LGT1, size/L

#1629 cluster: add significant warning when `--force` is set for scale-in
  pkg/cluster/manager/scale_in.go
  pkg/tui/tui.go
Labels: status/can-merge, status/LGT1, size/M

#1631 playground: add data-dir to ticdc
  components/playground/instance/ticdc.go
Labels: status/can-merge, status/LGT1, size/S

#1627 cluster: add envs to skip topology sanity check in scale-in process
  pkg/cluster/operation/destroy.go
  pkg/cluster/operation/operation.go
  pkg/cluster/operation/scale_in.go
  pkg/cluster/operation/upgrade.go
Labels: status/can-merge, status/LGT1, size/L

#1635 playground: fix wrong flag name
  components/playground/main.go
Labels: status/can-merge, status/LGT1, size/XS, component/playground

#1638 cluster: Scale-out action can be divided into 2
  components/cluster/command/scale_out.go
  pkg/cluster/manager/basic.go
  pkg/cluster/manager/builder.go
  pkg/cluster/manager/deploy.go
  pkg/cluster/manager/patch.go
  pkg/cluster/manager/reload.go
  pkg/cluster/manager/scale_in.go
  pkg/cluster/manager/scale_out.go
  pkg/cluster/manager/upgrade.go
  pkg/cluster/spec/spec_manager.go
Labels: status/can-merge, status/LGT1, size/XL

#1643 cluster: clean operations cannot cleanup monitor component files
  pkg/cluster/manager/basic.go
  pkg/cluster/manager/cleanup.go
Labels: status/can-merge, status/LGT1, size/L

#1639 Adjust for deprecation of `--monitor`
  components/playground/main.go
  doc/user/playground.md
Labels: status/can-merge, status/LGT1, size/M
