Repository pingcap/tiup, pull requests merged in 2021-12, with the labels that each got.

#1646 *: implement plain text output and custom output writer
  pkg/cluster/task/step.go
  pkg/logger/log/log.go
  pkg/logger/log/verbose.go
  pkg/tui/progress/display_props.go
Labels: status/can-merge, status/LGT1, size/M

#1644 cluster: need support clean up audit log
  components/cluster/command/clean.go
  pkg/cluster/manager/cleanup.go
  pkg/cluster/operation/operation.go
Labels: status/can-merge, status/LGT1, size/L

#1645 cluster: fix can't skip confirmation of scale-out
  pkg/cluster/manager/scale_out.go
Labels: status/can-merge, status/LGT1, size/M

#1649 cluster: skip dir conflict if node marked ignore_exporter
  pkg/cluster/spec/validate.go
  pkg/cluster/spec/validate_test.go
Labels: status/can-merge, status/LGT1, size/S

#1648 playground: add support of ng-monitoring
  components/playground/ngmonitoring.go
  components/playground/playground.go
Labels: status/can-merge, status/LGT1, size/L

#1641 cluster: add additional prom scrape_configs
  pkg/cluster/spec/monitoring.go
  pkg/cluster/spec/monitoring_test.go
Labels: status/can-merge, status/LGT1, size/L

#1654 dm: add dm hosts to node_exporter list
  pkg/cluster/spec/monitoring.go
Labels: status/can-merge, status/LGT1, size/XS

#1652 bump version 1.8.0
  CHANGELOG.md
  pkg/version/version.go
Labels: status/can-merge, status/LGT1, size/M

#1656 cluster: No port conflicts were detected during scale-out of the cluster imported from ansible
  pkg/cluster/spec/validate.go
Labels: status/can-merge, status/LGT1, size/XS

#1664 *: fix slow ssh connect when using buildin ssh
  go.mod
  go.sum
Labels: status/can-merge, status/LGT1, size/XS

#1665 cluster: support alertmanager configuration Listen Host
  embed/templates/scripts/run_alertmanager.sh.tpl
  pkg/cluster/spec/alertmanager.go
  pkg/cluster/spec/spec.go
  pkg/cluster/template/scripts/alertmanager.go
Labels: status/can-merge, status/LGT1, size/S

#1663 cluster: check add CPU frequency check output
  pkg/cluster/operation/check.go
Labels: status/can-merge, status/LGT1, size/S

#1669 cluster: add configuration rendering for web listen-address
  embed/examples/cluster/topology.example.yaml
  embed/templates/scripts/run_alertmanager.sh.tpl
Labels: status/can-merge, status/LGT1, size/XS, component/cluster

#1672 ci: run integrate tests daily to update codecov stats
  .codecov.yml
  .github/workflows/integrate-cluster-cmd.yaml
  .github/workflows/integrate-cluster-scale.yaml
  .github/workflows/integrate-dm.yaml
  .github/workflows/integrate-playground.yaml
  .github/workflows/integrate-tiup.yaml
  .github/workflows/release-tiup.yaml
  tests/tiup-cluster/test_scale_core_tls.sh
  tests/tiup-cluster/test_scale_tools_tls.sh
  tests/tiup-cluster/test_upgrade_tls.sh
Labels: status/can-merge, status/LGT1, size/M

#1673 Remove the config 'runAsDaemon' from tiflash.toml
  components/playground/instance/tiflash.go
  components/playground/instance/tiflash_config.go
  pkg/cluster/ansible/service_test.go
  pkg/cluster/spec/tiflash.go
Labels: status/can-merge, status/LGT1, size/M

#1676 tiup/mirror: add ability to change owner of a component
  cmd/mirror.go
  pkg/repository/model/model.go
  pkg/repository/model/publish.go
  server/rotate/component.go
  server/rotate/root.go
  server/rotate/server.go
Labels: status/can-merge, status/LGT1, size/XL, component/tiup

#1678 cluster: fix wrong default initial-commit-ts in drainer
  embed/templates/scripts/run_drainer.sh.tpl
  pkg/cluster/spec/drainer.go
Labels: status/can-merge, status/LGT1, size/XS

#1683 bump version 1.8.1
  CHANGELOG.md
  pkg/version/version.go
Labels: status/can-merge, status/LGT1, size/S

#1674 cluster: render cluster name when monitoring_servers.rule_dir is set
  pkg/cluster/spec/monitoring.go
  pkg/cluster/spec/monitoring_test.go
Labels: status/can-merge, status/LGT1, size/S

#1687 *: add initial support for auto-completion for components
  cmd/root.go
Labels: status/can-merge, status/LGT1, size/M

#1657 cluster: support enable or disable TLS for an exiting cluster
  components/cluster/command/root.go
  components/cluster/command/tls.go
  components/dm/spec/logic.go
  pkg/cluster/manager/builder.go
  pkg/cluster/manager/cacert.go
  pkg/cluster/manager/cleanup.go
  pkg/cluster/manager/deploy.go
  pkg/cluster/manager/destroy.go
  pkg/cluster/manager/reload.go
  pkg/cluster/manager/scale_in.go
  pkg/cluster/manager/tls.go
  pkg/cluster/operation/destroy.go
  pkg/cluster/operation/operation.go
  pkg/cluster/operation/pd_member.go
  pkg/cluster/spec/alertmanager.go
  pkg/cluster/spec/cdc.go
  pkg/cluster/spec/drainer.go
  pkg/cluster/spec/grafana.go
  pkg/cluster/spec/instance.go
  pkg/cluster/spec/monitoring.go
  pkg/cluster/spec/pd.go
  pkg/cluster/spec/profile.go
  pkg/cluster/spec/pump.go
  pkg/cluster/spec/spec.go
  pkg/cluster/spec/spec_test.go
  pkg/cluster/spec/tidb.go
  pkg/cluster/spec/tiflash.go
  pkg/cluster/spec/tikv.go
  pkg/cluster/spec/tispark.go
  pkg/cluster/task/builder.go
  pkg/cluster/task/tls.go
Labels: status/can-merge, status/LGT1, size/XXL

#1694 cluster: perfect the tips of TLS sub commands
  pkg/cluster/manager/tls.go
Labels: status/can-merge, status/LGT1, size/S

#1692 dm: add new config to dm template
  embed/examples/dm/topology.example.yaml
Labels: status/can-merge, status/LGT1, size/XS

#1698 resolve flag conflicts between tiup and component
  cmd/root.go
Labels: status/can-merge, status/LGT1, size/S

#1695 TiUP: `update --self` add some checks.
  cmd/update.go
Labels: status/can-merge, status/LGT1, size/S

#1700 cluster: support init root password
  components/bench/Makefile
  components/client/Makefile
  components/cluster/command/start.go
  components/cluster/command/test.go
  embed/templates/scripts/run_tidb.sh.tpl
  examples
  go.mod
  go.sum
  pkg/cluster/spec/tidb.go
  pkg/cluster/template/scripts/tidb.go
  pkg/crypto/rand/passwd.go
  pkg/crypto/rand/passwd_test.go
Labels: status/can-merge, status/LGT1, size/L

#1659 cluster: check support check before scale-out the instance
  components/cluster/command/check.go
  pkg/cluster/manager/check.go
  pkg/cluster/manager/scale_out.go
  pkg/cluster/operation/check.go
  pkg/cluster/task/check.go
Labels: status/can-merge, status/LGT1, size/L
