Repository pingcap/tiup, pull requests merged in 2021-07, with the labels that each got.

#1462 tests/cluster: trap bash exit
  tests/tiup-cluster/script/cmd_subtest.sh
  tests/tiup-cluster/script/scale_core.sh
  tests/tiup-cluster/script/scale_tools.sh
  tests/tiup-cluster/script/upgrade.sh
  tests/tiup-cluster/script/util.sh
  tests/tiup-cluster/test_cmd.sh
  tests/tiup-cluster/test_scale_core.sh
  tests/tiup-cluster/test_scale_core_tls.sh
  tests/tiup-cluster/test_scale_tools.sh
  tests/tiup-cluster/test_scale_tools_tls.sh
  tests/tiup-cluster/test_upgrade.sh
  tests/tiup-cluster/test_upgrade_tls.sh
  tests/tiup-dm/script/util.sh
Labels: category/testing, size/L, status/LGT1, status/can-merge

#1463 cluster/prometheus: tikv accelerate rules if version 3
  .github/workflows/integrate-cluster-cmd.yaml
  embed/templates/config/prometheus.yml.tpl
  pkg/cluster/spec/prometheus.go
  pkg/cluster/template/config/prometheus.go
Labels: category/monitoring, component/cluster, size/S, status/LGT1, status/can-merge

#1464 clone_mirror: refuse to clone from self
  pkg/repository/clone_mirror.go
Labels: size/XS, status/LGT1, status/can-merge

#1466 Update manifest errors in list component should not be returned, change to warning
  cmd/list.go
Labels: component/tiup, size/XS, status/LGT1

#1473 Fix unit test
  pkg/repository/testdata/polluted/manifests/tidb.json
Labels: size/XS, status/LGT1, status/can-merge

#1469 cluster/ssh: don't quote ssh options
  pkg/cluster/executor/ssh.go
  pkg/cluster/executor/ssh_test.go
Labels: size/S, status/LGT1, status/can-merge

#1471 Fix TiKV config check false alarm when data_dir is depended on
  pkg/cluster/spec/server_config.go
Labels: size/XS, status/LGT1, status/can-merge

#1468 proxy: use DialContext instead of Dial
  pkg/proxy/http_proxy.go
Labels: size/S, status/LGT1, status/can-merge

#1484 docs: update topology.example.yaml
  embed/templates/examples/topology.example.yaml
Labels: size/XS, status/LGT1, status/can-merge

#1476 cluster: adjust error message of selinux check
  pkg/cluster/operation/check.go
Labels: size/S, status/LGT1, status/can-merge

#1477 cluster: print more clear warning when scale in with `--force`
  pkg/cluster/manager/scale_in.go
Labels: size/S, status/LGT1, status/can-merge

#1479 tiup: implement renew subcommand to extend expiration date of compone…
  cmd/mirror.go
  pkg/repository/v1_repository.go
  pkg/repository/v1manifest/manifest.go
Labels: component/tiup, size/M, status/LGT1, status/can-merge

#1487 bump version 1.5.3
  CHANGELOG.md
  pkg/version/version.go
Labels: size/S, status/LGT1, status/can-merge

#1495 playground: ignore version check error in some cases
  components/playground/main.go
  components/playground/playground.go
  pkg/repository/v1_repository.go
Labels: component/playground, size/M, status/LGT1

#1491 cluster: distinguish cookie names of multiple grafana instances
  embed/templates/config/grafana.ini.tpl
Labels: component/cluster, size/XS, status/LGT1, status/can-merge

#1494 cluster: allow editing of lernel_config in tiflash
  pkg/cluster/spec/tiflash.go
Labels: component/cluster, size/XS, status/LGT1, status/can-merge

#1497 *: Create SECURITY.md
  SECURITY.md
Labels: size/M, status/LGT1, status/can-merge
