Repository pingcap/tiup, pull requests merged in 2021-09, with the labels that each got.

#1542 cluster: upgrade tikv first then cdc
  pkg/cluster/spec/spec.go
Labels: status/can-merge, status/LGT1, size/XS

#1543 bump version 1.5.6
  CHANGELOG.md
  pkg/version/version.go
Labels: status/can-merge, status/LGT1, size/S

#1539 remove network request before enter component
  pkg/environment/env.go
  pkg/exec/run.go
  pkg/repository/v1_repository.go
Labels: status/can-merge, status/LGT1, size/L

#1544 *: update depends
  .github/workflows/install.yaml
  .github/workflows/integrate-cluster-cmd.yaml
  .github/workflows/integrate-cluster-scale.yaml
  .github/workflows/integrate-dm.yaml
  .github/workflows/integrate-playground.yaml
  .github/workflows/integrate-tiup.yaml
  .github/workflows/release-tiup.yaml
  .github/workflows/reprotest.yaml
  components/bench/go.mod
  components/bench/go.sum
  components/client/go.mod
  components/client/go.sum
  docker/control/Dockerfile
  docker/node/Dockerfile
  go.mod
  go.sum
Labels: status/can-merge, status/LGT1, size/XXL

#1545 fix binpath not work
  components/playground/main.go
  pkg/exec/run.go
Labels: status/can-merge, status/LGT1, size/M

#1549 use cobra default auto completion
  cmd/completion.go
  cmd/root.go
Labels: status/can-merge, status/LGT1, size/L

#1551 use stdout on update and verbose information
  pkg/exec/run.go
  pkg/logger/log/verbose.go
Labels: status/can-merge, status/LGT1, size/S

#1552 cluster: add `--force` argument for `prune` subcommand
  components/cluster/command/prune.go
  pkg/cluster/operation/destroy.go
Labels: status/can-merge, status/LGT1, size/XS

#1553 support start playground offline when specify version
  cmd/list.go
  pkg/repository/v1_repository.go
Labels: status/can-merge, status/LGT1, size/M

#1554 update root.json only when necessary
  pkg/repository/v1_repository.go
  pkg/repository/v1manifest/key_store.go
Labels: status/can-merge, status/LGT1, size/M

#1556 remove TIUP_WORK_DIR
  cmd/help.go
  components/cluster/command/root.go
  components/ctl/main.go
  components/dm/command/root.go
  components/playground/main.go
  components/playground/playground_test.go
  pkg/exec/run.go
  pkg/localdata/constant.go
  pkg/tui/cliutil.go
  server/package/package.go
Labels: status/can-merge, status/LGT1, size/M, component/tiup

#1557 fix panic when cant openDB on tiup-bench
  components/bench/main.go
  components/bench/tpcc.go
  components/bench/tpch.go
Labels: status/can-merge, status/LGT1, size/S, component/bench

#1561 Fix darwin build
  Makefile
  go.mod
  go.sum
Labels: status/can-merge, status/LGT1, size/L

#1560 send component environment messages to stderr
  pkg/environment/env.go
Labels: status/can-merge, status/LGT1, size/XS

#1558 support run playground without TiUP
  cmd/root.go
  components/playground/env.go
  components/playground/main.go
  pkg/exec/run.go
  pkg/localdata/constant.go
Labels: status/can-merge, status/LGT1, size/M

#1562 [tiup] add remove dir when fail to install
  pkg/repository/v1_repository.go
Labels: status/can-merge, status/LGT1, size/XS

#1565 Fix the issue that lost numa_node when generating PD config
  pkg/cluster/spec/pd.go
Labels: status/can-merge, status/LGT1, first-time-contributor, size/XS, good first issue

#1566 pkg/cluster/spec: add supported configuration for grafana
  embed/templates/config/grafana.ini.tpl
  pkg/cluster/spec/grafana.go
  pkg/cluster/template/config/grafana.go
Labels: status/can-merge, status/LGT1, first-time-contributor, size/M, category/monitoring, component/cluster
