Repository pingcap/tiup, pull requests merged in 2021-03, with the labels that each got.

#1167 Fix check-lint.sh can't run on macOS
  tools/check/check-lint.sh
Labels: category/testing, size/XS, status/LGT1, status/can-merge, type/bug-fix

#1163 Check tarball checksum on tiup-server
  cmd/mirror.go
  pkg/repository/model/error.go
  pkg/repository/model/model.go
  pkg/repository/v1_repository.go
  pkg/repository/v1_repository_test.go
  server/handler/component.go
Labels: size/M, status/LGT1, status/can-merge

#1170 *: optimize checksum mismatch error
  pkg/cluster/clusterutil/cluster.go
  pkg/cluster/operation/download.go
  pkg/repository/v1_repository.go
  pkg/repository/v1_repository_test.go
  pkg/utils/sha.go
Labels: category/usability, size/M, status/LGT1, status/can-merge, type/enhancement

#1161 cluster: increase schedule limit during upgrade of tikv
  pkg/cluster/api/pdapi.go
  pkg/cluster/operation/upgrade.go
Labels: size/L, status/LGT1, status/can-merge, type/enhancement

#1174 mirror: retry publish if tarball is not valid
  cmd/mirror.go
  pkg/cluster/operation/upgrade.go
  server/handler/component.go
Labels: category/stability, size/XS, status/LGT1, status/can-merge, type/enhancement

#1175 Fix the issue that the error message is confused when the patched tar…
  pkg/cluster/manager/patch.go
Labels: size/XS, status/LGT1, status/can-merge

#1177 cluster: validate cluster name for all cluster ops
  pkg/cluster/manager/cleanup.go
  pkg/cluster/manager/destroy.go
  pkg/cluster/manager/display.go
  pkg/cluster/manager/edit_config.go
  pkg/cluster/manager/exec.go
  pkg/cluster/manager/patch.go
  pkg/cluster/manager/reload.go
  pkg/cluster/manager/rename.go
  pkg/cluster/manager/scale_in.go
  pkg/cluster/manager/scale_out.go
  pkg/cluster/manager/transfer.go
  pkg/cluster/manager/upgrade.go
Labels: category/stability, size/M, status/LGT1, status/can-merge, type/bug-fix

#1182 Bump v1.3.3
  CHANGELOG.md
  pkg/version/version.go
Labels: size/S, status/LGT1, status/can-merge

#1185 Fix the issue that can't gernerate prometheus config
  cmd/mirror.go
  components/playground/instance/proc_attr_default.go
  components/playground/instance/proc_attr_linux.go
  go.sum
  pkg/cluster/embed/autogen_pkger.go
  pkg/cluster/embed/pkged.go
  pkg/environment/env.go
  pkg/repository/clone_mirror.go
  templates/config/prometheus.yml.tpl
Labels: category/stability, size/M, status/LGT1, type/bug-fix

#1189 Bump v1.3.4
  CHANGELOG.md
  pkg/version/version.go
Labels: size/XS, status/LGT1, status/can-merge

#1183 cluster: check config before reload
  pkg/cluster/manager/builder.go
  pkg/cluster/manager/destroy.go
  pkg/cluster/manager/reload.go
  pkg/cluster/manager/scale_in.go
Labels: size/S, status/LGT1, status/can-merge

#1191 Fix the issue that tiup may choose yanked version if it's already installed
  cmd/help.go
  pkg/environment/env.go
  pkg/localdata/profile.go
Labels: size/L, status/LGT1, status/can-merge

#1192 ci: not running CI jobs if no code has been changed
  .github/workflows/install.yaml
  .github/workflows/integrate-cluster-cmd.yaml
  .github/workflows/integrate-cluster-scale.yaml
  .github/workflows/integrate-dm.yaml
  .github/workflows/integrate-playground.yaml
  .github/workflows/integrate-tiup.yaml
  .github/workflows/release-tiup.yaml
  .github/workflows/reprotest.yaml
Labels: category/testing, size/L, status/LGT1, status/can-merge, type/enhancement

#1193 Change changelog
  CHANGELOG.md
Labels: size/XS, status/LGT1

#1194 Fix help command does not display template
  components/cluster/command/template.go
  components/dm/command/template.go
Labels: size/XS, status/LGT1, status/can-merge

#1195 Fix the issue that replay command will transfer .service file
  components/cluster/command/template.go
  components/cluster/command/test.go
  components/dm/command/template.go
  components/playground/instance/proc_attr_default.go
  components/playground/instance/proc_attr_linux.go
  doc/design/checkpoint.md
  pkg/checkpoint/checkpoint.go
  pkg/checkpoint/checkpoint_test.go
  pkg/checkpoint/field.go
  pkg/cluster/executor/checkpoint.go
  pkg/cluster/operation/upgrade.go
  pkg/cluster/spec/instance.go
  pkg/cluster/spec/tispark.go
  pkg/cluster/task/monitored_config.go
Labels: size/XL, status/LGT1, status/can-merge

#1197 ci: try to reduce CI jobs for different components
  .github/workflows/install.yaml
  .github/workflows/integrate-cluster-cmd.yaml
  .github/workflows/integrate-cluster-scale.yaml
  .github/workflows/integrate-dm.yaml
  .github/workflows/integrate-playground.yaml
  .github/workflows/integrate-tiup.yaml
Labels: category/testing, size/L, status/LGT1, status/can-merge

#1198 Fix the issue that old nighlty may cause error
  pkg/environment/env.go
  pkg/repository/v1_repository.go
Labels: size/S, status/LGT1, status/can-merge, type/bug-fix

#1201 mirror: clone in concurrent jobs
  cmd/mirror.go
  pkg/repository/clone_mirror.go
Labels: size/M, status/LGT1, status/can-merge

#1200 *: remove direct depends of dm and pd
  .codecov.yml
  go.mod
  go.sum
  pkg/cluster/api/dmapi.go
  pkg/cluster/api/dmpb/README.md
  pkg/cluster/api/dmpb/dmmaster.pb.go
  pkg/cluster/api/dmpb/dmmaster.pb.gw.go
  pkg/cluster/api/dmpb/dmworker.pb.go
  pkg/cluster/api/pdapi.go
  pkg/cluster/api/types.go
  pkg/cluster/api/typeutil/README.md
  pkg/cluster/api/typeutil/duration.go
  pkg/cluster/api/typeutil/duration_test.go
  pkg/cluster/api/typeutil/size.go
  pkg/cluster/api/typeutil/size_test.go
  pkg/cluster/api/typeutil/string_slice.go
  pkg/cluster/api/typeutil/string_slice_test.go
  pkg/utils/diff.go
Labels: size/XXL, status/LGT1, status/can-merge, type/enhancement

#1202 ci: retry publish on checksum validation failure
  .github/workflows/integrate-cluster-cmd.yaml
  .github/workflows/integrate-cluster-scale.yaml
  .github/workflows/integrate-dm.yaml
  .github/workflows/integrate-playground.yaml
  cmd/mirror.go
  pkg/repository/v1_repository.go
  pkg/utils/error.go
  pkg/utils/error_test.go
  pkg/utils/sha.go
Labels: size/L, status/LGT1, status/can-merge, type/bug-fix

#1206 Bump v1.3.5
  CHANGELOG.md
  pkg/version/version.go
Labels: size/XS, status/LGT1, status/can-merge

#1196 grafana: fix lightning's name not changed when cluster renamed
  pkg/cluster/api/binlog.go
  pkg/cluster/manager/display.go
  pkg/cluster/spec/grafana.go
  pkg/cluster/spec/validate.go
Labels: category/monitoring, size/S, status/LGT1, status/can-merge

#1207 cluster&dm/display: add an option to only show cluster version
  components/cluster/command/display.go
  components/dm/command/display.go
Labels: category/usability, size/S, status/LGT1, status/can-merge, type/enhancement

#1210 Add TIUP_USER_INPUT_VERSION to support components that must have a specified version
  components/ctl/main.go
  pkg/exec/run.go
  pkg/localdata/constant.go
Labels: size/S, status/LGT1, status/can-merge

#1178 Update minimal.yaml
  embed/templates/examples/minimal.yaml
Labels: category/document, size/L, status/LGT1, status/can-merge, type/enhancement

#1179 Update topology.example.yaml
  embed/templates/examples/topology.example.yaml
Labels: category/document, size/XXL, status/LGT1, status/can-merge, type/enhancement

#1180 Update multi-dc.yaml
  embed/templates/examples/multi-dc.yaml
Labels: category/document, size/XL, status/LGT1, status/can-merge, type/enhancement

#1213 Support Apple Silicon
  Makefile
  cmd/mirror.go
  components/bench/main.go
  components/bench/tpcc.go
  components/cluster/command/check.go
  components/dm/spec/cluster.go
  components/playground/grafana.go
  install.sh
  pkg/cluster/ansible/config.go
  pkg/cluster/ansible/inventory.go
  pkg/cluster/api/pdapi.go
  pkg/cluster/audit/audit.go
  pkg/cluster/manager/transfer_test.go
  pkg/cluster/module/user.go
  pkg/cluster/operation/check.go
  pkg/cluster/operation/upgrade.go
  pkg/cluster/spec/util.go
  pkg/cluster/task/builder.go
  pkg/cluster/template/config/grafana.go
  pkg/crypto/ca_test.go
  pkg/repository/merge_mirror_test.go
Labels: first-time-contributor, size/M, status/LGT1, status/can-merge

#1216 *: refine the utils & version package to avoid confusing
  .github/workflows/install.yaml
  .github/workflows/integrate-cluster-cmd.yaml
  .github/workflows/integrate-cluster-scale.yaml
  .github/workflows/integrate-dm.yaml
  .github/workflows/integrate-playground.yaml
  .github/workflows/integrate-tiup.yaml
  .github/workflows/release-tiup.yaml
  .github/workflows/reprotest.yaml
  cmd/list.go
  cmd/uninstall.go
  components/playground/grafana.go
  components/playground/instance/drainer.go
  components/playground/instance/instance.go
  components/playground/instance/pd.go
  components/playground/instance/process.go
  components/playground/instance/pump.go
  components/playground/instance/ticdc.go
  components/playground/instance/tidb.go
  components/playground/instance/tiflash.go
  components/playground/instance/tiflash_proxy_config.go
  components/playground/instance/tikv.go
  components/playground/monitor.go
  components/playground/playground.go
  pkg/cluster/manager/builder.go
  pkg/cluster/manager/deploy.go
  pkg/cluster/manager/upgrade.go
  pkg/environment/env.go
  pkg/exec/run.go
  pkg/localdata/profile.go
  pkg/repository/clone_mirror.go
  pkg/repository/merge_mirror.go
  pkg/repository/v1_repository.go
  pkg/repository/version/version.go
  pkg/repository/version/version_test.go
  pkg/utils/semver.go
  pkg/utils/semver_test.go
  pkg/version/types.go
  pkg/version/version.go
Labels: size/XL, status/LGT1, status/can-merge, type/enhancement

#1215 Extract check cmd to pkg
  components/cluster/command/check.go
  pkg/cluster/manager/check.go
  pkg/cluster/operation/check.go
Labels: size/XXL, status/LGT1, status/can-merge

#1217 Extract get audit list
  pkg/cluster/audit/audit.go
Labels: size/M, status/LGT1, status/can-merge

#1222 cluster: fix tikv upgrade error not returned correctly
  pkg/cluster/operation/upgrade.go
Labels: size/S, status/LGT1, status/can-merge, type/bug-fix

#1229 Fix the issue that tiup-cluster can't deploy arm64 binary
  pkg/cluster/manager/deploy.go
  pkg/cluster/manager/upgrade.go
  pkg/cluster/task/copy_component.go
  pkg/cluster/task/download.go
  pkg/repository/v1_repository.go
Labels: size/S, status/LGT1, status/can-merge

#1230 bump version to v1.3.6
  CHANGELOG.md
  pkg/version/version.go
Labels: size/XS, status/LGT1, status/can-merge

#1211 Omitting deprecated `"users.*"` settings for TiFlash
  components/playground/instance/tiflash_proxy_config.go
  components/playground/playground.go
  pkg/cluster/spec/spec_test.go
  pkg/cluster/spec/tiflash.go
Labels: size/L, status/LGT1, status/can-merge

#1237 Fix the issue that prune command will regen config for removed nodes
  pkg/cluster/manager/destroy.go
Labels: size/S, status/LGT1, status/can-merge, type/bug-fix

#1238 cluster,dm: replace ENV_LABELS_ENV in prometheus rules
  pkg/cluster/spec/prometheus.go
  pkg/cluster/spec/prometheus_test.go
  tests/tiup-cluster/test_upgrade_tls.sh
Labels: size/M, status/LGT1, status/can-merge

#1240 Bump v1.3.7
  CHANGELOG.md
  pkg/version/version.go
Labels: size/S, status/LGT1, status/can-merge

#1245 cluster,dm: -R -N's help message is wrong
  components/cluster/command/check.go
  components/cluster/command/reload.go
  components/dm/command/reload.go
Labels: size/S, status/LGT1, status/can-merge

#1243 tiup: fix -v/--version argument
  cmd/root.go
  pkg/cluster/manager/destroy.go
Labels: size/S, status/LGT1, status/can-merge, type/bug-fix

#1227 cluster: fix the issue when endpoints are empty in scale-out
  Makefile
  pkg/cluster/api/pdapi.go
  pkg/cluster/ctxt/context.go
  pkg/cluster/manager/scale_out.go
  pkg/cluster/operation/action.go
  pkg/cluster/spec/instance.go
  pkg/cluster/spec/tiflash.go
  tests/tiup-cluster/script/scale_tools.sh
  tests/tiup-cluster/topo/full_scale_in_tiflash.yaml
  tests/tiup-cluster/topo/full_without_tiflash.yaml
Labels: size/L, status/LGT1, status/can-merge

#1235 dm: support monitored config
  components/dm/spec/bindversion.go
  components/dm/spec/logic.go
  components/dm/spec/topology_dm.go
  components/dm/spec/topology_dm_test.go
  embed/templates/config/prometheus.yml.tpl
  tests/tiup-cluster/topo/full.yaml
  tests/tiup-dm/script/task/run.sh
  tests/tiup-dm/test_cmd.sh
  tests/tiup-dm/topo/full_dm_monitored.yaml.tpl
Labels: size/XL, status/LGT1, status/can-merge

#1231 dm,cluster: display with uptime returned
  components/cluster/command/display.go
  components/dm/command/display.go
  components/dm/spec/logic.go
  go.mod
  pkg/cluster/manager/display.go
  pkg/cluster/operation/operation.go
  pkg/cluster/spec/alertmanager.go
  pkg/cluster/spec/cdc.go
  pkg/cluster/spec/drainer.go
  pkg/cluster/spec/grafana.go
  pkg/cluster/spec/instance.go
  pkg/cluster/spec/pd.go
  pkg/cluster/spec/prometheus.go
  pkg/cluster/spec/pump.go
  pkg/cluster/spec/spec.go
  pkg/cluster/spec/tidb.go
  pkg/cluster/spec/tiflash.go
  pkg/cluster/spec/tikv.go
  pkg/cluster/spec/tispark.go
  pkg/cluster/spec/util.go
  tests/tiup-cluster/script/cmd_subtest.sh
  tests/tiup-dm/test_cmd.sh
Labels: category/usability, size/XL, status/LGT1, status/can-merge, type/new-feature

#1256 Fix typo with find command
  tools/check/check-lint.sh
Labels: size/XS, status/LGT1, status/can-merge

#1251 docker: support --nodes
  docker/docker-compose.yml.tpl
  docker/up.sh
Labels: size/M, status/LGT1, status/can-merge

#1250 fix: grant cap_net_raw to blackbox_exporter
  embed/templates/systemd/system.service.tpl
  pkg/cluster/task/monitored_config.go
  pkg/cluster/template/systemd/system.go
Labels: size/XS, status/LGT1, status/can-merge

#1248 Fix the issue that tiup update --nightly not update to nightly
  pkg/environment/env.go
  tests/tiup-playground/test_playground.sh
  tests/tiup/test_tiup.sh
Labels: size/S, status/LGT1, status/can-merge

#1204 Bump v1.4.0
  .github/workflows/integrate-cluster-cmd.yaml
  .github/workflows/integrate-cluster-scale.yaml
  .github/workflows/integrate-dm.yaml
  .github/workflows/integrate-playground.yaml
  CHANGELOG.md
  pkg/version/version.go
Labels: category/document, size/L, status/LGT1, status/can-merge

#1242 Support config on TiCDC
  components/playground/main.go
  embed/templates/scripts/run_cdc.sh.tpl
  pkg/cluster/spec/cdc.go
  pkg/cluster/template/scripts/cdc.go
Labels: size/M, status/LGT1, status/can-merge

#1252 cluster: Type -> Rule in confirmTopology
  pkg/cluster/manager/manager.go
Labels: size/XS, status/LGT1, status/can-merge

#1257 *: fix releasing workflow
  .github/workflows/release-tiup.yaml
  .github/workflows/reprotest.yaml
  Makefile
Labels: size/M, status/LGT1, status/can-merge

#1253 cluster: reuse cluster.DeployOption and spec.PDScaleScript
  components/cluster/command/scale_out.go
  components/dm/command/scale_out.go
  pkg/cluster/manager/builder.go
  pkg/cluster/manager/deploy.go
  pkg/cluster/manager/scale_out.go
  pkg/cluster/spec/pd.go
  pkg/cluster/template/scripts/pd.go
  pkg/cluster/template/scripts/pd_test.go
Labels: size/L, status/LGT1, status/can-merge
