Repository pingcap/tiup, pull requests merged in 2021-01, with the labels that each got.

#1031 *: remove some legacy code using v0manifest
  pkg/repository/v1_repository_test.go
  server/package/package.go
  tools/migrate/main.go
Labels: size/XXL, status/LGT1, status/can-merge, type/enhancement

#1030 cluster: add role and node filter for `check` subcommand
  components/cluster/command/check.go
Labels: category/usability, size/M, status/LGT1, status/can-merge, type/enhancement, type/new-feature

#1040 Fix/prometheus wrong data dir
  components/playground/monitor.go
  tests/tiup-playground/test_playground.sh
Labels: size/XS, status/LGT1, status/can-merge

#1041 tests/tiup-cluster: check prometheus monitored components
  pkg/cluster/spec/prometheus.go
  tests/tiup-cluster/script/scale_tools.sh
Labels: size/S, status/LGT1, status/can-merge

#1046 *: update go mod dependencies
  components/playground/playground.go
  components/playground/playground_test.go
  go.mod
  go.sum
  pkg/tui/tui.go
Labels: size/L, status/LGT1, status/can-merge, type/enhancement

#1044 cluster: add subcommand pull and push to transfer files
  components/cluster/command/exec.go
  components/cluster/command/root.go
  components/cluster/command/transfer.go
  components/dm/command/exec.go
  pkg/cluster/manager/transfer.go
  tests/tiup-cluster/script/cmd_subtest.sh
Labels: category/usability, size/L, status/LGT1, status/can-merge, type/new-feature

#1049 Fix push with template
  pkg/cluster/manager/transfer.go
  pkg/cluster/manager/transfer_test.go
  tests/tiup-cluster/script/cmd_subtest.sh
Labels: size/M, status/LGT1, status/can-merge

#1054 fix(cluster/display): don't print dashboardAddr if none or auto
  pkg/cluster/manager/display.go
Labels: size/XS, status/LGT1, status/can-merge

#1052 feat(cmd): add tiup as completion's prefix name
  cmd/completion.go
Labels: size/XS, status/LGT1, status/can-merge

#1061 Fix the issue that tiup mirror clone not handle yanked tarball correctly
  pkg/repository/clone_mirror.go
Labels: size/XS, status/LGT1, status/can-merge

#1056 Fix the issue that dm grafana doen't has home.json
  pkg/cluster/spec/grafana.go
Labels: size/XS, status/LGT1, status/can-merge

#1050 cluster: allow type change when editing topology
  go.mod
  go.sum
  pkg/utils/diff.go
  pkg/utils/diff_test.go
Labels: category/usability, size/M, status/LGT1, status/can-merge, type/enhancement

#1048 cluster: support spec template for `exec`
  components/cluster/command/check.go
  pkg/cluster/manager/exec.go
  pkg/cluster/manager/transfer.go
  pkg/cluster/task/builder.go
  pkg/cluster/task/shell.go
  pkg/cluster/task/task.go
Labels: category/usability, size/L, status/LGT1, status/can-merge, type/new-feature

#1060 Fix the issue that tiup mirror clone not handle any platform correctly
  pkg/repository/clone_mirror.go
Labels: size/M, status/LGT1, status/can-merge

#1051 Fix the issue that the expires shortened after merging cloned mirror
  pkg/repository/v1manifest/manifest.go
Labels: size/S, status/LGT1, status/can-merge, type/bug-fix

#1053 typo(cmd/mirror): add warning if key already exists
  cmd/mirror.go
  pkg/repository/clone_mirror.go
  pkg/repository/v1manifest/repo.go
Labels: size/M, status/LGT1, status/can-merge

#1075 fix(cluster/executor): local executor should in single quote command
  pkg/cluster/executor/local.go
  pkg/cluster/executor/local_test.go
Labels: size/S, status/LGT1, status/can-merge

#1068 cluster: fix parsing of paths if there are redundant slashes in it
  pkg/cluster/operation/destroy.go
  pkg/cluster/spec/testdata/countdir.yaml
  pkg/cluster/spec/util.go
  pkg/cluster/spec/util_test.go
  pkg/cluster/spec/validate_test.go
Labels: category/stability, size/L, status/LGT1, status/can-merge, type/bug-fix

#1072 Feature/validate port user group
  pkg/cluster/spec/spec.go
  pkg/cluster/spec/validate.go
  pkg/cluster/spec/validate_test.go
Labels: size/L, status/LGT1, status/can-merge

#1080 Feature/dm destroy support --force --retaion-node-data --retaion-role-data
  components/cluster/command/destroy.go
  components/dm/command/destroy.go
Labels: size/M, status/LGT1, status/can-merge

#1078 *: remove v0manifest
  cmd/help.go
  pkg/cluster/executor/local_test.go
  pkg/environment/env.go
  pkg/exec/run.go
  pkg/localdata/profile.go
  pkg/repository/file_source.go
  pkg/repository/file_source_test.go
  pkg/repository/progress_test.go
  pkg/repository/repository.go
  pkg/repository/repository_test.go
  pkg/repository/v0manifest/component.go
  pkg/repository/v0manifest/version.go
  pkg/repository/v0manifest/version_test.go
Labels: size/XXL, status/LGT1, status/can-merge, type/enhancement

#1083 Add the node_exporter instance of the server where the tiflash-server…
  pkg/cluster/spec/prometheus.go
Labels: size/XS, status/LGT1, status/can-merge

#1086 cluster: upgrade PD leader after other PD instances
  pkg/cluster/operation/upgrade.go
  pkg/cluster/spec/pd.go
Labels: category/stability, size/M, status/LGT1, status/can-merge, type/enhancement, type/new-feature

#1092 Feature/add prometheus local rules
  pkg/cluster/embed/autogen_pkger.go
  pkg/cluster/spec/instance.go
  pkg/cluster/spec/prometheus.go
  pkg/cluster/template/config/prometheus.go
  templates/config/prometheus.yml.tpl
Labels: size/M, status/LGT1, status/can-merge

#1091 Fix the issue that a dummy entry may cheat patch command
  pkg/cluster/manager/patch.go
  tests/tiup-cluster/script/cmd_subtest.sh
Labels: size/S, status/LGT1, status/can-merge

#1089 Mark required flag in help message
  components/cluster/command/scale_in.go
  components/dm/command/import.go
  components/dm/command/scale_in.go
  server/package/package.go
Labels: size/S, status/LGT1, status/can-merge

#1088 Fix the issue that tiup-cluster disable monitoring service unexpected
  pkg/cluster/operation/action.go
Labels: size/S, status/LGT1, status/can-merge

#1085 fix: tiup supports define root_url and enable anonymous in grafana.ini
  pkg/cluster/embed/autogen_pkger.go
  pkg/cluster/spec/grafana.go
  pkg/cluster/template/config/grafana.go
  templates/config/grafana.ini.tpl
Labels: first-time-contributor, good first issue, size/M, status/LGT1, status/can-merge

#1093 Feature/disable log or data dir overlapped
  pkg/cluster/spec/validate.go
  pkg/cluster/spec/validate_test.go
  pkg/utils/ioutil.go
  pkg/utils/ioutil_test.go
  pkg/utils/mock/mock.go
Labels: size/XL, status/LGT1, status/can-merge

#1095 README: add info and fix typos
  README.md
Labels: category/document, size/S, status/LGT1, status/can-merge

#1101 cluster: add workaround for different *_exporter locations
  pkg/cluster/embed/autogen_pkger.go
  templates/scripts/run_blackbox_exporter.sh.tpl
  templates/scripts/run_node_exporter.sh.tpl
Labels: ansible, category/monitoring, category/stability, size/S, status/LGT1, status/can-merge, type/bug-fix

#1102 Fix/checkpoint's context value maybe nil
  doc/design/checkpoint.md
  pkg/checkpoint/checkpoint.go
  pkg/checkpoint/checkpoint_test.go
Labels: size/M, status/LGT1, status/can-merge

#1103 Add debug mode for checkpoint
  components/playground/playground.go
  pkg/checkpoint/checkpoint.go
  pkg/checkpoint/checkpoint_test.go
  pkg/checkpoint/gotrack.go
  pkg/cluster/ansible/service.go
  pkg/cluster/api/binlog.go
  pkg/cluster/executor/local.go
  pkg/cluster/executor/ssh.go
  pkg/cluster/operation/destroy.go
  pkg/cluster/operation/scale_in.go
  tests/tiup-cluster/run.sh
  tests/tiup-dm/run.sh
Labels: size/L, status/LGT1, status/can-merge

#1104 cliutil: return user's answer on prompt
  pkg/cliutil/tui.go
  pkg/cluster/manager/edit_config.go
Labels: category/usability, size/S, status/LGT1, status/can-merge, type/enhancement

#1099 cluster: improve check subcommand
  pkg/cluster/operation/check.go
  pkg/cluster/task/check.go
Labels: category/stability, category/usability, size/M, status/LGT1, status/can-merge, type/enhancement, type/new-feature

#1106 Bump v1.3.2
  CHANGELOG.md
  pkg/version/version.go
Labels: size/S, status/LGT1, status/can-merge

#1074 feat(cluster/spec): check alertmanager,prometheus's config
  pkg/cluster/embed/autogen_pkger.go
  pkg/cluster/spec/alertmanager.go
  pkg/cluster/spec/grafana.go
  pkg/cluster/spec/prometheus.go
  pkg/cluster/spec/prometheus_test.go
  pkg/cluster/spec/server_config.go
  pkg/cluster/spec/testdata/rules/tidb.rules.yml
  templates/config/dm/prometheus.yml.tpl
  templates/config/prometheus.yml.tpl
  tests/tiup-cluster/script/cmd_subtest.sh
Labels: size/L, status/LGT1, status/can-merge
