Repository pingcap/tiup, pull requests merged in 2021-06, with the labels that each got.

#1372 support ticdc data dir
  components/client/go.mod
  components/client/go.sum
  embed/templates/scripts/run_cdc.sh.tpl
  pkg/cluster/manager/check.go
  pkg/cluster/manager/deploy.go
  pkg/cluster/manager/scale_out.go
  pkg/cluster/manager/upgrade.go
  pkg/cluster/spec/cdc.go
  pkg/cluster/spec/spec.go
  pkg/cluster/spec/spec_test.go
  pkg/cluster/template/scripts/cdc.go
Labels: size/L, status/LGT1, status/can-merge

#1401 cluster: fix tikv not upgraded on error increasing schedule limit
  pkg/cluster/operation/upgrade.go
Labels: category/stability, size/S, status/LGT1, status/can-merge, type/bug-fix

#1390 cluster: fix wrong indent in display
  pkg/cluster/manager/display.go
Labels: size/XS, status/LGT1, status/can-merge

#1404 Added tiup cluster template --local
  components/cluster/command/template.go
  embed/templates/examples/local.yaml
Labels: category/usability, component/cluster, size/M, status/LGT1, status/can-merge

#1407 Update dependencies
  go.mod
  go.sum
Labels: size/L, status/LGT1, status/can-merge

#1409 cluster: add deploy user to display output
  cmd/root.go
  components/cluster/command/root.go
  pkg/cluster/manager/display.go
Labels: category/usability, component/cluster, component/dm, size/M, status/LGT1, status/can-merge

#1412 cluster: support char dot(.) in cluster name
  pkg/cluster/clusterutil/cluster_name.go
Labels: size/XS, status/LGT1, status/can-merge

#1415 bump version 1.5.0
  CHANGELOG.md
  pkg/version/version.go
Labels: size/M, status/LGT1, status/can-merge

#1418 tests/cluster: --native-ssh is deprecated, use --ssh=system
  tests/tiup-cluster/script/cmd_subtest.sh
  tests/tiup-cluster/script/scale_core.sh
  tests/tiup-cluster/script/scale_tools.sh
  tests/tiup-cluster/script/util.sh
Labels: category/testing, size/S, status/LGT1, status/can-merge

#1419 *: fix release build
  .github/workflows/release-tiup.yaml
Labels: size/XS, status/LGT1

#1421 spec: fix cdc data dir version issue
  pkg/cluster/spec/spec_test.go
  pkg/cluster/template/scripts/cdc.go
Labels: component/cluster, size/M, status/LGT1, status/can-merge, type/bug-fix

#1422 bump version 1.5.1
  CHANGELOG.md
  pkg/version/version.go
Labels: size/S, status/LGT1, status/can-merge

#1416 cluster: check, deploy support use ssh-agent instead of identity-file
  components/cluster/command/check.go
  components/cluster/command/deploy.go
  components/cluster/command/scale_out.go
  components/dm/command/deploy.go
  components/dm/command/scale_out.go
  pkg/cliutil/ssh.go
  pkg/cluster/manager/check.go
  tests/tiup-cluster/script/cmd_subtest.sh
Labels: component/cluster, component/dm, size/L, status/LGT1, status/can-merge, type/new-feature

#1424 cluster/executor: fix the issue of native ssh connect refused if port not 22
  pkg/cluster/executor/ssh.go
  pkg/cluster/executor/ssh_test.go
Labels: size/L, status/LGT1, status/can-merge

#1420 task: implement parallel concurrency limit
  components/cluster/command/root.go
  components/dm/ansible/import_test.go
  components/dm/command/import.go
  components/dm/command/root.go
  pkg/cluster/ansible/config.go
  pkg/cluster/ansible/service.go
  pkg/cluster/ctxt/context.go
  pkg/cluster/executor/local_test.go
  pkg/cluster/manager/basic.go
  pkg/cluster/manager/check.go
  pkg/cluster/manager/cleanup.go
  pkg/cluster/manager/deploy.go
  pkg/cluster/manager/destroy.go
  pkg/cluster/manager/display.go
  pkg/cluster/manager/exec.go
  pkg/cluster/manager/patch.go
  pkg/cluster/manager/reload.go
  pkg/cluster/manager/scale_in.go
  pkg/cluster/manager/scale_out.go
  pkg/cluster/manager/transfer.go
  pkg/cluster/manager/upgrade.go
  pkg/cluster/operation/operation.go
  pkg/cluster/spec/grafana_test.go
  pkg/cluster/task/init_config_test.go
  pkg/cluster/task/task.go
  pkg/cluster/task/tls.go
Labels: category/stability, component/cluster, component/dm, size/L, status/LGT1, status/can-merge, type/new-feature

#1425 Update alertmanager.yml
  embed/templates/config/alertmanager.yml
Labels: size/XS, status/LGT1, status/can-merge

#1426 Update alertmanager.yml
  embed/templates/config/alertmanager.yml
Labels: size/XS, status/LGT1, status/can-merge

#1428 fix pd and dashboard address display issue in `tiup-playground`
  components/playground/playground.go
Labels: component/playground, size/XS, status/LGT1, status/can-merge

#1429 doc: fix a help message of playground
  components/playground/main.go
Labels: component/playground, size/XS, status/LGT1, status/can-merge

#1423 cluster,dm: auto detect cpu arch
  .github/workflows/integrate-cluster-cmd.yaml
  .github/workflows/integrate-cluster-scale.yaml
  .github/workflows/integrate-dm.yaml
  components/dm/spec/topology_dm.go
  components/dm/spec/topology_dm_test.go
  pkg/cluster/ansible/import.go
  pkg/cluster/ansible/import_test.go
  pkg/cluster/ansible/inventory.go
  pkg/cluster/manager/check.go
  pkg/cluster/manager/deploy.go
  pkg/cluster/manager/manager.go
  pkg/cluster/manager/scale_out.go
  pkg/cluster/spec/spec.go
  pkg/cluster/spec/spec_manager_test.go
  pkg/cluster/spec/validate_test.go
Labels: size/L, status/LGT1, status/can-merge

#1431 Fix the issue that exec command doesn't handle tiflash nodes
  pkg/cluster/manager/transfer.go
Labels: component/cluster, size/XS, status/LGT1, status/can-merge

#1433 *: update dependencies
  go.mod
  go.sum
Labels: size/L, status/LGT1, status/can-merge

#1434 cluster: increase default timeout transfer leader in upgrade progress
  components/cluster/command/upgrade.go
  pkg/cluster/module/systemd.go
  pkg/cluster/operation/upgrade.go
Labels: size/XS, status/LGT1, status/can-merge

#1435 tikv: prof.active is not a valid jemalloc config
  components/playground/instance/tikv.go
  embed/templates/scripts/run_tikv.sh.tpl
Labels: component/cluster, component/playground, size/XS, status/LGT1, status/can-merge

#1441 Fix the issue that slow log position not change with LogDir
  embed/templates/scripts/run_tidb.sh.tpl
Labels: size/XS, status/LGT1, status/can-merge

#1445 *: use `--wait-timeout` for SSH command opeartions with easyssh
  components/cluster/command/import.go
  pkg/cluster/ansible/config.go
  pkg/cluster/executor/ssh.go
  pkg/cluster/manager/builder.go
  pkg/cluster/manager/check.go
  pkg/cluster/manager/deploy.go
  pkg/cluster/manager/manager.go
  pkg/cluster/manager/reload.go
  pkg/cluster/task/builder.go
  pkg/cluster/task/ssh.go
Labels: size/L, status/LGT1, status/can-merge

#1443 blackbox: fix the issue of TLS handshake error in tls cluster
  embed/templates/config/blackbox.yml
  embed/templates/config/blackbox.yml.tpl
  embed/templates/config/prometheus.yml.tpl
  pkg/cluster/manager/builder.go
  pkg/cluster/manager/deploy.go
  pkg/cluster/task/builder.go
  pkg/cluster/task/monitored_config.go
  pkg/cluster/task/tls.go
  pkg/cluster/template/config/blackbox.go
Labels: size/XL, status/LGT1, status/can-merge

#1446 cluster/tls: add 127.0.0.1,localhost to cert list
  pkg/cluster/task/tls.go
Labels: size/S, status/LGT1, status/can-merge

#1447 bump version 1.5.2
  CHANGELOG.md
  pkg/version/version.go
Labels: size/S, status/LGT1, status/can-merge

#1438 cluster,dm: add support of ssh-proxy
  components/cluster/command/import.go
  components/cluster/command/root.go
  components/cluster/command/test.go
  components/dm/command/root.go
  docker/docker-compose.yml.tpl
  docker/up.sh
  pkg/cluster/ansible/config.go
  pkg/cluster/api/binlog.go
  pkg/cluster/executor/ssh.go
  pkg/cluster/executor/ssh_test.go
  pkg/cluster/manager/basic.go
  pkg/cluster/manager/builder.go
  pkg/cluster/manager/check.go
  pkg/cluster/manager/cleanup.go
  pkg/cluster/manager/deploy.go
  pkg/cluster/manager/destroy.go
  pkg/cluster/manager/exec.go
  pkg/cluster/manager/manager.go
  pkg/cluster/manager/patch.go
  pkg/cluster/manager/reload.go
  pkg/cluster/manager/scale_in.go
  pkg/cluster/manager/scale_out.go
  pkg/cluster/manager/transfer.go
  pkg/cluster/manager/upgrade.go
  pkg/cluster/operation/destroy.go
  pkg/cluster/operation/operation.go
  pkg/cluster/operation/scale_in.go
  pkg/cluster/spec/spec.go
  pkg/cluster/spec/tikv.go
  pkg/cluster/task/builder.go
  pkg/cluster/task/ssh.go
  pkg/cluster/task/update_topology.go
  pkg/proxy/http_proxy.go
  pkg/proxy/proxy.go
  pkg/proxy/tcp_proxy.go
  pkg/utils/http_client.go
Labels: size/XXL, status/LGT1, status/can-merge

#1458 cluster/check: apply thp fix only if thp found
  pkg/cluster/manager/check.go
  pkg/cluster/operation/check.go
Labels: size/XS, status/LGT1, status/can-merge

#1459 *: update dependencies & adjust an error message
  components/bench/go.mod
  components/bench/go.sum
  components/client/go.mod
  components/client/go.sum
  components/ctl/main.go
Labels: size/M, status/LGT1, status/can-merge

#1455 cmd: use SHELL from environment for completion
  cmd/completion.go
  go.mod
  go.sum
Labels: size/M, status/LGT1, status/can-merge

#1461 tests/tiup-cluster: duplicated version v
  pkg/cluster/manager/patch.go
  tests/tiup-cluster/test_cmd_tls_native_ssh.sh
Labels: category/testing, size/S, status/LGT1, status/can-merge
