Repository pingcap/tiup, pull requests merged in 2022-02, with the labels that each got.

#1734 cluster: fix malformed commands in local executor
  pkg/cluster/executor/local.go
  pkg/cluster/executor/local_test.go
  pkg/cluster/spec/grafana.go
  pkg/cluster/spec/monitoring.go
Labels: status/can-merge, status/LGT1, size/M

#1743 cluster: fix ngm cannot be reload
  embed/templates/systemd/system.service.tpl
Labels: status/can-merge, status/LGT1, size/XS

#1746 utils: add some http operations
  pkg/utils/http_client.go
Labels: status/can-merge, status/LGT1, size/M

#1738 tiup/playground: refactor RunComponent
  cmd/root.go
  components/playground/grafana.go
  components/playground/instance/drainer.go
  components/playground/instance/pd.go
  components/playground/instance/process.go
  components/playground/instance/pump.go
  components/playground/instance/ticdc.go
  components/playground/instance/tidb.go
  components/playground/instance/tiflash.go
  components/playground/instance/tikv.go
  components/playground/monitor.go
  components/playground/ngmonitoring.go
  components/playground/playground.go
  pkg/environment/env.go
  pkg/exec/run.go
Labels: status/can-merge, status/LGT1, size/XL

#1745 dm: add TLS support
  components/dm/command/prune.go
  components/dm/command/scale_in.go
  components/dm/spec/logic.go
  embed/templates/config/prometheus.yml.tpl
  embed/templates/scripts/run_dm-master.sh.tpl
  embed/templates/scripts/run_dm-master_scale.sh.tpl
  embed/templates/scripts/run_dm-worker.sh.tpl
  pkg/cluster/template/scripts/dm_master.go
  pkg/utils/utils.go
Labels: status/can-merge, status/LGT1, size/L

#1747 dm: fix messige at the end of deploy
  pkg/cluster/manager/deploy.go
Labels: status/can-merge, status/LGT1, size/XS

#1748 *: update dependencies
  components/bench/go.mod
  components/bench/go.sum
  components/client/go.mod
  components/client/go.sum
  components/errdoc/main.go
  go.mod
  go.sum
  pkg/cluster/api/dmpb/dmmaster.pb.go
  pkg/cluster/api/dmpb/dmmaster.pb.gw.go
  pkg/cluster/api/dmpb/dmworker.pb.go
  pkg/cluster/api/typeutil/duration.go
  pkg/cluster/api/typeutil/duration_test.go
  pkg/cluster/api/typeutil/size.go
  pkg/cluster/api/typeutil/size_test.go
  pkg/cluster/api/typeutil/string_slice.go
  pkg/cluster/api/typeutil/string_slice_test.go
  pkg/repository/mirror.go
Labels: status/can-merge, status/LGT1, size/XXL

#1751 bump version 1.9.0
  CHANGELOG.md
  pkg/version/version.go
Labels: status/can-merge, status/LGT1, size/M

#1755 bench: update cmd flags of go-tpc v1.0.8
  components/bench/tpcc.go
  components/bench/tpch.go
Labels: status/can-merge, status/LGT1, size/S

#1753 cluster: completing the os type of the host
  components/cluster/command/check.go
  components/dm/spec/topology_dm.go
  components/dm/spec/topology_dm_test.go
  pkg/cluster/ansible/inventory.go
  pkg/cluster/manager/builder.go
  pkg/cluster/manager/check.go
  pkg/cluster/manager/deploy.go
  pkg/cluster/manager/manager.go
  pkg/cluster/manager/scale_out.go
  pkg/cluster/spec/spec.go
  pkg/cluster/spec/spec_manager_test.go
  pkg/cluster/spec/validate_test.go
Labels: status/can-merge, status/LGT1, size/L

#1760 cluster: fix ngm nightly not start by default
  pkg/cluster/spec/spec.go
Labels: status/can-merge, status/LGT1, size/XS

#1758 cluster: fix upgrade not restart exporer
  pkg/cluster/operation/action.go
  pkg/cluster/operation/upgrade.go
Labels: status/can-merge, status/LGT1, size/S

#1763 cluster: fix stdout and stderr
  pkg/cluster/ctxt/context.go
Labels: status/can-merge, status/LGT1, size/XS

#1768 cluster: fix Grafana error datasource not found
  components/playground/grafana.go
  embed/templates/config/datasource.yml.tpl
  pkg/cluster/manager/builder.go
  pkg/cluster/manager/destroy.go
  pkg/cluster/manager/scale_in.go
Labels: status/can-merge, status/LGT1, size/M

#1769 bump version 1.9.1
  CHANGELOG.md
  pkg/version/version.go
Labels: size/S
