Repository pingcap/tiup, pull requests merged in 2022-01, with the labels that each got.

#1701 cluster: scale-out topology cannot inherit the global configuration
  pkg/cluster/manager/check.go
  pkg/cluster/manager/scale_out.go
  pkg/cluster/spec/parse_topology.go
  pkg/cluster/spec/parse_topology_test.go
Labels: status/can-merge, status/LGT1, size/M

#1703 cluster: support configure grafana in server_configs
  components/dm/spec/topology_dm.go
  pkg/cluster/ansible/import_test.go
  pkg/cluster/ansible/test-data/meta.yaml
  pkg/cluster/spec/grafana.go
  pkg/cluster/spec/grafana_test.go
  pkg/cluster/spec/spec.go
  pkg/cluster/spec/spec_manager_test.go
Labels: status/can-merge, status/LGT1, size/L

#1699 cluster: ngm server default enabled during deployment
  embed/examples/cluster/minimal.yaml
  embed/examples/cluster/multi-dc.yaml
  embed/examples/cluster/topology.example.yaml
  pkg/cluster/manager/upgrade.go
  pkg/cluster/spec/monitoring.go
  pkg/cluster/spec/spec.go
  pkg/cluster/spec/validate.go
Labels: status/can-merge, status/LGT1, size/S

#1705 mirror: Fix typos and naming
  doc/user/mirrors.md
  pkg/repository/clone_mirror.go
Labels: status/can-merge, status/LGT1, size/L

#1710 cluster/deploy: adjust hint to add --init
  pkg/cluster/manager/deploy.go
Labels: status/can-merge, status/LGT1, size/XS

#1706 cluster: use initial_commit_ts in drainer config file instead of start script
  embed/templates/scripts/run_drainer.sh.tpl
  pkg/cluster/ansible/service.go
  pkg/cluster/spec/drainer.go
  pkg/cluster/spec/spec.go
  pkg/cluster/template/scripts/drainer.go
Labels: status/can-merge, status/LGT1, size/M

#1712 playground: fix panic when boot monitor
  components/playground/playground.go
Labels: status/can-merge, status/LGT1, size/XS

#1702 cluster: nightly version could not be compared
  pkg/cluster/task/builder.go
Labels: status/can-merge, status/LGT1, size/S

#1715 playground: fix cannot find nightly version
  pkg/repository/v1_repository.go
Labels: status/can-merge, status/LGT1, size/M

#1716 bump version 1.8.2
  CHANGELOG.md
  pkg/version/version.go
Labels: status/can-merge, status/LGT1, size/S

#1717 not record "tiup __complete" in telemetry and audit log
  cmd/root.go
  components/cluster/command/root.go
Labels: status/can-merge, status/LGT1, size/XS

#1714 cluster: support Chrony as NTP implementation
  go.mod
  go.sum
  pkg/cluster/operation/check.go
Labels: status/can-merge, status/LGT1, size/M

#1720 fix json output for check results
  pkg/cluster/manager/check.go
Labels: status/can-merge, status/LGT1, size/M

#1718 tiup: check update before run component
  pkg/exec/run.go
Labels: status/can-merge, status/LGT1, size/M

#1727 playground: allow use different nightly version
  components/playground/main.go
Labels: status/can-merge, status/LGT1, size/S

#1723 cluster: add significant warning destroying a cluster
  pkg/cluster/manager/destroy.go
  tests/tiup-cluster/script/upgrade.sh
  tests/tiup-dm/test_upgrade.sh
Labels: status/can-merge, status/LGT1, size/S

#1729 cluster: fix tls op not check topo Validate
  pkg/cluster/manager/tls.go
Labels: status/can-merge, status/LGT1, size/XS

#1730 Update error messages and prompts
  components/cluster/command/start.go
  pkg/exec/run.go
Labels: status/can-merge, status/LGT1, size/S

#1735 cluster: Ignore the nightly version when judging whether the TiFlash version supports TLS
  pkg/cluster/manager/basic.go
  pkg/cluster/manager/deploy.go
  pkg/cluster/manager/scale_out.go
  pkg/cluster/manager/tls.go
Labels: status/can-merge, status/LGT1, size/M

#1740 Add Amazon Linux 2 as supported OS
  pkg/cluster/operation/check.go
Labels: status/can-merge, status/LGT1, size/XS

#1737 cluster: deduplicate the check result
  pkg/cluster/manager/check.go
  pkg/cluster/manager/manager_test.go
Labels: status/can-merge, status/LGT1, size/M

#1742 cluster: fix wrong status when display due to closure
  pkg/cluster/spec/alertmanager.go
  pkg/cluster/spec/grafana.go
  pkg/cluster/spec/monitoring.go
  pkg/cluster/spec/tispark.go
Labels: status/can-merge, status/LGT1, size/XS
