Repository pingcap/tiup, pull requests merged in 2022-05, with the labels that each got.

#1867 cluster: display support concurrent access to node status
  components/dm/spec/logic.go
  pkg/cluster/manager/display.go
  pkg/cluster/operation/check.go
  pkg/cluster/spec/spec.go
  pkg/cluster/spec/spec_manager_test.go
Labels: status/can-merge, status/LGT1, size/M

#1866 cluster: display support set status-timeout
  components/cluster/command/display.go
  components/dm/command/display.go
  components/dm/spec/logic.go
  components/dm/spec/topology_dm.go
  components/playground/playground.go
  pkg/cluster/api/binlog.go
  pkg/cluster/manager/display.go
  pkg/cluster/operation/destroy.go
  pkg/cluster/operation/scale_in.go
  pkg/cluster/spec/alertmanager.go
  pkg/cluster/spec/cdc.go
  pkg/cluster/spec/drainer.go
  pkg/cluster/spec/grafana.go
  pkg/cluster/spec/instance.go
  pkg/cluster/spec/monitoring.go
  pkg/cluster/spec/pd.go
  pkg/cluster/spec/pump.go
  pkg/cluster/spec/spec.go
  pkg/cluster/spec/tidb.go
  pkg/cluster/spec/tiflash.go
  pkg/cluster/spec/tikv.go
  pkg/cluster/spec/tispark.go
  pkg/cluster/spec/util.go
Labels: status/can-merge, status/LGT1, size/L

#1863 ctl: add tidb-lightning
  components/ctl/main.go
Labels: status/can-merge, status/LGT1, size/XS

#1869 playground: make playground tag has higher priority than tiup
  cmd/root.go
  components/playground/main.go
Labels: status/can-merge, status/LGT1, size/M

#1856 cluster: return error when found multiple nodes with the same ip:port
  pkg/cluster/api/binlog.go
Labels: status/can-merge, status/LGT1, size/L

#1874 bump version 1.9.5
  CHANGELOG.md
  pkg/version/version.go
Labels: status/can-merge, status/LGT1, size/S, component/tiup

#1875 adjust changelog
  CHANGELOG.md
Labels: status/can-merge, status/LGT1, size/XS

#1877 Update outdated doc links
  index.html
Labels: status/can-merge, status/LGT1, size/XS

#1873 add package tidbver
  components/dm/command/deploy.go
  components/dm/command/deploy_test.go
  components/playground/instance/ticdc.go
  components/playground/instance/tiflash_config.go
  components/playground/instance/tiflash_proxy_config.go
  pkg/cluster/manager/basic.go
  pkg/cluster/spec/cdc.go
  pkg/cluster/spec/spec.go
  pkg/cluster/spec/spec_test.go
  pkg/cluster/spec/tidb.go
  pkg/cluster/spec/tiflash.go
  pkg/cluster/template/config/prometheus.go
  pkg/cluster/template/scripts/cdc.go
  pkg/cluster/template/scripts/tikv.go
  pkg/tidbver/tidbver.go
Labels: status/can-merge, status/LGT1, size/L

#1847 test: update tidb version
  tests/tiup-cluster/test_cmd_tls_native_ssh.sh
  tests/tiup-cluster/test_scale_core.sh
  tests/tiup-cluster/test_scale_core_tls.sh
  tests/tiup-cluster/test_scale_tools_tls.sh
  tests/tiup-cluster/test_upgrade_tls.sh
  tests/tiup-playground/test_playground.sh
Labels: status/can-merge, status/LGT1, size/S

#1882 test: detect error log
  .github/workflows/integrate-cluster-cmd.yaml
  .github/workflows/integrate-cluster-scale.yaml
  tests/tiup-cluster/script/detect_error.sh
Labels: status/can-merge, status/LGT1, size/M

#1889 cluster: fix display exception
  pkg/cluster/manager/display.go
Labels: type/bug-fix, status/can-merge, status/LGT1, size/S

#1892 bump version 1.9.6
  CHANGELOG.md
  pkg/version/version.go
Labels: status/can-merge, status/LGT1, size/XS

#1883 Revert grafana anonymous config
  embed/examples/dm/minimal.yaml
  embed/examples/dm/topology.example.yaml
Labels: status/can-merge, status/LGT1, size/XS

#1885 fix: TIUP_HOME is not loaded on initializes meta
  pkg/cluster/spec/profile.go
Labels: status/can-merge, status/LGT1, size/S

#1886 cluster: add kylin Linux as supported OS
  pkg/cluster/operation/check.go
Labels: status/can-merge, status/LGT1, size/S

#1895 cluster: fix concurrent map writes
  pkg/cluster/manager/display.go
Labels: status/can-merge, status/LGT1, size/XS

#1891 completion: show cluster list when click tab
  components/cluster/command/clean.go
  components/cluster/command/deploy.go
  components/cluster/command/destroy.go
  components/cluster/command/disable.go
  components/cluster/command/display.go
  components/cluster/command/edit_config.go
  components/cluster/command/enable.go
  components/cluster/command/exec.go
  components/cluster/command/prune.go
  components/cluster/command/reload.go
  components/cluster/command/restart.go
  components/cluster/command/scale_in.go
  components/cluster/command/scale_out.go
  components/cluster/command/show_config.go
  components/cluster/command/start.go
  components/cluster/command/stop.go
  components/cluster/command/upgrade.go
  components/dm/command/deploy.go
  components/dm/command/destroy.go
  components/dm/command/disable.go
  components/dm/command/display.go
  components/dm/command/edit_config.go
  components/dm/command/enable.go
  components/dm/command/exec.go
  components/dm/command/prune.go
  components/dm/command/reload.go
  components/dm/command/restart.go
  components/dm/command/scale_in.go
  components/dm/command/scale_out.go
  components/dm/command/start.go
  components/dm/command/stop.go
  components/dm/command/upgrade.go
Labels: status/can-merge, status/LGT1, size/XL

#1893 playground: exit faster
  components/playground/main.go
  components/playground/playground.go
  pkg/repository/testdata/manifests/root.json
  pkg/repository/testdata/polluted/bin/root.json
  pkg/repository/v1manifest/testdata/polluted/bin/root.json
Labels: status/can-merge, status/LGT1, size/M

#1890 cluster: support check timezone
  pkg/cluster/manager/check.go
  pkg/cluster/operation/check.go
  pkg/cluster/task/check.go
Labels: status/can-merge, status/LGT1, size/M

#1868 bump dependencies
  go.mod
  go.sum
Labels: status/can-merge, status/LGT1, size/XL

#1896 cluster: support RHEL8
  embed/templates/systemd/system.service.tpl
  embed/templates/systemd/tispark.service.tpl
  pkg/cluster/operation/check.go
Labels: status/can-merge, status/LGT1, size/S

#1827 bench: fix wrong woakload loading
  components/bench/ycsb.go
Labels: status/can-merge, status/LGT1, size/XS
