Repository pingcap/tiup, pull requests merged in 2022-06, with the labels that each got.

#1900 fix edit-cluster help information
  components/cluster/command/edit_config.go
  components/dm/command/edit_config.go
Labels: status/can-merge, status/LGT1, size/XS

#1910 cluster:fix info when restore meta
  components/dm/command/root.go
  pkg/cluster/manager/basic.go
Labels: status/can-merge, status/LGT1, size/XS

#1914 fix fillHostArchOrOS not working when using Identity
  pkg/cluster/manager/manager.go
Labels: status/can-merge, status/LGT1, size/M

#1915 bump version 1.10.1
  CHANGELOG.md
  pkg/version/version.go
Labels: size/XS

#1922 fix: fix can not get drainer status from pd
  pkg/cluster/api/binlog.go
Labels: status/can-merge, status/LGT1, size/XS

#1925 cluster: fix cannot check time zone
  pkg/cluster/manager/check.go
Labels: status/can-merge, status/LGT1, size/M

#1926 dm: fix peer-urls of dm-master
  embed/templates/scripts/run_dm-master.sh.tpl
  embed/templates/scripts/run_dm-master_scale.sh.tpl
Labels: status/can-merge, status/LGT1, size/XS

#1929 bump version 1.10.2
  CHANGELOG.md
  pkg/version/version.go
Labels: status/can-merge, status/LGT1, size/S

#1931 playground: add pd.port argument
  components/playground/instance/pd.go
  components/playground/main.go
  components/playground/playground.go
  go.mod
  go.sum
Labels: status/can-merge, status/LGT1, size/M

#1928 README: a mis-spelling of `TiUp`
  README.md
Labels: status/can-merge, status/LGT1, size/XS

#1933 playground: don't get Pid() when there is no Process
  components/playground/playground.go
Labels: status/can-merge, status/LGT1, size/S
