Repository pingcap/tiup, pull requests merged in 2022-10, with the labels that each got.

#2055 move tiup bench to standalone repo
  .github/workflows/integrate-cluster-cmd.yaml
  .github/workflows/integrate-cluster-scale.yaml
  .github/workflows/integrate-dm.yaml
  .github/workflows/integrate-playground.yaml
  .github/workflows/release-tiup.yaml
  Makefile
  components/bench/Makefile
  components/bench/README.md
  components/bench/ch_benchmark.go
  components/bench/go.mod
  components/bench/go.sum
  components/bench/main.go
  components/bench/misc.go
  components/bench/tpcc.go
  components/bench/tpch.go
  components/bench/ycsb.go
  components/client/Makefile
  doc/user/bench.md
  pkg/cluster/manager/check.go
Labels: status/can-merge, status/LGT1, size/XXL

#2051 wait for leader to transfer back during rolling restart
  pkg/cluster/api/pdapi.go
  pkg/cluster/spec/tikv.go
Labels: type/enhancement, status/can-merge, category/stability, status/LGT1, size/L, component/cluster

#2054 Check required CPU flags for TiFlash >= v6.3.0
  embed/templates/scripts/run_tiflash.sh.tpl
  pkg/cluster/spec/spec_test.go
  pkg/cluster/spec/tiflash.go
  pkg/cluster/template/scripts/tiflash.go
  pkg/tidbver/tidbver.go
Labels: status/can-merge, status/LGT1, size/M

#2041 cluster: add support for displaying the grafana URLs in JSON output.
  pkg/cluster/manager/display.go
Labels: status/can-merge, status/LGT1, size/M

#2063 cluster/api: sync pdapi & typeutil with pd 6.3.0
  go.mod
  go.sum
  pkg/cluster/api/types.go
  pkg/cluster/api/typeutil/size.go
  pkg/cluster/api/typeutil/size_test.go
  pkg/cluster/manager/display.go
Labels: status/can-merge, status/LGT1, size/L
