Repository pingcap/tiup, pull requests merged in 2022-09, with the labels that each got.

#2021 server: fix not delete tmp file when upload package
  server/handler/tarball.go
  tools/check/golangci.yaml
Labels: status/can-merge, status/LGT1, size/XS

#2036 cdc: retry on resign the owner, if old owner in power again.
  pkg/cluster/api/cdcapi.go
  pkg/cluster/spec/cdc.go
Labels: status/can-merge, status/LGT1, size/S

#2033 *: upgrade to go1.19
  .github/workflows/install.yaml
  .github/workflows/integrate-cluster-cmd.yaml
  .github/workflows/integrate-cluster-scale.yaml
  .github/workflows/integrate-dm.yaml
  .github/workflows/integrate-playground.yaml
  .github/workflows/integrate-tiup.yaml
  .github/workflows/release-tiup.yaml
  .github/workflows/reprotest.yaml
  Makefile
  components/cluster/command/audit.go
  go.mod
  go.sum
  pkg/cluster/api/dmpb/dmmaster.pb.go
  pkg/cluster/api/dmpb/dmworker.pb.go
  pkg/cluster/executor/checkpoint.go
  pkg/cluster/spec/grafana_test.go
  pkg/cluster/spec/server_config.go
  pkg/cluster/task/update_topology.go
  pkg/cluster/template/scripts/pd_test.go
  pkg/repository/store/txn.go
  pkg/tidbver/tidbver.go
  pkg/tui/progress/renderer.go
  tools/check/golangci.yaml
Labels: status/can-merge, status/LGT1, size/XL

#2042 cluster: support TiCDC cluster id
  embed/templates/scripts/run_cdc.sh.tpl
  pkg/cluster/spec/cdc.go
  pkg/cluster/template/scripts/cdc.go
  pkg/tidbver/tidbver.go
Labels: status/can-merge, status/LGT1, size/S

#1994 cluster: display memory usage
  components/cluster/command/display.go
  components/dm/command/display.go
  pkg/cluster/manager/display.go
  pkg/cluster/operation/action.go
  pkg/cluster/operation/check.go
  pkg/cluster/operation/operation.go
  pkg/cluster/operation/systemd.go
  pkg/cluster/spec/instance.go
  pkg/cluster/task/action.go
Labels: status/can-merge, status/LGT1, size/L

#2032 playground: fix redundant log
  components/playground/playground.go
Labels: status/can-merge, status/LGT1, size/XS

#2017 cluster: add tidb dashboard
  embed/examples/cluster/topology.example.yaml
  embed/templates/scripts/run_tidb-dashboard.sh.tpl
  pkg/cluster/ansible/import_test.go
  pkg/cluster/ansible/test-data/meta.yaml
  pkg/cluster/spec/dashboard.go
  pkg/cluster/spec/instance.go
  pkg/cluster/spec/spec.go
  pkg/cluster/spec/validate.go
  pkg/cluster/task/update_meta.go
  pkg/cluster/template/scripts/dashboard.go
Labels: status/can-merge, status/LGT1, size/XL

#2045 cluster: fix timezone check and remove duplicate cleanTasks
  pkg/cluster/manager/check.go
Labels: status/can-merge, status/LGT1, size/XL

#2046 bump version 1.11.0
  CHANGELOG.md
  pkg/version/version.go
Labels: status/can-merge, status/LGT1, size/M

#2047 cluster: fix service check
  pkg/cluster/operation/check.go
  pkg/cluster/operation/systemd.go
Labels: status/can-merge, status/LGT1, size/S
