Repository pingcap/tiup, pull requests merged in 2022-12, with the labels that each got.

#2077 playground: Enable AutoTLS by default
  components/playground/instance/tidb.go
  components/playground/playground.go
Labels: status/can-merge, category/security, status/LGT1, size/S, component/playground

#2099 test: pin github action image
  .github/workflows/install.yaml
  .github/workflows/integrate-cluster-cmd.yaml
  .github/workflows/integrate-cluster-scale.yaml
  .github/workflows/integrate-dm.yaml
  .github/workflows/integrate-playground.yaml
  .github/workflows/integrate-tiup.yaml
  .github/workflows/release-tiup.yaml
  .github/workflows/reprotest.yaml
  tests/tiup-cluster/script/tikv_cdc.sh
Labels: status/can-merge, status/LGT1, size/S

#2094 cluster:support display tiflash uptime
  pkg/cluster/spec/tiflash.go
Labels: status/can-merge, status/LGT1, size/XS
