Repository pingcap/tiup, pull requests merged in 2022-11, with the labels that each got.

#2059 cdc: before drain the capture, check the capture can be found
  pkg/cluster/api/cdcapi.go
  pkg/cluster/spec/cdc.go
Labels: status/can-merge, status/LGT1, size/M

#2068 fix prometheus config template
  embed/templates/config/prometheus.yml.tpl
Labels: status/can-merge, status/LGT1, size/S

#2069 Ipv6 use join host port
  components/cluster/command/start.go
  components/cluster/command/test.go
  components/dm/ansible/import.go
  components/dm/spec/topology_dm.go
  components/playground/instance/drainer.go
  components/playground/instance/instance.go
  components/playground/instance/pd.go
  components/playground/instance/pump.go
  components/playground/instance/ticdc.go
  components/playground/instance/tidb.go
  components/playground/instance/tiflash.go
  components/playground/instance/tikv.go
  components/playground/instance/tikv_cdc.go
  components/playground/monitor.go
  components/playground/ngmonitoring.go
  components/playground/playground.go
  pkg/cluster/manager/check.go
  pkg/cluster/manager/display.go
  pkg/cluster/manager/exec.go
  pkg/cluster/spec/cdc.go
  pkg/cluster/spec/instance.go
  pkg/cluster/spec/pd.go
  pkg/cluster/spec/spec.go
  pkg/cluster/spec/tiflash.go
  pkg/cluster/spec/tikv.go
  pkg/cluster/spec/tikv_cdc.go
  pkg/cluster/spec/tispark.go
  pkg/cluster/spec/util.go
  pkg/cluster/task/update_topology.go
  pkg/cluster/template/config/ngmonitoring.go
  pkg/cluster/template/config/prometheus.go
  pkg/cluster/template/scripts/pd.go
  pkg/cluster/template/scripts/tikv.go
  pkg/utils/freeport.go
  pkg/utils/utils.go
Labels: status/can-merge, status/LGT1, size/L

#2019 pd: set madvdontneed=1 to shrink RSS after GC
  embed/templates/scripts/run_pd.sh.tpl
  embed/templates/scripts/run_pd_scale.sh.tpl
Labels: status/can-merge, status/LGT1, size/XS

#2071 support config scrape_interval and scrape_timeout for prometheus
  embed/examples/cluster/topology.example.yaml
  embed/templates/config/prometheus.yml.tpl
  pkg/cluster/spec/monitoring.go
  pkg/cluster/template/config/prometheus.go
Labels: status/can-merge, status/LGT1, size/S

#2070 refactor scripts package to support ipv6
  embed/templates/scripts/run_alertmanager.sh.tpl
  embed/templates/scripts/run_cdc.sh.tpl
  embed/templates/scripts/run_drainer.sh.tpl
  embed/templates/scripts/run_grafana.sh.tpl
  embed/templates/scripts/run_pd.sh.tpl
  embed/templates/scripts/run_pd_scale.sh.tpl
  embed/templates/scripts/run_prometheus.sh.tpl
  embed/templates/scripts/run_pump.sh.tpl
  embed/templates/scripts/run_tidb-dashboard.sh.tpl
  embed/templates/scripts/run_tidb.sh.tpl
  embed/templates/scripts/run_tikv-cdc.sh.tpl
  embed/templates/scripts/run_tikv.sh.tpl
  pkg/cluster/spec/alertmanager.go
  pkg/cluster/spec/cdc.go
  pkg/cluster/spec/dashboard.go
  pkg/cluster/spec/drainer.go
  pkg/cluster/spec/grafana.go
  pkg/cluster/spec/instance.go
  pkg/cluster/spec/monitoring.go
  pkg/cluster/spec/monitoring_test.go
  pkg/cluster/spec/pd.go
  pkg/cluster/spec/pump.go
  pkg/cluster/spec/spec.go
  pkg/cluster/spec/spec_test.go
  pkg/cluster/spec/tidb.go
  pkg/cluster/spec/tiflash.go
  pkg/cluster/spec/tikv.go
  pkg/cluster/spec/tikv_cdc.go
  pkg/cluster/spec/tispark.go
  pkg/cluster/template/scripts/alertmanager.go
  pkg/cluster/template/scripts/cdc.go
  pkg/cluster/template/scripts/dashboard.go
  pkg/cluster/template/scripts/drainer.go
  pkg/cluster/template/scripts/grafana.go
  pkg/cluster/template/scripts/monitoring.go
  pkg/cluster/template/scripts/monitoring_test.go
  pkg/cluster/template/scripts/pd.go
  pkg/cluster/template/scripts/pd_test.go
  pkg/cluster/template/scripts/pump.go
  pkg/cluster/template/scripts/tidb.go
  pkg/cluster/template/scripts/tiflash.go
  pkg/cluster/template/scripts/tikv.go
  pkg/cluster/template/scripts/tikv_cdc.go
  pkg/tidbver/tidbver.go
Labels: status/can-merge, status/LGT1, size/XXL

#2073 component/playground: rm the restriction that tikv num must be greater than 0
  components/playground/playground.go
Labels: status/can-merge, status/LGT1, size/XS

#2076 playground: fix panic
  components/playground/playground.go
Labels: status/can-merge, status/LGT1, size/S

#2079 cluster: mark kylin v10 as supported OS
  pkg/cluster/operation/check.go
Labels: status/can-merge, status/LGT1, size/XS

#2081 ctl: Set ETCDCTL_API=v3 to get the v3 API
  components/ctl/main.go
Labels: status/can-merge, status/LGT1, size/XS

#2082 cluster: avoid redirect when grafana set root_url
  pkg/cluster/spec/grafana.go
Labels: status/can-merge, status/LGT1, size/XS

#2088 bump to v1.11.1
  CHANGELOG.md
  pkg/version/version.go
Labels: status/can-merge, status/LGT1, size/S

#2075 modify config template to support ipv6
  embed/templates/config/datasource.yml.tpl
  embed/templates/config/ngmonitoring.toml.tpl
  pkg/cluster/spec/grafana.go
  pkg/cluster/spec/monitoring.go
  pkg/cluster/spec/spec.go
  pkg/cluster/template/config/datasource.go
  pkg/cluster/template/config/ngmonitoring.go
  pkg/cluster/template/scripts/pd.go
Labels: status/can-merge, status/LGT1, size/L
