Repository pingcap/tiup, pull requests merged in 2022-04, with the labels that each got.

#1832 tiup: fix print duplicated component path
  pkg/exec/run.go
Labels: status/can-merge, status/LGT1, size/XS

#1838 cluster: enable data-dir for versions above v5.0.3
  pkg/cluster/spec/spec_test.go
  pkg/cluster/template/scripts/cdc.go
Labels: status/can-merge, status/LGT1, size/S

#1840 cluster: fix example topology url 404
  embed/examples/cluster/topology.example.yaml
Labels: status/can-merge, status/LGT1, size/XS

#1841 bump version 1.9.4
  CHANGELOG.md
  pkg/version/version.go
Labels: status/can-merge, status/LGT1, size/XS

#1843 examples: update monitoring and grafana example
  embed/examples/cluster/topology.example.yaml
  embed/examples/dm/topology.example.yaml
Labels: status/can-merge, status/LGT1, size/S

#1801 cluster/dm: support backup and restore cluster meta
  components/cluster/command/meta.go
  components/cluster/command/root.go
  components/dm/command/meta.go
  components/dm/command/root.go
  pkg/cluster/manager/basic.go
  pkg/utils/ioutil.go
Labels: status/can-merge, status/LGT1, size/L

#1808 tiup: supprot record tiup execution history
  cmd/history.go
  cmd/root.go
  go.mod
  pkg/environment/history.go
Labels: status/can-merge, status/LGT1, size/XL

#1831 tiup: refactor help
  cmd/help.go
  cmd/root.go
  pkg/repository/repository.go
Labels: status/can-merge, status/LGT1, size/XL

#1818 add altermanager config
  embed/examples/cluster/topology.example.yaml
Labels: status/can-merge, status/LGT1, size/XS

#1848 mirror: support custom key-dir when rotate root.json
  cmd/mirror.go
  cmd/root.go
  components/cluster/command/root.go
  components/dm/command/root.go
  components/playground/main.go
  pkg/environment/env.go
  pkg/repository/model/model.go
Labels: status/can-merge, status/LGT1, size/M, component/tiup

#1844 ci: support-auto-update-homebrew
  .github/workflows/release-tiup.yaml
Labels: status/can-merge, status/LGT1, size/M

#1845 dm: bind to 0.0.0.0
  embed/templates/scripts/run_dm-master.sh.tpl
  embed/templates/scripts/run_dm-master_scale.sh.tpl
  embed/templates/scripts/run_dm-worker.sh.tpl
Labels: status/can-merge, status/LGT1, size/XS

#1853 fix: exporter and grafana are abnormal in prometheus
  embed/templates/config/prometheus.yml.tpl
Labels: status/can-merge, status/LGT1, size/S

#1862 cluster: display pump/drainer server status
  pkg/cluster/manager/destroy.go
  pkg/cluster/manager/display.go
  pkg/cluster/manager/scale_in.go
  pkg/cluster/spec/drainer.go
  pkg/cluster/spec/pump.go
Labels: status/can-merge, status/LGT1, size/L
