Repository pingcap/tiup, pull requests merged in 2022-08, with the labels that each got.

#1998 playground: Fix "--tag" argument for subcommands.
  components/playground/main.go
  tests/tiup-playground/test_playground.sh
Labels: status/can-merge, status/LGT1, size/M

#2007 TiUP: Support setting CPUAffinity
  embed/templates/scripts/run_tidb.sh.tpl
  embed/templates/scripts/run_tiflash.sh.tpl
  embed/templates/scripts/run_tikv.sh.tpl
  go.mod
  go.sum
  pkg/cluster/spec/tidb.go
  pkg/cluster/spec/tiflash.go
  pkg/cluster/spec/tikv.go
  pkg/cluster/template/scripts/tidb.go
  pkg/cluster/template/scripts/tiflash.go
  pkg/cluster/template/scripts/tikv.go
Labels: status/can-merge, status/LGT1, size/M

#2014 cluster: fix THP check
  pkg/cluster/manager/check.go
  pkg/cluster/operation/check.go
Labels: status/LGT1, size/XS

#2009 update mirror clone help
  cmd/mirror.go
Labels: status/can-merge, status/LGT1, size/XS

#2008 cluster: fix cannot push to some instance
  pkg/cluster/manager/transfer.go
Labels: status/can-merge, status/LGT1, size/XS

#2005 scale-in pd leader after evict the leader
  pkg/cluster/operation/scale_in.go
  pkg/cluster/operation/upgrade.go
  pkg/cluster/spec/cdc.go
Labels: status/can-merge, status/LGT1, size/M

#2011 cluster: fix not delete tidb topo from pd when scale-in
  pkg/cluster/task/update_meta.go
Labels: status/can-merge, status/LGT1, size/M

#2016 bump version 1.10.3
  CHANGELOG.md
  pkg/version/version.go
Labels: status/can-merge, status/LGT1, size/S

#2012 cdc check healthy when rolling upgrade
  pkg/cluster/api/cdcapi.go
  pkg/cluster/manager/patch.go
  pkg/cluster/manager/reload.go
  pkg/cluster/manager/upgrade.go
  pkg/cluster/operation/scale_in.go
  pkg/cluster/operation/upgrade.go
  pkg/cluster/spec/cdc.go
  pkg/cluster/task/action.go
  pkg/tidbver/tidbver.go
Labels: status/can-merge, status/LGT1, size/L
