Repository pingcap/tiup, pull requests merged in 2022-07, with the labels that each got.

#1984 fix: typo
  doc/user/README.md
Labels: status/can-merge, status/LGT1, size/XS

#1978 playground: fix ineffectiveness of ticdc.config
  components/playground/instance/ticdc.go
Labels: status/can-merge, status/LGT1, size/XS

#1991 cluster: unable to configure tiflash LearnerConfig
  pkg/cluster/spec/tiflash.go
Labels: status/can-merge, status/LGT1, size/XS

#1972 cdc rolling upgrade / scale-in ultilize two-phase-scheduling
  components/cluster/command/patch.go
  components/cluster/command/reload.go
  components/cluster/command/scale_in.go
  components/cluster/command/upgrade.go
  components/dm/command/scale_in.go
  go.mod
  go.sum
  pkg/cluster/api/cdcapi.go
  pkg/cluster/api/pdapi.go
  pkg/cluster/manager/scale_in.go
  pkg/cluster/operation/action.go
  pkg/cluster/operation/destroy.go
  pkg/cluster/operation/scale_in.go
  pkg/cluster/operation/upgrade.go
  pkg/cluster/spec/bindversion.go
  pkg/cluster/spec/cdc.go
  pkg/cluster/spec/spec.go
  pkg/utils/http_client.go
Labels: status/can-merge, status/LGT1, size/XXL

#1996 cdc rolling upgrade remove status check to prevent false detection.
  pkg/cluster/api/cdcapi.go
  pkg/cluster/spec/cdc.go
Labels: status/can-merge, status/LGT1, size/S
