Repository pingcap/tiup, pull requests merged in 2022-03, with the labels that each got.

#1774 fix --ignore-config-check not working for deploy
  components/cluster/command/deploy.go
  pkg/cluster/api/dmpb/dmmaster.pb.go
  pkg/cluster/api/dmpb/dmworker.pb.go
  pkg/cluster/manager/deploy.go
Labels: status/can-merge, status/LGT1, size/M

#1776 cluster: change initial_commit_ts to initial-commit-ts
  pkg/cluster/ansible/service.go
  pkg/cluster/spec/spec.go
Labels: status/can-merge, status/LGT1, size/S

#1775 cluster: check active before reload promtheus when scale-in/scale-out
  pkg/cluster/manager/builder.go
  pkg/cluster/manager/check.go
  pkg/cluster/manager/destroy.go
  pkg/cluster/manager/scale_in.go
  pkg/cluster/module/systemd.go
  pkg/cluster/task/builder.go
  pkg/cluster/task/systemd.go
Labels: status/can-merge, status/LGT1, size/M

#1778 *: support save audit to specified file
  pkg/cluster/audit/audit.go
  pkg/cluster/audit/audit_test.go
  pkg/logger/audit.go
Labels: status/can-merge, status/LGT1, size/S

#1784 utils: support symlink when untar
  pkg/utils/ioutil.go
Labels: status/can-merge, status/LGT1, size/S

#1780 *: support cleanup audit logs
  components/cluster/command/audit.go
  components/dm/command/audit.go
  pkg/cluster/audit/audit.go
Labels: status/can-merge, status/LGT1, size/L

#1777 Update README.md
  doc/user/README.md
Labels: status/can-merge, status/LGT1, size/M

#1786 fix: Add Oracle Linux 2 as supported OS
  pkg/cluster/operation/check.go
Labels: status/can-merge, status/LGT1, size/XS

#1788 bump version 1.9.2
  CHANGELOG.md
  pkg/version/version.go
Labels: size/S

#1791 There is no `Oracle Linux 2`
  CHANGELOG.md
Labels: status/can-merge, status/LGT1, size/XS

#1789 cluster: support evict leaders on stop and restore on start
  components/cluster/command/audit.go
  components/cluster/command/start.go
  components/cluster/command/stop.go
  components/dm/command/audit.go
  components/dm/command/scale_in.go
  components/dm/command/start.go
  components/dm/command/stop.go
  pkg/cluster/audit/audit.go
  pkg/cluster/manager/basic.go
  pkg/cluster/manager/builder.go
  pkg/cluster/manager/cleanup.go
  pkg/cluster/manager/destroy.go
  pkg/cluster/operation/action.go
  pkg/cluster/operation/destroy.go
  pkg/cluster/operation/operation.go
  pkg/cluster/task/action.go
Labels: status/can-merge, status/LGT1, size/L

#1794 cluster: fix cannot use exec command when hostname contain '-'
  pkg/cluster/manager/exec.go
Labels: status/can-merge, status/LGT1, size/XS

#1798 pdapi: fix loss of precision on GetClusterID()
  pkg/cluster/api/pdapi.go
Labels: status/can-merge, status/LGT1, size/S

#1802 *: bump go 1.18
  .github/workflows/install.yaml
  .github/workflows/integrate-cluster-cmd.yaml
  .github/workflows/integrate-cluster-scale.yaml
  .github/workflows/integrate-dm.yaml
  .github/workflows/integrate-playground.yaml
  .github/workflows/integrate-tiup.yaml
  .github/workflows/release-tiup.yaml
  .github/workflows/reprotest.yaml
  Makefile
  components/playground/playground.go
  go.mod
  pkg/cluster/operation/action.go
  pkg/cluster/spec/instance.go
  pkg/cluster/task/init_config.go
Labels: status/can-merge, status/LGT1, size/M

#1785 add grafana embedding config
  embed/examples/dm/minimal.yaml
  embed/examples/dm/topology.example.yaml
Labels: status/can-merge, status/LGT1, size/XS

#1805 cluster: fix port conflict check for tiflash instances
  pkg/cluster/spec/validate.go
  pkg/cluster/spec/validate_test.go
Labels: status/can-merge, status/LGT1, size/M

#1806 cluster: add ngm metrics to promtheus config
  embed/templates/config/prometheus.yml.tpl
  pkg/cluster/ansible/inventory.go
  pkg/cluster/spec/monitoring.go
  pkg/cluster/template/config/prometheus.go
Labels: size/L

#1811 playground: fix cannot bind 0.0.0.0
  components/playground/instance/tiflash.go
  components/playground/instance/tiflash_config.go
  components/playground/instance/tiflash_proxy_config.go
  components/playground/playground.go
Labels: status/can-merge, status/LGT1, size/S

#1810 bump version 1.9.3
  CHANGELOG.md
  pkg/version/version.go
Labels: size/S

#1812 remove preceding spaces from commands so they are not omitted from shell history
  index.html
Labels: status/LGT1, size/XS

#1815 removed leading and trailing spaces from code blocks
  index.html
Labels: status/can-merge, status/LGT1, size/XS

#1816 playground: fix cp error when encountered readonly files
  components/playground/playground.go
Labels: status/can-merge, status/LGT1, size/XS

#1803 cluster: try to disable swap when `check --apply`
  pkg/cluster/manager/check.go
  pkg/cluster/operation/check.go
Labels: status/can-merge, status/LGT1, size/S

#1814 *: remove unused files
  CNAME
  CONTRIBUTING.md
  index.html
  staticcheck.conf
Labels: size/M

#1824 bench: fix the typo in the error message of bench command
  components/bench/ch_benchmark.go
  components/bench/tpcc.go
  components/bench/tpch.go
Labels: status/can-merge, status/LGT1, size/XS

#1819 cluster: display grafana URL on the top
  pkg/cluster/manager/display.go
  pkg/cluster/manager/display_test.go
Labels: status/can-merge, status/LGT1, size/M
