Repository pingcap/tiup, pull requests merged in 2023-08, with the labels that each got.

#2238 fix ut
  pkg/repository/testdata/manifests/root.json
  pkg/repository/testdata/polluted/bin/root.json
  pkg/repository/v1manifest/testdata/polluted/bin/root.json
Labels: size/XS, lgtm, approved

#2242 update doc links on topology example
  embed/examples/cluster/minimal.yaml
  embed/examples/cluster/topology.example.yaml
  pkg/cluster/spec/testdata/topology_err.yaml
  tests/tiup-cluster/root.json
  tests/tiup-dm/root.json
Labels: size/S, lgtm, approved

#2236 Component source
  components/dm/spec/logic.go
  components/dm/spec/topology_dm.go
  pkg/cluster/manager/builder.go
  pkg/cluster/manager/deploy.go
  pkg/cluster/manager/upgrade.go
  pkg/cluster/spec/alertmanager.go
  pkg/cluster/spec/cdc.go
  pkg/cluster/spec/dashboard.go
  pkg/cluster/spec/drainer.go
  pkg/cluster/spec/instance.go
  pkg/cluster/spec/monitoring.go
  pkg/cluster/spec/pd.go
  pkg/cluster/spec/pump.go
  pkg/cluster/spec/server_config.go
  pkg/cluster/spec/tidb.go
  pkg/cluster/spec/tiflash.go
  pkg/cluster/spec/tikv.go
  pkg/cluster/spec/tikv_cdc.go
  pkg/cluster/task/builder.go
Labels: size/L, lgtm, approved

#2251 cluster: fix node filter on exec
  pkg/cluster/manager/exec.go
Labels: size/XS, lgtm, approved

#2249 Move to Go 1.21
  .github/workflows/install.yaml
  .github/workflows/integrate-cluster-cmd.yaml
  .github/workflows/integrate-cluster-scale.yaml
  .github/workflows/integrate-dm.yaml
  .github/workflows/integrate-playground.yaml
  .github/workflows/integrate-tiup.yaml
  .github/workflows/release-tiup.yaml
  .github/workflows/reprotest.yaml
  Makefile
  components/client/go.mod
  components/client/go.sum
  doc/dev/README.md
  go.mod
  go.sum
  tools/check/go.mod
  tools/check/go.sum
  tools/check/revive.toml
Labels: size/XL, lgtm, approved

#2255 Fix the issue meta backup is failed when symbolic links exist in meta dir.
  pkg/cluster/manager/patch.go
  pkg/utils/ioutil.go
Labels: size/S, lgtm, approved

#2256 cluster: not abort destroy if cannot delete files
  pkg/cluster/operation/destroy.go
Labels: size/M, lgtm, approved

#2257 dm: fix cannot deploy grafana and prometheus
  pkg/cluster/spec/grafana.go
  pkg/cluster/spec/monitoring.go
  pkg/cluster/spec/util.go
Labels: size/S, lgtm, approved

#2253 Upgrade TiCDC before TiKV and PD when cluster is equal or greater than v5.1.0
  components/dm/spec/logic.go
  pkg/cluster/manager/check.go
  pkg/cluster/manager/upgrade.go
  pkg/cluster/operation/upgrade.go
  pkg/cluster/spec/spec.go
  pkg/cluster/spec/spec_manager_test.go
  pkg/tidbver/tidbver.go
Labels: size/M, lgtm, approved

#2202 playground: add tiproxy
  components/playground/command.go
  components/playground/instance/tiproxy.go
  components/playground/main.go
  components/playground/playground.go
  go.mod
  go.sum
  pkg/cluster/spec/instance.go
Labels: size/L, lgtm, approved

#2262 playground: refine ready message
  components/playground/main.go
  components/playground/playground.go
Labels: size/XS, lgtm, approved

#2258 RFC: Support Run Component without TiUP
  doc/rfcs/0002-support-run-component-without-tiup.md
Labels: size/S, lgtm

#2265 tiup: support run components without tiup
  cmd/link.go
  cmd/root.go
  cmd/unlink.go
  pkg/environment/env.go
Labels: size/L, lgtm

#2266 bump version to v1.13.0
  CHANGELOG.md
  pkg/version/version.go
Labels: size/S, lgtm
