Repository pingcap/tiup, pull requests merged in 2023-09, with the labels that each got.

#2269 mirror: increase publish timeout
  pkg/repository/mirror.go
Labels: size/XS, lgtm

#2272 fix pd microservice component id
  components/playground/playground.go
Labels: size/XS, lgtm, approved

#2277 grafana for Multiple instances of the same host
  pkg/cluster/spec/grafana.go
Labels: size/XS, lgtm, approved

#2285 add cdn workaround
  pkg/repository/mirror.go
Labels: size/XS, lgtm, approved

#2282 cluster/dm: support ignore version check when upgrade
  components/cluster/command/upgrade.go
  components/dm/command/upgrade.go
  pkg/cluster/manager/upgrade.go
Labels: size/S, lgtm, approved

#2284 mirror: fix progress bar is not accurate
  pkg/repository/mirror.go
  pkg/repository/progress.go
Labels: size/XS, lgtm, approved
