Repository pingcap/tiup, pull requests merged in 2023-10, with the labels that each got.

#2287 Support tidb upgrade api
  pkg/cluster/api/tidbapi.go
  pkg/cluster/manager/patch.go
  pkg/cluster/manager/reload.go
  pkg/cluster/manager/upgrade.go
  pkg/cluster/operation/upgrade.go
  pkg/tidbver/tidbver.go
Labels: size/L, lgtm, approved

#2289 update tidbver.TiDBSupportUpgradeAPI
  pkg/cluster/manager/patch.go
  pkg/cluster/manager/reload.go
  pkg/cluster/manager/upgrade.go
  pkg/cluster/operation/upgrade.go
  pkg/tidbver/tidbver.go
Labels: size/S, approved

#2290 show more retry error message
  pkg/utils/retry.go
Labels: size/XS, lgtm, approved

#2271 cluster: support tiproxy
  embed/templates/config/prometheus.yml.tpl
  embed/templates/scripts/run_tiproxy.sh.tpl
  pkg/cluster/ansible/import_test.go
  pkg/cluster/ansible/test-data/meta.yaml
  pkg/cluster/spec/bindversion.go
  pkg/cluster/spec/monitoring.go
  pkg/cluster/spec/spec.go
  pkg/cluster/spec/tiproxy.go
  pkg/cluster/task/update_meta.go
  pkg/cluster/template/config/prometheus.go
  pkg/cluster/template/scripts/tiproxy.go
Labels: size/XL, lgtm, approved

#2295 add a new flag '--numa' to show numa in display command
  components/cluster/command/display.go
  pkg/cluster/manager/display.go
  pkg/cluster/spec/alertmanager.go
  pkg/cluster/spec/cdc.go
  pkg/cluster/spec/dashboard.go
  pkg/cluster/spec/drainer.go
  pkg/cluster/spec/grafana.go
  pkg/cluster/spec/instance.go
  pkg/cluster/spec/monitoring.go
  pkg/cluster/spec/pd.go
  pkg/cluster/spec/pump.go
  pkg/cluster/spec/tidb.go
  pkg/cluster/spec/tiflash.go
  pkg/cluster/spec/tikv.go
  pkg/cluster/spec/tikv_cdc.go
  pkg/cluster/spec/tiproxy.go
  pkg/cluster/spec/tispark.go
Labels: size/M, lgtm, approved

#2296 use port to probe db in playground
  components/playground/main.go
Labels: size/S, approved

#2273 Support scheduling service
  components/playground/instance/instance.go
  components/playground/instance/pd.go
  components/playground/main.go
  components/playground/playground.go
Labels: size/L, lgtm, approved
