Repository pingcap/tiup, pull requests merged in 2023-04, with the labels that each got.

#2158 fix TiUP version
  pkg/version/version.go
Labels: status/can-merge, status/LGT1, size/XS

#2162 playground: Run TiFlash via args
  components/playground/instance/tiflash.go
  components/playground/instance/tiflash_config.go
  components/playground/instance/tiflash_proxy_config.go
  components/playground/instance/tikv.go
  pkg/tidbver/tidbver.go
Labels: status/can-merge, status/LGT1, size/M

#2161 cluster: Allows setting other storage config for TiFlash when `storage.main` is not defined
  pkg/cluster/spec/parse_topology_test.go
  pkg/cluster/spec/tiflash.go
Labels: status/can-merge, status/LGT1, size/M

#2174 cluster: remove : on default backup filename
  components/cluster/command/meta.go
Labels: status/can-merge, status/LGT1, size/XS

#2165 *: remove TiFlash http service
  components/playground/instance/tiflash.go
  components/playground/instance/tiflash_config.go
  components/playground/playground.go
  embed/examples/cluster/minimal.yaml
  embed/examples/cluster/multi-dc.yaml
  embed/examples/cluster/topology.example.yaml
  pkg/cluster/ansible/inventory.go
  pkg/cluster/ansible/service_test.go
  pkg/cluster/ansible/test-data/meta.yaml
  pkg/cluster/spec/testdata/topology_err.yaml
  pkg/cluster/spec/tiflash.go
  pkg/telemetry/testdata/single/nilvalue.yaml
  pkg/tidbver/tidbver.go
  tools/check/golangci.yaml
Labels: status/can-merge, status/LGT1, size/M

#2175 cluster: fix ngm config
  embed/templates/config/ngmonitoring.toml.tpl
  pkg/cluster/spec/monitoring.go
  pkg/cluster/template/config/ngmonitoring.go
Labels: status/can-merge, status/LGT1, size/XS

#2178 playground: Code refine for args
  components/playground/main.go
  components/playground/playground.go
Labels: status/can-merge, status/LGT1, size/XL

#2177 playground: Code refine for TiFlash
  components/playground/instance/tiflash.go
  components/playground/instance/tiflash_pre7.go
  components/playground/instance/tiflash_pre7_config.go
  components/playground/instance/tiflash_pre7_proxy_config.go
  pkg/tidbver/tidbver.go
Labels: status/can-merge, status/LGT1, size/XL

#2180 fix cannot prune/scale-in tikv when use ipv6
  pkg/cluster/api/pdapi.go
  pkg/cluster/operation/destroy.go
  pkg/cluster/operation/scale_in.go
  pkg/cluster/operation/upgrade.go
  pkg/cluster/spec/drainer.go
  pkg/cluster/spec/pump.go
  pkg/cluster/spec/validate.go
  pkg/utils/utils.go
Labels: status/can-merge, status/LGT1, size/M

#2187 playground: include '--comments' in mysql command line arguments
  components/playground/playground.go
Labels: status/can-merge, status/LGT1, size/XS

#2188 playground: fix port conflict when cluster version >= 5.4 and < 7.1
  components/playground/instance/tiflash_pre7_config.go
Labels: status/can-merge, status/LGT1, size/XS

#2189 playground: Fix --tiflash 0 not working
  components/playground/main.go
Labels: status/can-merge, status/LGT1, size/S

#2183 Playground: Option to specify TiKV port
  components/playground/instance/tikv.go
  components/playground/main.go
  components/playground/playground.go
Labels: status/can-merge, status/LGT1, size/S

#2193 cluster: fix exec
  pkg/cluster/manager/exec.go
Labels: status/can-merge, status/LGT1, size/XS

#2192 publish nightly package
  .github/workflows/release-tiup.yaml
Labels: status/can-merge, status/LGT1, size/S
