Repository pingcap/tiup, pull requests merged in 2023-11, with the labels that each got.

#2298 not cache the output of `ss -tln` command when checking wether components are started/stopped
  pkg/cluster/api/tidbapi.go
  pkg/cluster/executor/executor.go
  pkg/cluster/module/wait_for.go
Labels: size/S, lgtm

#2299 playground: fix tiproxy metrics addr
  components/playground/instance/instance.go
  components/playground/instance/tiproxy.go
  components/playground/monitor.go
  components/playground/playground.go
Labels: size/M, lgtm, approved

#2301 improve install.sh and release ci
  .github/workflows/release-tiup.yaml
  install.sh
Labels: size/XS, lgtm, approved

#2264 cluster: support use different component versions
  components/cluster/command/display.go
  components/cluster/command/root.go
  components/cluster/command/upgrade.go
  components/dm/command/root.go
  components/dm/command/upgrade.go
  components/dm/spec/bindversion.go
  components/dm/spec/logic.go
  pkg/cluster/manager/builder.go
  pkg/cluster/manager/check.go
  pkg/cluster/manager/deploy.go
  pkg/cluster/manager/display.go
  pkg/cluster/manager/manager.go
  pkg/cluster/manager/patch.go
  pkg/cluster/manager/upgrade.go
  pkg/cluster/spec/alertmanager.go
  pkg/cluster/spec/bindversion.go
  pkg/cluster/spec/cdc.go
  pkg/cluster/spec/dashboard.go
  pkg/cluster/spec/drainer.go
  pkg/cluster/spec/grafana.go
  pkg/cluster/spec/instance.go
  pkg/cluster/spec/monitoring.go
  pkg/cluster/spec/pd.go
  pkg/cluster/spec/pump.go
  pkg/cluster/spec/server_config.go
  pkg/cluster/spec/spec.go
  pkg/cluster/spec/tidb.go
  pkg/cluster/spec/tiflash.go
  pkg/cluster/spec/tikv.go
  pkg/cluster/spec/tikv_cdc.go
  pkg/cluster/spec/tiproxy.go
  pkg/cluster/spec/tispark.go
  pkg/cluster/task/builder.go
Labels: size/XXL, lgtm, approved

#2303 cluster/dm: add gloabl listen_host
  components/dm/spec/logic.go
  embed/examples/cluster/minimal.yaml
  embed/examples/cluster/multi-dc.yaml
  embed/examples/cluster/topology.example.yaml
  pkg/cluster/spec/alertmanager.go
  pkg/cluster/spec/cdc.go
  pkg/cluster/spec/dashboard.go
  pkg/cluster/spec/drainer.go
  pkg/cluster/spec/grafana.go
  pkg/cluster/spec/monitoring.go
  pkg/cluster/spec/pd.go
  pkg/cluster/spec/pump.go
  pkg/cluster/spec/spec.go
  pkg/cluster/spec/tidb.go
  pkg/cluster/spec/tiflash.go
  pkg/cluster/spec/tikv.go
  pkg/cluster/spec/tikv_cdc.go
  pkg/cluster/spec/tiproxy.go
Labels: size/S, lgtm, approved

#2304 cluster: fix tidb-dashboard listen_host
  embed/templates/scripts/run_tidb-dashboard.sh.tpl
  pkg/cluster/spec/dashboard.go
  pkg/cluster/template/scripts/dashboard.go
Labels: size/XS, lgtm, approved

#2305 tiproxy not use nightly by default
  components/playground/main.go
  components/playground/playground.go
  pkg/cluster/spec/tiproxy.go
Labels: size/XS, lgtm, approved

#2246 upgrade go-sql-driver/mysql version to v1.7.1
  components/client/go.mod
  components/client/go.sum
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2306 allow to set component version when scale-out
  pkg/cluster/spec/spec.go
Labels: size/M, lgtm, approved

#2308 Revert "OWNERS: Auto Sync OWNERS files from community membership"
  OWNERS
Labels: size/S

#2309 Mirror clone err
  cmd/mirror.go
  pkg/cluster/spec/bindversion.go
  pkg/repository/clone_mirror.go
Labels: size/L, lgtm, approved

#2310 playground/log: add mcs name for pd log
  components/playground/instance/pd.go
  components/playground/playground.go
Labels: size/XS, lgtm, approved

#2311 mirror: return err if specified latest not found when clone mirror
  pkg/repository/clone_mirror.go
Labels: size/S, lgtm, approved

#2312 fix typo
  pkg/cluster/manager/display.go
Labels: size/XS, approved

#2313 playground: Fix alignment of output
  components/playground/playground.go
Labels: size/XS, approved

#2318 playground: make sure to signal tiproxy to stop
  components/playground/playground.go
Labels: size/XS, lgtm, approved

#2316 Change revive cognitive-complexity settings
  .github/workflows/lint.yaml
  components/dm/ansible/import.go
  pkg/cluster/ansible/inventory.go
  pkg/cluster/ansible/service.go
  pkg/cluster/operation/scale_in.go
  tools/check/revive.toml
Labels: size/M, lgtm, approved

#2010 RFC: Separate Component Version in Cluster
  doc/rfcs/0001-separate-component-version-in-cluster.md
  pkg/cluster/spec/spec.go
Labels: size/M

#2322 bump version to v1.14.0
  CHANGELOG.md
  pkg/version/version.go
Labels: size/M, lgtm, approved
