Repository pingcap/tiup, pull requests merged in 2023-03, with the labels that each got.

#2132 scp: create dir before download
  components/cluster/command/import.go
  pkg/cluster/executor/local.go
  pkg/cluster/executor/ssh.go
  pkg/cluster/manager/cacert.go
  pkg/cluster/spec/profile.go
  pkg/cluster/spec/spec_manager.go
  pkg/cluster/task/tls.go
  pkg/logger/audit.go
  pkg/utils/http_client.go
  pkg/utils/ioutil.go
Labels: status/can-merge, status/LGT1, size/M

#2116 cluster: check upgrade offline
  pkg/cluster/manager/upgrade.go
Labels: status/can-merge, status/LGT1, size/M

#2124 add ticdc port prob config
  embed/templates/config/prometheus.yml.tpl
Labels: status/can-merge, status/LGT1, size/XS

#2136 cluster: delete !#$%&= from init password
  pkg/crypto/rand/passwd.go
Labels: status/can-merge, status/LGT1, size/XS

#2138 Remove mark_cache_size default value of tiflash.toml after v5.4.0
  components/playground/instance/tiflash_config.go
  pkg/cluster/ansible/service_test.go
  pkg/cluster/spec/tiflash.go
Labels: status/can-merge, status/LGT1, size/S

#2140 playground: Allow setting the TiCDC port
  components/playground/instance/ticdc.go
  components/playground/main.go
  components/playground/playground.go
Labels: status/can-merge, status/LGT1, size/S

#2133 display disaggregated mode
  pkg/cluster/manager/display.go
  pkg/cluster/spec/tiflash.go
Labels: status/can-merge, status/LGT1, size/M

#2141 clean: check process name before killing it
  cmd/clean.go
Labels: status/can-merge, status/LGT1, size/S

#2137 cluster: support connect to external Pushgateway
  embed/templates/config/prometheus.yml.tpl
  pkg/cluster/spec/monitoring.go
  pkg/cluster/template/config/prometheus.go
Labels: status/can-merge, status/LGT1, size/M

#2142 tiup cluster prune need to delete storage.remote.cache.dir
  pkg/cluster/operation/destroy.go
  pkg/cluster/spec/tiflash.go
Labels: status/can-merge, status/LGT1, size/S

#2147 cluster/dm: support set manage host
  components/cluster/command/display.go
  components/dm/command/scale_in.go
  components/dm/spec/logic.go
  components/dm/spec/topology_dm.go
  pkg/cluster/ansible/config.go
  pkg/cluster/manager/basic.go
  pkg/cluster/manager/builder.go
  pkg/cluster/manager/check.go
  pkg/cluster/manager/cleanup.go
  pkg/cluster/manager/deploy.go
  pkg/cluster/manager/display.go
  pkg/cluster/manager/exec.go
  pkg/cluster/manager/manager.go
  pkg/cluster/manager/patch.go
  pkg/cluster/manager/transfer.go
  pkg/cluster/manager/upgrade.go
  pkg/cluster/operation/action.go
  pkg/cluster/operation/check.go
  pkg/cluster/operation/destroy.go
  pkg/cluster/operation/scale_in.go
  pkg/cluster/operation/telemetry.go
  pkg/cluster/operation/upgrade.go
  pkg/cluster/spec/alertmanager.go
  pkg/cluster/spec/cdc.go
  pkg/cluster/spec/dashboard.go
  pkg/cluster/spec/drainer.go
  pkg/cluster/spec/grafana.go
  pkg/cluster/spec/instance.go
  pkg/cluster/spec/monitoring.go
  pkg/cluster/spec/pd.go
  pkg/cluster/spec/pump.go
  pkg/cluster/spec/spec.go
  pkg/cluster/spec/tidb.go
  pkg/cluster/spec/tiflash.go
  pkg/cluster/spec/tikv.go
  pkg/cluster/spec/tikv_cdc.go
  pkg/cluster/spec/tispark.go
  pkg/cluster/spec/validate.go
  pkg/cluster/task/builder.go
  pkg/cluster/task/init_config.go
  pkg/cluster/task/init_config_test.go
  pkg/cluster/task/scale_config.go
Labels: status/can-merge, status/LGT1, size/XXL

#2145 mark openEuler as supported
  pkg/cluster/operation/check.go
Labels: status/can-merge, status/LGT1, size/XS

#2150 cluster/dm: support rotate ssh key
  components/cluster/command/root.go
  components/cluster/command/rotate_ssh.go
  components/dm/command/root.go
  components/dm/command/rotate_ssh.go
  pkg/cluster/manager/rotate_ssh.go
  pkg/cluster/task/builder.go
  pkg/cluster/task/rotate_ssh.go
Labels: status/can-merge, status/LGT1, size/XL

#2117 dm: support ipv6
  components/dm/spec/logic.go
  components/dm/spec/topology_dm.go
  embed/templates/scripts/run_dm-master.sh.tpl
  embed/templates/scripts/run_dm-master_scale.sh.tpl
  embed/templates/scripts/run_dm-worker.sh.tpl
  pkg/cluster/api/dmapi.go
  pkg/cluster/operation/upgrade.go
  pkg/cluster/template/scripts/dm_master.go
  pkg/cluster/template/scripts/dm_worker.go
Labels: status/can-merge, status/LGT1, size/XL

#2153 allow detail nighlty version
  pkg/repository/v1_repository.go
Labels: status/can-merge, status/LGT1, size/XS

#2154 Release112
  CHANGELOG.md
  go.mod
  go.sum
Labels: status/can-merge, status/LGT1, size/XXL
