Repository pingcap/tiup, pull requests merged in 2023-06, with the labels that each got.

#2206 cluster: fix not use manage_host when connect to pd/cdc
  components/dm/command/scale_in.go
  components/playground/playground.go
  go.mod
  pkg/cluster/manager/display.go
  pkg/cluster/operation/scale_in.go
  pkg/cluster/operation/upgrade.go
  pkg/cluster/spec/cdc.go
  pkg/cluster/spec/pd.go
  pkg/cluster/spec/spec.go
  pkg/cluster/spec/tiflash.go
  pkg/cluster/spec/tikv_cdc.go
Labels: size/M, lgtm, approved

#2207 cluster: fix not use manage_host when connect to components again
  components/dm/command/prune.go
  components/dm/spec/topology_dm.go
  pkg/cluster/manager/check.go
  pkg/cluster/manager/display.go
  pkg/cluster/operation/destroy.go
  pkg/cluster/operation/upgrade.go
  pkg/cluster/spec/alertmanager.go
  pkg/cluster/spec/cdc.go
  pkg/cluster/spec/dashboard.go
  pkg/cluster/spec/drainer.go
  pkg/cluster/spec/grafana.go
  pkg/cluster/spec/monitoring.go
  pkg/cluster/spec/pd.go
  pkg/cluster/spec/pump.go
  pkg/cluster/spec/spec.go
  pkg/cluster/spec/tidb.go
  pkg/cluster/spec/tiflash.go
  pkg/cluster/spec/tikv.go
  pkg/cluster/spec/tikv_cdc.go
Labels: size/L, lgtm, approved

#2210 cluster: make manage_host editable
  components/dm/spec/topology_dm.go
  pkg/cluster/spec/alertmanager.go
  pkg/cluster/spec/cdc.go
  pkg/cluster/spec/dashboard.go
  pkg/cluster/spec/drainer.go
  pkg/cluster/spec/grafana.go
  pkg/cluster/spec/monitoring.go
  pkg/cluster/spec/pd.go
  pkg/cluster/spec/pump.go
  pkg/cluster/spec/tidb.go
  pkg/cluster/spec/tiflash.go
  pkg/cluster/spec/tikv.go
  pkg/cluster/spec/tikv_cdc.go
  pkg/cluster/spec/tispark.go
Labels: size/M, lgtm, approved

#2203 progress: Add option to add error detail
  pkg/tui/progress/display_props.go
  pkg/tui/progress/example_single_bar_test.go
  pkg/tui/progress/single_bar.go
Labels: size/M, approved

#2217 bump version to v1.12.3
  CHANGELOG.md
  pkg/version/version.go
Labels: size/S, approved

#2218 *: remove tcp_port for tiflash
  components/playground/instance/tiflash.go
  components/playground/instance/tiflash_pre7.go
  components/playground/instance/tiflash_pre7_config.go
  embed/examples/cluster/minimal.yaml
  embed/examples/cluster/multi-dc.yaml
  embed/examples/cluster/topology.example.yaml
  pkg/cluster/ansible/inventory.go
  pkg/cluster/ansible/service_test.go
  pkg/cluster/ansible/test-data/meta.yaml
  pkg/cluster/spec/testdata/topology_err.yaml
  pkg/cluster/spec/tiflash.go
  pkg/cluster/spec/validate.go
  pkg/telemetry/testdata/single/nilvalue.yaml
Labels: size/M, lgtm, approved

#2219 Revert "*: remove tcp_port for tiflash (#2218)"
  components/playground/instance/tiflash.go
  components/playground/instance/tiflash_pre7.go
  components/playground/instance/tiflash_pre7_config.go
  embed/examples/cluster/minimal.yaml
  embed/examples/cluster/multi-dc.yaml
  embed/examples/cluster/topology.example.yaml
  pkg/cluster/ansible/inventory.go
  pkg/cluster/ansible/service_test.go
  pkg/cluster/ansible/test-data/meta.yaml
  pkg/cluster/spec/testdata/topology_err.yaml
  pkg/cluster/spec/tiflash.go
  pkg/cluster/spec/validate.go
  pkg/telemetry/testdata/single/nilvalue.yaml
Labels: size/M, approved

#2220 *: remove tcp_port for tiflash >= 7.1.0
  components/playground/instance/tiflash.go
  components/playground/instance/tiflash_pre7_config.go
  embed/examples/cluster/minimal.yaml
  embed/examples/cluster/multi-dc.yaml
  embed/examples/cluster/topology.example.yaml
  pkg/cluster/ansible/service_test.go
  pkg/cluster/spec/tiflash.go
  pkg/tidbver/tidbver.go
Labels: size/M, lgtm, approved
