Repository pingcap/tiup, pull requests merged in 2023-01, with the labels that each got.

#2086 merge tiflash config in tiup playground to reduce handwrite config
  components/playground/command.go
  components/playground/instance/tiflash.go
  components/playground/instance/tiflash_config.go
Labels: status/can-merge, status/LGT1, size/L

#2109 improve tiup timeout message
  pkg/exec/run.go
Labels: size/XS

#2103 base52: check for invalid chars in Decode()
  pkg/base52/base52.go
  pkg/base52/base52_test.go
Labels: type/bug, status/can-merge, category/security, status/LGT1, size/S
