Repository pingcap/tiup, pull requests merged in 2023-07, with the labels that each got.

#2227 cluster: fix tiflash uptime
  pkg/cluster/manager/display.go
  pkg/cluster/operation/check.go
  pkg/cluster/operation/systemd.go
Labels: size/M, lgtm, approved

#2228 bump version to v1.12.4
  CHANGELOG.md
  pkg/version/version.go
Labels: size/S, lgtm, approved

#2226 playground: support microservices mode
  components/playground/command.go
  components/playground/instance/instance.go
  components/playground/instance/pd.go
  components/playground/main.go
  components/playground/playground.go
  pkg/tidbver/tidbver.go
Labels: size/XL, lgtm, approved

#2230 cluster: fix cannot start tiflash above 7.1.0
  pkg/cluster/spec/tiflash.go
  pkg/tidbver/tidbver.go
Labels: size/XS, lgtm, approved

#2231 bump version to v1.12.5
  CHANGELOG.md
  pkg/version/version.go
Labels: size/XS, lgtm, approved
