Repository pingcap/tiup, pull requests merged in 2023-02, with the labels that each got.

#2098 allow download directory when use builtin scp
  pkg/cluster/executor/scp.go
Labels: status/can-merge, status/LGT1, size/L

#2111 doc/dev: Add TIUP_VERBOSE
  doc/dev/README.md
Labels: status/can-merge, status/LGT1, size/XS

#2105 clean: Warn for cleanup failures due to missing datadir
  cmd/clean.go
Labels: status/can-merge, status/LGT1, size/XS

#2112 cluster:comment out tidb-dashboard in template
  embed/examples/cluster/topology.example.yaml
Labels: status/can-merge, status/LGT1, size/S

#2110 cluster:update upgrade message
  pkg/cluster/manager/upgrade.go
Labels: status/LGT1, size/XS

#2113 add v1.11.2 release note
  CHANGELOG.md
  pkg/version/version.go
Labels: status/can-merge, status/LGT1, size/S

#2119 disable telemetry by default
  pkg/telemetry/meta.go
  pkg/telemetry/meta_test.go
Labels: status/can-merge, status/LGT1, size/S

#2120 add v1.11.3 release note
  CHANGELOG.md
  pkg/version/version.go
Labels: status/can-merge, status/LGT1, size/XS

#2123 fix build-in scp
  pkg/cluster/executor/scp.go
  tools/check/golangci.yaml
Labels: status/can-merge, status/LGT1, size/S
