Repository pingcap/tiup, pull requests merged in 2023-12, with the labels that each got.

#2335 tiup & playground: Tidy output
  components/playground/main.go
  go.mod
  go.sum
  pkg/exec/run.go
  pkg/tui/colorstr/builtin_tokens.go
  pkg/tui/colorstr/color.go
  pkg/tui/colorstr/color_test.go
  pkg/tui/colorstr/test_util.go
  pkg/tui/colorstr/test_util_test.go
Labels: size/XL, lgtm, approved

#2330 Change typo 'waitting' to 'waiting' in output messages within pdapi.go.
  pkg/cluster/api/pdapi.go
Labels: size/S, approved

#2337 fix the start script for alertmanager when enabling numa
  embed/templates/scripts/run_alertmanager.sh.tpl
Labels: size/XS, lgtm, approved

#2341 fix ci
  tests/tiup-cluster/script/scale_tools.sh
Labels: size/XS, lgtm, approved

#2340 cluster/dm: support deploying Prometheus witch custom command parameters
  embed/templates/scripts/run_prometheus.sh.tpl
  pkg/cluster/spec/monitoring.go
  pkg/cluster/template/scripts/monitoring.go
Labels: size/S, lgtm, approved

#2344 playground: fallback to default version when componen specific version is empty
  components/playground/playground.go
Labels: size/XS, lgtm, approved

#2342 playground: tiproxy needs to override usercfg
  components/playground/instance/tiproxy.go
  go.mod
  go.sum
Labels: size/M, lgtm, approved
