Repository pingcap/tiup, pull requests merged in 2024-06, with the labels that each got.

#2425 hide password
  pkg/environment/history.go
  pkg/exec/run.go
Labels: size/S

#2426 remove test code
  pkg/exec/run.go
Labels: size/XS

#2422 client: Use localdata and fix typo
  components/client/go.mod
  components/client/go.sum
  components/client/main.go
Labels: size/XXL

#2044 cluster: remove tombstone nodes on pd when prune
  pkg/cluster/api/pdapi.go
  pkg/cluster/manager/destroy.go
Labels: size/S

#2431 cluster: make pd mode editable
  pkg/cluster/spec/spec.go
Labels: size/XS, lgtm, approved
