Repository pingcap/tiup, pull requests merged in 2024-07, with the labels that each got.

#2432 cluster: copy session certs when scale-out TiDB
  .github/workflows/integrate-cluster-scale.yaml
  pkg/cluster/manager/builder.go
  pkg/cluster/manager/deploy.go
  pkg/cluster/spec/tidb.go
  tests/tiup-cluster/script/scale_tiproxy.sh
  tests/tiup-cluster/test_scale_tiproxy.sh
Labels: size/XL, approved

#2433 Update OWNERS
  OWNERS
Labels: size/XS

#2430 bump version to v1.16.0
  CHANGELOG.md
  pkg/version/version.go
Labels: size/S, lgtm

#2435 cluster: remove duplicated tasks when prune
  pkg/cluster/manager/destroy.go
Labels: size/XS, lgtm

#2437 TiFlash: Enable and inactive prof when start
  embed/templates/scripts/run_tiflash.sh.tpl
Labels: size/XS, lgtm

#2436 hide other password args
  pkg/environment/history.go
Labels: size/M, approved

#2314 playground: Only add --comments when needed
  components/playground/playground.go
  components/playground/playground_test.go
Labels: size/L, lgtm, approved

#2334 playground: print version when filling binpath
  components/playground/instance/drainer.go
  components/playground/instance/instance.go
  components/playground/instance/pd.go
  components/playground/instance/pump.go
  components/playground/instance/ticdc.go
  components/playground/instance/tidb.go
  components/playground/instance/tiflash.go
  components/playground/instance/tiflash_pre7.go
  components/playground/instance/tikv.go
  components/playground/instance/tikv_cdc.go
  components/playground/instance/tiproxy.go
  components/playground/playground.go
Labels: size/L, lgtm, approved

#2440 cluster: do not need to check TiFlash http_port
  pkg/cluster/spec/tiflash.go
Labels: size/S, lgtm

#2443 fix tiup cannot update itself when tiup comonent exist
  pkg/repository/v1_repository.go
Labels: size/XS, lgtm, approved

#2444 tiflash: Add example of setting the tiflash-proxy configs
  embed/examples/cluster/topology.example.yaml
Labels: size/XS, lgtm

#2438 pdms(playground, cluster): add name to start pdms
  components/playground/instance/pd.go
  embed/templates/scripts/run_scheduling.sh.tpl
  embed/templates/scripts/run_tso.sh.tpl
  pkg/cluster/manager/manager_test.go
  pkg/cluster/manager/transfer_test.go
  pkg/cluster/spec/scheduling.go
  pkg/cluster/spec/spec.go
  pkg/cluster/spec/tso.go
  pkg/cluster/spec/validate.go
  pkg/cluster/template/scripts/pdms_test.go
  pkg/cluster/template/scripts/scheduling.go
  pkg/cluster/template/scripts/tso.go
  pkg/tidbver/tidbver.go
Labels: size/XL, lgtm, approved

#2446 Revert "pdms(playground, cluster): add name to start pdms"
  components/playground/instance/pd.go
  embed/templates/scripts/run_scheduling.sh.tpl
  embed/templates/scripts/run_tso.sh.tpl
  pkg/cluster/manager/manager_test.go
  pkg/cluster/manager/transfer_test.go
  pkg/cluster/spec/scheduling.go
  pkg/cluster/spec/spec.go
  pkg/cluster/spec/tso.go
  pkg/cluster/spec/validate.go
  pkg/cluster/template/scripts/pdms_test.go
  pkg/cluster/template/scripts/scheduling.go
  pkg/cluster/template/scripts/tso.go
  pkg/tidbver/tidbver.go
Labels: size/XL, lgtm
