Repository pingcap/tiup, pull requests merged in 2024-05, with the labels that each got.

#2415 playground: fix the health check
  components/playground/playground.go
  pkg/cluster/api/pdapi.go
Labels: size/XS, lgtm, approved

#2417 playground: support scaling ms instances when using playground
  components/playground/command.go
  components/playground/playground.go
Labels: size/M, lgtm, approved

#2407 Allow specifying Grafana port via command-line arguments
  components/playground/grafana.go
  components/playground/main.go
  components/playground/playground.go
  doc/user/playground.md
Labels: size/S, lgtm

#2419 Remove redundant config arg when launching pd
  components/playground/instance/pd.go
Labels: size/XS, lgtm

#2423 remove duplicate download when upgrade
  pkg/cluster/manager/upgrade.go
  pkg/cluster/operation/download.go
Labels: size/S, approved

#2420 pdms: add name to start pdms
  components/playground/instance/pd.go
  embed/templates/scripts/run_scheduling.sh.tpl
  embed/templates/scripts/run_tso.sh.tpl
  pkg/cluster/spec/scheduling.go
  pkg/cluster/spec/tso.go
  pkg/cluster/spec/validate.go
  pkg/cluster/template/scripts/scheduling.go
  pkg/cluster/template/scripts/tso.go
Labels: size/M
