Repository pingcap/tiup, pull requests merged in 2024-04, with the labels that each got.

#2397 Revert "playground: only pull nightly from cluster version (#2364)"
  components/playground/playground.go
Labels: size/XS

#2401 Fix tiflash numa node not working issue
  pkg/cluster/spec/tiflash.go
Labels: size/XS, approved

#2394 playground/pdms: wait for tso component ready
  components/playground/instance/tikv.go
  components/playground/playground.go
  pkg/cluster/api/pdapi.go
Labels: size/M

#2400 Improve handling of mirror renw
  cmd/mirror.go
Labels: size/XS

#2402 playground: fix default tiproxy version
  components/playground/playground.go
Labels: size/XS, lgtm, approved

#2403 Remove ansiterm
  components/playground/playground.go
  go.mod
  go.sum
  pkg/tui/tui.go
  pkg/utils/tabledisplayer.go
Labels: size/L, lgtm

#2404 bump to v1.15.1
  CHANGELOG.md
Labels: size/S

#2377 Support deploying microservice
  components/cluster/command/upgrade.go
  embed/templates/config/prometheus.yml.tpl
  embed/templates/scripts/run_pd.sh.tpl
  embed/templates/scripts/run_pd_scale.sh.tpl
  embed/templates/scripts/run_scheduling.sh.tpl
  embed/templates/scripts/run_tso.sh.tpl
  pkg/cluster/ansible/import_test.go
  pkg/cluster/ansible/test-data/meta.yaml
  pkg/cluster/api/pdapi.go
  pkg/cluster/spec/instance.go
  pkg/cluster/spec/monitoring.go
  pkg/cluster/spec/pd.go
  pkg/cluster/spec/scheduling.go
  pkg/cluster/spec/spec.go
  pkg/cluster/spec/tso.go
  pkg/cluster/task/update_meta.go
  pkg/cluster/template/config/prometheus.go
  pkg/cluster/template/scripts/pd.go
  pkg/cluster/template/scripts/scheduling.go
  pkg/cluster/template/scripts/tso.go
Labels: size/XXL, lgtm, approved

#2408 cluster: fix the tls check for tso and scheduling service
  pkg/cluster/spec/validate.go
Labels: size/XS, lgtm
