Repository pingcap/tiup, pull requests merged in 2024-08, with the labels that each got.

#2445 cluster: remove systemd and interrupts collector
  embed/templates/scripts/run_node_exporter.sh.tpl
  pkg/repository/testdata/manifests/root.json
  pkg/repository/testdata/polluted/bin/root.json
  pkg/repository/v1manifest/testdata/polluted/bin/root.json
Labels: size/S, approved

#2447 pdms(playground, cluster): add name to start pdms
  components/playground/instance/pd.go
  embed/templates/scripts/run_scheduling.sh.tpl
  embed/templates/scripts/run_tso.sh.tpl
  pkg/cluster/manager/manager_test.go
  pkg/cluster/manager/transfer_test.go
  pkg/cluster/spec/scheduling.go
  pkg/cluster/spec/spec.go
  pkg/cluster/spec/tso.go
  pkg/cluster/spec/validate.go
  pkg/cluster/template/scripts/pdms_test.go
  pkg/cluster/template/scripts/scheduling.go
  pkg/cluster/template/scripts/tso.go
  pkg/tidbver/tidbver.go
Labels: size/XL, lgtm, approved

#2451 cluster: fix that scaled nodes don't respect `component_versions`
  .github/workflows/integrate-cluster-cmd.yaml
  .github/workflows/integrate-cluster-scale.yaml
  .github/workflows/integrate-dm.yaml
  docker/up.sh
  pkg/cluster/spec/parse_topology_test.go
  pkg/cluster/spec/spec.go
  tests/tiup-cluster/script/detect_error.sh
  tests/tiup-cluster/script/pull_log.sh
  tests/tiup-cluster/script/scale_tiproxy.sh
  tests/tiup-cluster/test_scale_tiproxy.sh
  tests/tiup-cluster/topo/tiproxy.yaml
Labels: size/L, lgtm

#2453 playground: Allow specifying port offset
  components/playground/grafana.go
  components/playground/instance/drainer.go
  components/playground/instance/instance.go
  components/playground/instance/pd.go
  components/playground/instance/pump.go
  components/playground/instance/ticdc.go
  components/playground/instance/tidb.go
  components/playground/instance/tiflash.go
  components/playground/instance/tikv.go
  components/playground/instance/tikv_cdc.go
  components/playground/instance/tiproxy.go
  components/playground/main.go
  components/playground/monitor.go
  components/playground/ngmonitoring.go
  components/playground/playground.go
  pkg/proxy/proxy.go
  pkg/proxy/tcp_proxy.go
  pkg/utils/freeport.go
  pkg/utils/freeport_test.go
Labels: size/L, lgtm

#2455 pkg/crypto: replace 'math/rand' with 'crypto/rand'
  pkg/crypto/rand/rand.go
  pkg/telemetry/meta.go
Labels: size/M, lgtm
