Repository pingcap/tiup, pull requests merged in 2024-01, with the labels that each got.

#2348 delete `logger.level` and `profiles.default.max_memory_usage` in tiflash default configs
  pkg/cluster/spec/tiflash.go
Labels: size/XS, do-not-merge/hold, lgtm, approved

#2351 playground: init some pd configuration
  components/playground/instance/pd.go
  components/playground/instance/pd_config.go
Labels: size/M, lgtm

#2347 playground: Allow configuring pd.binpath for all PD microservices
  components/playground/main.go
Labels: size/S, approved

#2354 cluster: fix tiproxy config and version
  pkg/cluster/spec/tiproxy.go
  pkg/cluster/spec/validate.go
Labels: size/S, lgtm, approved

#2359 tiup: fix cannot clone without global version
  pkg/repository/clone_mirror.go
Labels: size/XS, lgtm, approved

#2356 cluster: fix TLS configs for tiproxy
  pkg/cluster/spec/tiproxy.go
Labels: size/S, lgtm, approved

#2346 playground: fix can not set runtime config in config file & set TiFlash logger level to debug
  components/playground/instance/tiflash.go
  components/playground/instance/tiflash_config.go
Labels: size/M, lgtm, approved

#2349 [fix] Empty label is not allowed in Prometheus
  embed/templates/config/prometheus.yml.tpl
Labels: size/XS, lgtm, approved

#2358 cluster: fix tiproxy will restart even if version is the same
  pkg/cluster/manager/upgrade.go
Labels: size/XS, lgtm, approved

#2363 bump to 1.14.1
  CHANGELOG.md
Labels: size/S, lgtm, approved

#2350 support user mode systemd
  components/cluster/command/template.go
  components/dm/command/template.go
  embed/examples/cluster/local.tpl
  embed/examples/cluster/minimal.yaml
  embed/examples/cluster/multi-dc.yaml
  embed/examples/cluster/topology.example.yaml
  embed/examples/dm/local.tpl
  embed/examples/dm/minimal.yaml
  embed/examples/dm/topology.example.yaml
  embed/templates/systemd/system.service.tpl
  pkg/cluster/ctxt/context.go
  pkg/cluster/executor/ssh.go
  pkg/cluster/manager/builder.go
  pkg/cluster/manager/check.go
  pkg/cluster/manager/cleanup.go
  pkg/cluster/manager/deploy.go
  pkg/cluster/manager/display.go
  pkg/cluster/manager/manager.go
  pkg/cluster/manager/scale_out.go
  pkg/cluster/manager/upgrade.go
  pkg/cluster/module/systemd.go
  pkg/cluster/operation/action.go
  pkg/cluster/operation/check.go
  pkg/cluster/operation/destroy.go
  pkg/cluster/operation/systemd.go
  pkg/cluster/operation/upgrade.go
  pkg/cluster/spec/instance.go
  pkg/cluster/spec/spec.go
  pkg/cluster/spec/tispark.go
  pkg/cluster/task/builder.go
  pkg/cluster/task/check.go
  pkg/cluster/task/env_init.go
  pkg/cluster/task/limits.go
  pkg/cluster/task/mkdir.go
  pkg/cluster/task/monitored_config.go
  pkg/cluster/task/ssh.go
  pkg/cluster/task/sysctl.go
  pkg/cluster/task/systemd.go
  pkg/cluster/template/systemd/system.go
Labels: size/XXL, lgtm, approved

#2371 cluster: add integration tests for tiproxy
  tests/tiup-cluster/script/scale_core.sh
  tests/tiup-cluster/script/scale_tools.sh
  tests/tiup-cluster/topo/full.yaml
  tests/tiup-cluster/topo/full_scale_in_tiproxy.yaml
  tests/tiup-cluster/topo/full_tls.yaml
  tests/tiup-cluster/topo/full_without_tiflash.yaml
Labels: size/M, lgtm, approved

#2373 create systemd dir when use systemd user mode
  embed/templates/systemd/system.service.tpl
  pkg/cluster/manager/builder.go
  pkg/cluster/manager/deploy.go
  pkg/cluster/spec/instance.go
Labels: size/S, lgtm, approved
