Repository pingcap/tiup, pull requests merged in 2024-03, with the labels that each got.

#2379 Fix timeout when checking component upgrade
  pkg/exec/run.go
Labels: size/XS, lgtm, approved

#2366 cluster: skip tiproxy download & copy
  pkg/cluster/manager/upgrade.go
Labels: size/S, lgtm, approved

#2374 cluster: auto session certs
  pkg/cluster/manager/builder.go
  pkg/cluster/spec/tidb.go
  pkg/tidbver/tidbver.go
Labels: size/L

#2372 playground: auto tiproxy sign certs
  components/playground/instance/tidb.go
  components/playground/instance/tidb_config.go
  components/playground/instance/tiproxy.go
  components/playground/playground.go
Labels: size/M

#2383 Remove uselesss println
  components/playground/instance/tiflash.go
Labels: size/XS, lgtm

#2382 pdms: fix pdms grafana display
  components/playground/playground.go
Labels: size/XS, lgtm

#2381 playground: remove resource manager
  components/playground/instance/instance.go
  components/playground/instance/pd.go
  components/playground/main.go
  components/playground/playground.go
  pkg/cluster/executor/ssh.go
Labels: size/L, lgtm

#2386 playground: Add tidb-cse mode
  components/playground/instance/instance.go
  components/playground/instance/pd.go
  components/playground/instance/pd_config.go
  components/playground/instance/tidb.go
  components/playground/instance/tidb_config.go
  components/playground/instance/tiflash.go
  components/playground/instance/tiflash_config.go
  components/playground/instance/tikv.go
  components/playground/instance/tikv_config.go
  components/playground/main.go
  components/playground/playground.go
  pkg/tidbver/tidbver.go
Labels: size/L, lgtm, approved

#2392 cluster, playground: add config `advertise-addr` to tiproxy
  components/playground/instance/tiproxy.go
  pkg/cluster/spec/tiproxy.go
Labels: size/XS, lgtm

#2387 update prometheus config when scale in
  pkg/cluster/manager/destroy.go
  pkg/cluster/manager/scale_in.go
Labels: size/M

#2393 Bump version to v1.15.0
  CHANGELOG.md
  pkg/version/version.go
Labels: size/S
