Repository pingcap/tiup, pull requests merged in 2024-11, with the labels that each got.

#2466 add cdc server topylogy example
  embed/examples/cluster/topology.example.yaml
Labels: size/M, lgtm

#2454 playground: Fix typo and update
  components/playground/instance/pd_config.go
  components/playground/playground.go
Labels: size/S, lgtm

#2468 fix # cannot be included in grafana password
  embed/templates/config/grafana.ini.tpl
  pkg/cluster/spec/grafana_test.go
Labels: size/S, lgtm

#2472 cluster: display dashboard server URLs
  pkg/cluster/manager/display.go
  pkg/cluster/spec/spec.go
Labels: size/M

#2474 playground: add tiproxy to dsn
  components/playground/main.go
  components/playground/playground.go
Labels: size/XS, lgtm

#2476 cluster: Update supported OS versions
  pkg/cluster/operation/check.go
Labels: size/M, lgtm
