Repository pingcap/tiup, pull requests merged in 2025-01, with the labels that each got.

#2487 *: fix typo
  components/playground/instance/pd.go
  components/playground/playground.go
  pkg/cluster/api/pdapi.go
  pkg/cluster/spec/scheduling.go
  pkg/cluster/spec/tso.go
  pkg/tidbver/tidbver.go
Labels: size/S, lgtm

#2492 playground: Add --mode=tiflash-disagg
  .github/workflows/integrate-cluster-cmd.yaml
  .github/workflows/integrate-cluster-scale.yaml
  .github/workflows/integrate-dm.yaml
  .github/workflows/integrate-playground.yaml
  components/playground/instance/pd.go
  components/playground/instance/pd_config.go
  components/playground/instance/tidb.go
  components/playground/instance/tidb_config.go
  components/playground/instance/tiflash.go
  components/playground/instance/tiflash_config.go
  components/playground/instance/tikv.go
  components/playground/instance/tikv_config.go
  components/playground/main.go
  components/playground/playground.go
Labels: size/L, lgtm

#2499 cluster: improved error for missing tar
  pkg/cluster/task/install_package.go
Labels: size/XS, lgtm
