Repository pingcap/tiup, pull requests merged in 2025-05, with the labels that each got.

#2535 playground: Add --perf for starting cluster for higher performance
  components/playground/instance/dm_master.go
  components/playground/instance/dm_worker.go
  components/playground/instance/drainer.go
  components/playground/instance/instance.go
  components/playground/instance/pd.go
  components/playground/instance/pd_config.go
  components/playground/instance/pump.go
  components/playground/instance/ticdc.go
  components/playground/instance/tidb.go
  components/playground/instance/tidb_config.go
  components/playground/instance/tiflash.go
  components/playground/instance/tiflash_config.go
  components/playground/instance/tiflash_pre7.go
  components/playground/instance/tikv.go
  components/playground/instance/tikv_cdc.go
  components/playground/instance/tikv_config.go
  components/playground/instance/tiproxy.go
  components/playground/main.go
  components/playground/monitor.go
  components/playground/ngmonitoring.go
  components/playground/playground.go
Labels: size/XL, lgtm

#2536 playground: Support tikv-worker and --tikv.columnar in tidb-cse mode
  components/playground/instance/instance.go
  components/playground/instance/tiflash_config.go
  components/playground/instance/tikv_config.go
  components/playground/instance/tikv_worker.go
  components/playground/main.go
  components/playground/playground.go
  pkg/cluster/spec/instance.go
Labels: size/L, lgtm

#2532 cluster: add agent mode for prometheus
  embed/templates/scripts/run_prometheus.sh.tpl
  pkg/cluster/spec/grafana.go
  pkg/cluster/spec/grafana_test.go
  pkg/cluster/spec/monitoring.go
  pkg/cluster/spec/monitoring_test.go
  pkg/cluster/template/config/prometheus.go
  pkg/cluster/template/config/prometheus_test.go
  pkg/cluster/template/scripts/monitoring.go
  pkg/cluster/template/scripts/monitoring_test.go
Labels: size/XL, lgtm

#2540 test: use larger RSA keys
  .github/pull_request_template.md
  pkg/cluster/spec/monitoring.go
  pkg/crypto/rsa_test.go
Labels: size/M, lgtm
