Repository pingcap/tiup, pull requests merged in 2025-08, with the labels that each got.

#2567 tici: Update the default config filename & default port of tici
  components/playground/instance/tici.go
Labels: size/S, lgtm

#2568 cluster: add stop/start timeout for systemd service
  embed/templates/systemd/system.service.tpl
  pkg/cluster/spec/instance.go
  pkg/cluster/task/monitored_config.go
  pkg/cluster/template/systemd/system.go
  pkg/meta/resource_ctrl.go
Labels: size/S

#2553 Move insight to tiup
  go.mod
  go.sum
  pkg/cluster/operation/check.go
  pkg/cluster/spec/monitoring.go
  pkg/insight/chrony.go
  pkg/insight/dmesg.go
  pkg/insight/epoll.go
  pkg/insight/epoll_no_cgo.go
  pkg/insight/insight.go
  pkg/insight/ntp.go
  pkg/insight/partitions.go
  pkg/insight/process.go
  pkg/insight/process_linux.go
  pkg/insight/process_others.go
  pkg/insight/socket.go
  pkg/insight/socket_linux.go
  pkg/insight/socket_others.go
  pkg/insight/syscfg.go
  pkg/insight/utils.go
  pkg/kmsg/read.go
  pkg/kmsg/types.go
Labels: size/XXL

#2566 check_to_require: cluster
  cmd/cmd_test.go
  components/cluster/command/root_test.go
  components/dm/spec/topology_dm_test.go
  go.mod
  go.sum
  pkg/cluster/ansible/import_test.go
  pkg/cluster/ansible/service_test.go
  pkg/cluster/api/error_test.go
  pkg/cluster/api/typeutil/duration_test.go
  pkg/cluster/api/typeutil/string_slice_test.go
  pkg/cluster/audit/audit_test.go
  pkg/cluster/spec/parse_topology_test.go
  pkg/cluster/spec/server_config_test.go
  pkg/cluster/spec/spec_test.go
  pkg/cluster/spec/util_test.go
  pkg/cluster/spec/validate_test.go
  pkg/cluster/task/init_config_test.go
  pkg/cluster/template/scripts/pd_test.go
  pkg/queue/any_queue_test.go
Labels: size/XXL

#2571 Replace otiai10/copy with os.CopyFS
  go.mod
  go.sum
  pkg/utils/ioutil.go
Labels: size/S, lgtm

#2579 ci: fix STAGING version competition
  .github/workflows/release-tiup.yaml
Labels: size/XS, lgtm

#2578 playground: fix config typo
  components/playground/instance/pd_config.go
Labels: size/XS, lgtm

#2577 ci: add ci for feature branch
  .github/workflows/integrate-playground.yaml
  .github/workflows/integrate-tiup.yaml
  .github/workflows/reprotest.yaml
Labels: size/XS, lgtm

#2581 playground: make the tici changefeed endpoint configurable
  components/playground/playground.go
Labels: size/XS, lgtm

#2583 *: support start a TiDB playground cluster with TiCI without any self-defined binarys or configurations
  components/playground/instance/tici.go
  components/playground/instance/tici_meta_config.go
  components/playground/instance/tici_worker_config.go
  components/playground/instance/tidb.go
  components/playground/instance/tiflash.go
  components/playground/instance/tiflash_tici_reader_config.go
  components/playground/instance/tiproxy.go
  components/playground/main.go
  components/playground/playground.go
  pkg/cluster/spec/instance.go
  pkg/environment/env.go
  pkg/utils/semver.go
Labels: size/XL

#2586 playground: fix --tici.binpath
  components/playground/instance/tici.go
  components/playground/instance/tiflash.go
  components/playground/playground.go
Labels: size/S

#2570 Replace alecthomas/assert with testify/require
  go.mod
  go.sum
  pkg/repository/v1manifest/keys_test.go
  pkg/repository/v1manifest/types_test.go
Labels: size/L, lgtm

#2558 Switch from yaml.v2 to yaml.v3
  components/dm/ansible/import.go
  components/dm/command/import.go
  components/dm/spec/topology_dm_test.go
  go.mod
  go.sum
  pkg/cluster/ansible/inventory.go
  pkg/cluster/manager/edit_config.go
  pkg/cluster/manager/manager_test.go
  pkg/cluster/manager/show_config.go
  pkg/cluster/spec/parse_topology.go
  pkg/cluster/spec/server_config.go
  pkg/cluster/spec/server_config_test.go
  pkg/cluster/spec/spec_manager.go
  pkg/cluster/spec/spec_test.go
  pkg/cluster/spec/tiflash.go
  pkg/cluster/spec/validate_test.go
  pkg/utils/diff_test.go
Labels: size/M

#2592 cluster: support new ready api for PD
  .github/workflows/integrate-cluster-cmd.yaml
  docker/control/Dockerfile
  pkg/cluster/api/pdapi.go
  pkg/cluster/operation/action.go
  pkg/cluster/operation/scale_in.go
  pkg/cluster/operation/upgrade.go
  pkg/cluster/spec/cdc.go
  pkg/cluster/spec/instance.go
  pkg/cluster/spec/pd.go
  pkg/cluster/spec/scheduling.go
  pkg/cluster/spec/tikv.go
  pkg/cluster/spec/tikv_cdc.go
  pkg/cluster/spec/tiproxy.go
  pkg/cluster/spec/tso.go
  pkg/tidbver/tidbver.go
Labels: size/L

#2591 cluster: clear leader_priority for pd leader if exist
  pkg/cluster/api/pdapi.go
  pkg/cluster/spec/pd.go
Labels: size/M

#2513 cluster: prompt for instance restart
  components/cluster/command/upgrade.go
  components/dm/command/upgrade.go
  pkg/cluster/manager/patch.go
  pkg/cluster/manager/reload.go
  pkg/cluster/manager/upgrade.go
  pkg/cluster/operation/upgrade.go
Labels: size/M

#2574 Modernize
  components/cluster/command/start.go
  components/cluster/command/test.go
  components/dm/command/prune.go
  components/dm/spec/logic.go
  components/playground/instance/tiflash.go
  components/playground/main.go
  pkg/cluster/ansible/service.go
  pkg/cluster/api/types.go
  pkg/cluster/audit/audit_test.go
  pkg/cluster/executor/executor.go
  pkg/cluster/manager/builder.go
  pkg/cluster/manager/cleanup.go
  pkg/cluster/manager/transfer.go
  pkg/cluster/operation/action.go
  pkg/cluster/operation/check.go
  pkg/cluster/operation/scale_in.go
  pkg/cluster/operation/systemd.go
  pkg/cluster/spec/alertmanager.go
  pkg/cluster/spec/cdc.go
  pkg/cluster/spec/dashboard.go
  pkg/cluster/spec/drainer.go
  pkg/cluster/spec/grafana.go
  pkg/cluster/spec/monitoring.go
  pkg/cluster/spec/pd.go
  pkg/cluster/spec/pump.go
  pkg/cluster/spec/scheduling.go
  pkg/cluster/spec/tidb.go
  pkg/cluster/spec/tikv.go
  pkg/cluster/spec/tikv_cdc.go
  pkg/cluster/spec/tiproxy.go
  pkg/cluster/spec/tispark.go
  pkg/cluster/spec/tso.go
  pkg/cluster/spec/util.go
  pkg/cluster/spec/validate.go
  pkg/cluster/task/mkdir.go
  pkg/crypto/rand/passwd_test.go
  pkg/insight/insight.go
  pkg/insight/partitions.go
  pkg/insight/syscfg.go
  pkg/proxy/tcp_proxy.go
  pkg/repository/v1_repository.go
  pkg/repository/v1manifest/repo.go
  pkg/tui/progress/example_single_bar_test.go
  pkg/utils/diff.go
  pkg/utils/ioutil_test.go
Labels: size/L, lgtm

#2598 cluster: prevent panic when the operation is not upgrade
  pkg/cluster/operation/upgrade.go
Labels: size/XS
