Repository pingcap/tiup, pull requests merged in 2025-07, with the labels that each got.

#2552 Fix PR template
  .github/pull_request_template.md
Labels: size/S, lgtm

#2560 Switch from go-pretty fork back to upstream
  go.mod
  go.sum
  pkg/tui/tui.go
Labels: size/S, lgtm

#2557 check_to_require: set
  pkg/set/any_set_test.go
  pkg/set/string_set_test.go
Labels: size/M, lgtm

#2559 meta: replace pingcap/check with testing
  pkg/meta/err_test.go
Labels: size/M, lgtm

#2561 check_to_require: localdata
  pkg/localdata/profile_test.go
Labels: size/M, lgtm

#2564 Telemetry removal
  .codecov.yml
  cmd/clean.go
  cmd/env.go
  cmd/install.go
  cmd/link.go
  cmd/list.go
  cmd/mirror.go
  cmd/root.go
  cmd/status.go
  cmd/telemetry.go
  cmd/uninstall.go
  cmd/unlink.go
  cmd/update.go
  components/cluster/command/check.go
  components/cluster/command/clean.go
  components/cluster/command/deploy.go
  components/cluster/command/destroy.go
  components/cluster/command/disable.go
  components/cluster/command/display.go
  components/cluster/command/edit_config.go
  components/cluster/command/enable.go
  components/cluster/command/exec.go
  components/cluster/command/patch.go
  components/cluster/command/prune.go
  components/cluster/command/reload.go
  components/cluster/command/rename.go
  components/cluster/command/restart.go
  components/cluster/command/root.go
  components/cluster/command/scale_in.go
  components/cluster/command/scale_out.go
  components/cluster/command/show_config.go
  components/cluster/command/start.go
  components/cluster/command/stop.go
  components/cluster/command/telemetry.go
  components/cluster/command/tls.go
  components/cluster/command/transfer.go
  components/cluster/command/upgrade.go
  components/playground/main.go
  go.sum
  pkg/cluster/operation/telemetry.go
  pkg/exec/run.go
  pkg/telemetry/generate.sh
  pkg/telemetry/meta.go
  pkg/telemetry/meta_test.go
  pkg/telemetry/node_info.go
  pkg/telemetry/node_info_generic.go
  pkg/telemetry/node_info_loong64.go
  pkg/telemetry/report.go
  pkg/telemetry/report.pb.go
  pkg/telemetry/report.proto
  pkg/telemetry/report_test.go
  pkg/telemetry/scrub.go
  pkg/telemetry/scrub_test.go
  pkg/telemetry/telemetry.go
  pkg/telemetry/telemetry_test.go
  pkg/telemetry/testdata/full.yaml
  pkg/telemetry/testdata/full.yaml.out
  pkg/telemetry/testdata/simple.yaml
  pkg/telemetry/testdata/simple.yaml.out
  pkg/telemetry/testdata/single/nilvalue.yaml
Labels: size/XXL

#2563 cluster: also check exporter ports
  .github/workflows/integrate-cluster-cmd.yaml
  .github/workflows/integrate-cluster-scale.yaml
  .github/workflows/integrate-dm.yaml
  .github/workflows/integrate-playground.yaml
  .github/workflows/integrate-tiup.yaml
  Makefile
  docker/up.sh
  pkg/cluster/spec/monitoring.go
  pkg/cluster/spec/monitoring_test.go
  tests/tiup-dm/test_cmd.sh
Labels: size/L

#2501 cluster: improve SELinux compatibility
  pkg/cluster/spec/instance.go
  pkg/cluster/spec/tispark.go
  pkg/cluster/task/monitored_config.go
Labels: size/S, lgtm
