Repository pingcap/tiup, pull requests merged in 2025-02, with the labels that each got.

#2493 telemetry: fix loong64 build
  pkg/telemetry/node_info.go
  pkg/telemetry/node_info_generic.go
  pkg/telemetry/node_info_loong64.go
Labels: size/L, lgtm

#2488 uninstall: more clearly messages
  cmd/uninstall.go
Labels: size/XS, lgtm

#2500 update sysinfo
  go.mod
  go.sum
Labels: size/XS, lgtm

#2495 cluster: Fix message for net.core.somaxconn check
  pkg/cluster/operation/check.go
Labels: size/XS, lgtm

#2504 *: Fix misc spelling
  CHANGELOG.md
  cmd/mirror.go
  components/cluster/command/root.go
  components/cluster/command/telemetry.go
  components/dm/ansible/import.go
  components/dm/command/root.go
  doc/design/checkpoint.md
  doc/design/manifest.md
  doc/user/README.md
  embed/templates/config/grafana.ini.tpl
  install.sh
  pkg/cluster/api/dmpb/dmworker.pb.go
  pkg/cluster/executor/executor.go
  pkg/cluster/executor/scp.go
  pkg/cluster/manager/builder.go
  pkg/cluster/manager/patch.go
  pkg/cluster/manager/scale_out.go
  pkg/cluster/operation/action.go
  pkg/cluster/operation/check.go
  pkg/cluster/operation/operation.go
  pkg/cluster/spec/spec.go
  pkg/cluster/spec/tiflash.go
  pkg/cluster/spec/tikv.go
  pkg/cluster/spec/tispark.go
  pkg/cluster/spec/validate.go
  pkg/cluster/spec/validate_test.go
  pkg/cluster/task/ssh.go
  pkg/cluster/template/install/local_install.sh.go
  pkg/cluster/template/systemd/system.go
  pkg/cluster/template/systemd/tispark.go
  pkg/logger/printer/logger.go
  pkg/repository/clone_mirror.go
  pkg/repository/merge_mirror.go
  pkg/repository/mirror.go
  pkg/repository/model/model.go
  pkg/repository/model/publish.go
  pkg/repository/store/store.go
  pkg/repository/store/txn.go
  pkg/repository/v1manifest/types.go
  pkg/telemetry/report.pb.go
  pkg/telemetry/report.proto
  pkg/tui/progress/display_props.go
  pkg/tui/progress/single_bar.go
  server/session/session.go
  tests/tiup-dm/test_import.sh
Labels: size/L, lgtm

#2511 cluster: remove created directories after fio test in `tiup cluster check`
  pkg/cluster/task/check.go
Labels: size/S, lgtm
