Repository pingcap/tiup, pull requests merged in 2025-04, with the labels that each got.

#2524 cluster: fill node & role information in custom upgrade scripts
  components/cluster/command/reload.go
  components/cluster/command/upgrade.go
  pkg/cluster/operation/upgrade.go
Labels: size/S, lgtm

#2526 bump version to v1.16.2
  CHANGELOG.md
  pkg/version/version.go
Labels: size/M, lgtm

#2520 cluster: add new option to set VM as a remote writer
  embed/templates/config/datasource.yml.tpl
  embed/templates/config/prometheus.yml.tpl
  pkg/cluster/spec/grafana.go
  pkg/cluster/spec/grafana_test.go
  pkg/cluster/spec/monitoring.go
  pkg/cluster/template/config/datasource.go
  pkg/telemetry/node_info_generic.go
  pkg/telemetry/node_info_loong64.go
Labels: size/XL

#2525 Run golang.org/x/tools/gopls modernize
  components/client/main.go
  components/cluster/command/reload.go
  components/ctl/main.go
  components/dm/command/reload.go
  components/playground/playground.go
  pkg/cluster/api/typeutil/duration.go
  pkg/cluster/module/wait_for.go
  pkg/cluster/operation/scale_in.go
  pkg/cluster/operation/upgrade.go
  pkg/cluster/spec/tiflash.go
  pkg/crypto/ca_test.go
  pkg/localdata/profile.go
  pkg/queue/any_queue.go
  pkg/set/any_set.go
  pkg/utils/ioutil.go
  pkg/utils/semver.go
  server/handler/component.go
Labels: size/L, lgtm

#2530 *: Support changing the data source when multiple data sources exist
  .github/workflows/install.yaml
  .github/workflows/integrate-cluster-cmd.yaml
  .github/workflows/integrate-cluster-scale.yaml
  .github/workflows/integrate-dm.yaml
  .github/workflows/integrate-playground.yaml
  .github/workflows/integrate-tiup.yaml
  .github/workflows/release-tiup.yaml
  .github/workflows/reprotest.yaml
  pkg/cluster/manager/reload.go
  pkg/cluster/spec/grafana.go
  pkg/cluster/spec/grafana_test.go
  pkg/cluster/spec/monitoring.go
  pkg/cluster/spec/monitoring_test.go
  pkg/cluster/task/init_config_test.go
Labels: size/XL, lgtm
